// examples/react/PasswordInputExample.tsx
import React from "react";
import {
  LoongArkPasswordInputRoot,
  LoongArkPasswordInputLabel,
  LoongArkPasswordInputControl,
  LoongArkPasswordInputInput,
  LoongArkPasswordInputIndicator,
  LoongArkPasswordInputVisibilityTrigger,
} from "@loongark/react";
import type {
  PasswordInputSize,
  PasswordInputState,
} from "@loongark/primitives";

interface PasswordInputExampleProps {
  size?: PasswordInputSize;
  state?: PasswordInputState;
  disabled?: boolean;
  readOnly?: boolean;
}

export const PasswordInputExample: React.FC<PasswordInputExampleProps> = ({
  size = "md",
  state = "default",
  disabled = false,
  readOnly = false,
}) => {
  return (
    <LoongArkPasswordInputRoot
      size={size}
      state={state}
      disabled={disabled}
      readOnly={readOnly}
    >
      <LoongArkPasswordInputLabel>Password</LoongArkPasswordInputLabel>
      <LoongArkPasswordInputControl
        size={size}
        state={state}
        disabled={disabled}
      >
        <LoongArkPasswordInputInput
          size={size}
          state={state}
          disabled={disabled}
          readOnly={readOnly}
          placeholder="Enter your password"
        />
        <LoongArkPasswordInputIndicator>●●●</LoongArkPasswordInputIndicator>
        <LoongArkPasswordInputVisibilityTrigger disabled={disabled}>
          Show
        </LoongArkPasswordInputVisibilityTrigger>
      </LoongArkPasswordInputControl>
    </LoongArkPasswordInputRoot>
  );
};

// examples/svelte/PasswordInputExample.svelte
<script lang="ts">
  import {
    LoongArkPasswordInputRoot,
    LoongArkPasswordInputLabel,
    LoongArkPasswordInputControl,
    LoongArkPasswordInputInput,
    LoongArkPasswordInputIndicator,
    LoongArkPasswordInputVisibilityTrigger,
  } from "@loongark/svelte";
  import type { PasswordInputSize, PasswordInputState } from "@loongark/primitives";

  export let size: PasswordInputSize = "md";
  export let state: PasswordInputState = "default";
  export let disabled = false;
  export let readOnly = false;
</script>

<LoongArkPasswordInputRoot {size} {state} {disabled} {readOnly}>
  <LoongArkPasswordInputLabel>Password</LoongArkPasswordInputLabel>
  <LoongArkPasswordInputControl {size} {state} {disabled}>
    <LoongArkPasswordInputInput
      {size}
      {state}
      {disabled}
      {readOnly}
      placeholder="Enter your password"
    />
    <LoongArkPasswordInputIndicator>●●●</LoongArkPasswordInputIndicator>
    <LoongArkPasswordInputVisibilityTrigger {disabled}>
      Show
    </LoongArkPasswordInputVisibilityTrigger>
  </LoongArkPasswordInputControl>
</LoongArkPasswordInputRoot>
