// examples/react/SwitchExample.tsx
import React, { useState } from "react";
import {
  LoongArkSwitch,
  LoongArkSwitchRoot,
  LoongArkSwitchControl,
  LoongArkSwitchThumb,
  LoongArkSwitchLabel,
} from "@loongark/react";

export interface SwitchExampleProps {
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  label?: string;
}

export const SwitchExample: React.FC<SwitchExampleProps> = ({
  size = "md",
  disabled = false,
  label = "通知提醒",
}) => {
  const [checked, setChecked] = useState(false);

  return (
    <LoongArkSwitchRoot
      size={size}
      disabled={disabled}
      checked={checked}
      name="notifications"
      data-testid="switch-root"
      onCheckedChange={(detail: { checked: boolean }) =>
        setChecked(detail.checked)
      }
    >
      <LoongArkSwitchControl
        size={size}
        disabled={disabled}
        data-testid="switch-control"
      >
        <LoongArkSwitchThumb size={size} data-testid="switch-thumb" />
      </LoongArkSwitchControl>
      <LoongArkSwitchLabel disabled={disabled} data-testid="switch-label">
        {label}
      </LoongArkSwitchLabel>
      <LoongArkSwitch.HiddenInput />
    </LoongArkSwitchRoot>
  );
};

// examples/svelte/SwitchExample.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import { LoongArkSwitch } from "@loongark/svelte";
  export let size: "sm" | "md" | "lg" = "md";
  export let disabled = false;
  export let label = "通知提醒";
  let checked = false;
  const dispatch = createEventDispatcher<{ change: { checked: boolean } }>();
</script>

<LoongArkSwitch.Root
  {size}
  {disabled}
  {checked}
  name="notifications"
  onCheckedChange={(details) => {
    checked = details.checked;
    dispatch("change", details);
  }}
  data-testid="switch-root"
  ><LoongArkSwitch.Control data-testid="switch-control"
    ><LoongArkSwitch.Thumb data-testid="switch-thumb" /></LoongArkSwitch.Control
  ><LoongArkSwitch.Label data-testid="switch-label"
    >{label}</LoongArkSwitch.Label
  ><LoongArkSwitch.HiddenInput /></LoongArkSwitch.Root
>
