// examples/svelte/ClipboardExample.svelte
<script lang="ts">
  import {
    LoongArkClipboardRoot,
    LoongArkClipboardLabel,
    LoongArkClipboardControl,
    LoongArkClipboardInput,
    LoongArkClipboardTrigger,
    LoongArkClipboardIndicator,
    LoongArkClipboardValueText,
  } from "@loongark/svelte";
  import type { ClipboardSize } from "@loongark/primitives";

  export let size: ClipboardSize = "md";
  export let disabled = false;

  let value = "https://loongark.dev";

  const handleInput = (event: Event) => {
    value = (event.currentTarget as HTMLInputElement).value;
  };
</script>

<LoongArkClipboardRoot {size} {value}>
  <LoongArkClipboardLabel>Share link</LoongArkClipboardLabel>
  <LoongArkClipboardControl>
    <LoongArkClipboardInput {value} oninput={handleInput} readonly={disabled} />
    <LoongArkClipboardTrigger {disabled}>Copy</LoongArkClipboardTrigger>
  </LoongArkClipboardControl>
  <LoongArkClipboardIndicator>Copied</LoongArkClipboardIndicator>
  <LoongArkClipboardValueText>{value}</LoongArkClipboardValueText>
</LoongArkClipboardRoot>

// examples/solid/ClipboardExample.tsx
import type { Component } from "solid-js";
import { createSignal } from "solid-js";
import {
  LoongArkClipboardRoot,
  LoongArkClipboardLabel,
  LoongArkClipboardControl,
  LoongArkClipboardInput,
  LoongArkClipboardTrigger,
  LoongArkClipboardIndicator,
  LoongArkClipboardValueText,
} from "@loongark/solid";
import type { ClipboardSize } from "@loongark/primitives";

interface ClipboardExampleProps {
  size?: ClipboardSize;
  disabled?: boolean;
}

export const ClipboardExample: Component<ClipboardExampleProps> = (props) => {
  const size = () => props.size ?? "md";
  const disabled = () => props.disabled ?? false;
  const [value, setValue] = createSignal("https://loongark.dev");

  return (
    <LoongArkClipboardRoot size={size()} disabled={disabled()} value={value()}>
      <LoongArkClipboardLabel>Share link</LoongArkClipboardLabel>
      <LoongArkClipboardControl>
        <LoongArkClipboardInput
          value={value()}
          onInput={(event: InputEvent & { currentTarget: HTMLInputElement }) =>
            setValue(event.currentTarget.value)
          }
          readOnly={disabled()}
        />
        <LoongArkClipboardTrigger disabled={disabled()}>Copy</LoongArkClipboardTrigger>
      </LoongArkClipboardControl>
      <LoongArkClipboardIndicator>Copied</LoongArkClipboardIndicator>
      <LoongArkClipboardValueText>{value()}</LoongArkClipboardValueText>
    </LoongArkClipboardRoot>
  );
};
