// examples/react/ComboboxExample.tsx
import React, { useMemo, useState } from "react";
import { createListCollection } from "@ark-ui/react";
import {
  LoongArkComboboxRoot,
  LoongArkComboboxLabel,
  LoongArkComboboxControl,
  LoongArkComboboxInput,
  LoongArkComboboxTrigger,
  LoongArkComboboxClearTrigger,
  LoongArkComboboxPositioner,
  LoongArkComboboxContent,
  LoongArkComboboxList,
  LoongArkComboboxItem,
  LoongArkComboboxItemText,
  LoongArkComboboxItemIndicator,
  type ComboboxSize,
} from "@loongark/react";

interface ComboboxExampleProps {
  size?: ComboboxSize;
  disabled?: boolean;
  label?: string;
  placeholder?: string;
}

const options = [
  { label: "Beijing", value: "beijing" },
  { label: "Shanghai", value: "shanghai" },
  { label: "Guangzhou", value: "guangzhou" },
  { label: "Shenzhen", value: "shenzhen" },
  { label: "Hangzhou", value: "hangzhou" },
];

export const ComboboxExample: React.FC<ComboboxExampleProps> = ({
  size = "md",
  disabled = false,
  label = "City",
  placeholder = "Search...",
}) => {
  const [value, setValue] = useState<string[]>([]);
  const [inputValue, setInputValue] = useState("");

  const filteredOptions = useMemo(() => {
    const query = inputValue.trim().toLowerCase();
    if (!query) return options;
    return options.filter((option) =>
      option.label.toLowerCase().includes(query)
    );
  }, [inputValue]);

  const collection = useMemo(
    () => createListCollection({ items: filteredOptions }),
    [filteredOptions]
  );

  const handleValueChange = (details: { value: string[] }) => {
    setValue(details.value);
    const nextValue = details.value[0];
    const match = options.find((option) => option.value === nextValue);
    setInputValue(match?.label ?? "");
  };

  return (
    <div style={{ padding: "20px", width: "320px" }}>
      <LoongArkComboboxRoot
        size={size}
        disabled={disabled}
        collection={collection}
        value={value}
        inputValue={inputValue}
        onInputValueChange={(details: { inputValue: string }) =>
          setInputValue(details.inputValue)
        }
        onValueChange={handleValueChange}
      >
        <LoongArkComboboxLabel>{label}</LoongArkComboboxLabel>
        <LoongArkComboboxControl>
          <LoongArkComboboxInput placeholder={placeholder} />
          <LoongArkComboboxClearTrigger aria-label="Clear">
            x
          </LoongArkComboboxClearTrigger>
          <LoongArkComboboxTrigger aria-label="Toggle">v</LoongArkComboboxTrigger>
        </LoongArkComboboxControl>
        <LoongArkComboboxPositioner>
          <LoongArkComboboxContent>
            <LoongArkComboboxList>
              {filteredOptions.map((option) => (
                <LoongArkComboboxItem key={option.value} item={option}>
                  <LoongArkComboboxItemText>
                    {option.label}
                  </LoongArkComboboxItemText>
                  <LoongArkComboboxItemIndicator>
                    Check
                  </LoongArkComboboxItemIndicator>
                </LoongArkComboboxItem>
              ))}
            </LoongArkComboboxList>
          </LoongArkComboboxContent>
        </LoongArkComboboxPositioner>
      </LoongArkComboboxRoot>
      <p style={{ marginTop: "16px", fontSize: "14px", color: "#666" }}>
        Selected: {value.length > 0 ? value.join(", ") : "None"}
      </p>
    </div>
  );
};

// examples/solid/ComboboxExample.tsx
import type { Component } from "solid-js";
import { createMemo, createSignal } from "solid-js";
import { createListCollection } from "@ark-ui/solid";
import {
  LoongArkComboboxRoot,
  LoongArkComboboxLabel,
  LoongArkComboboxControl,
  LoongArkComboboxInput,
  LoongArkComboboxTrigger,
  LoongArkComboboxClearTrigger,
  LoongArkComboboxPositioner,
  LoongArkComboboxContent,
  LoongArkComboboxList,
  LoongArkComboboxItem,
  LoongArkComboboxItemText,
  LoongArkComboboxItemIndicator,
} from "@loongark/solid";
import type { ComboboxSize } from "@loongark/primitives";

export interface ComboboxExampleProps {
  size?: ComboboxSize;
  disabled?: boolean;
  label?: string;
  placeholder?: string;
}

const options = [
  { label: "Beijing", value: "beijing" },
  { label: "Shanghai", value: "shanghai" },
  { label: "Guangzhou", value: "guangzhou" },
  { label: "Shenzhen", value: "shenzhen" },
  { label: "Hangzhou", value: "hangzhou" },
];

export const ComboboxExample: Component<ComboboxExampleProps> = (props) => {
  const size = () => props.size ?? "md";
  const disabled = () => props.disabled ?? false;
  const label = () => props.label ?? "City";
  const placeholder = () => props.placeholder ?? "Search...";
  const [value, setValue] = createSignal<string[]>([]);
  const [inputValue, setInputValue] = createSignal("");

  const filteredOptions = createMemo(() => {
    const query = inputValue().trim().toLowerCase();
    if (!query) return options;
    return options.filter((option) =>
      option.label.toLowerCase().includes(query)
    );
  });

  const collection = createMemo(() =>
    createListCollection({ items: filteredOptions() })
  );

  const handleValueChange = (details: { value: string[] }) => {
    setValue(details.value);
    const nextValue = details.value[0];
    const match = options.find((option) => option.value === nextValue);
    setInputValue(match?.label ?? "");
  };

  return (
    <div style={{ padding: "20px", width: "320px" }}>
      <LoongArkComboboxRoot
        size={size()}
        disabled={disabled()}
        collection={collection()}
        value={value()}
        inputValue={inputValue()}
        onInputValueChange={(details: { inputValue: string }) =>
          setInputValue(details.inputValue)
        }
        onValueChange={handleValueChange}
      >
        <LoongArkComboboxLabel>{label()}</LoongArkComboboxLabel>
        <LoongArkComboboxControl>
          <LoongArkComboboxInput placeholder={placeholder()} />
          <LoongArkComboboxClearTrigger aria-label="Clear">
            x
          </LoongArkComboboxClearTrigger>
          <LoongArkComboboxTrigger aria-label="Toggle">v</LoongArkComboboxTrigger>
        </LoongArkComboboxControl>
        <LoongArkComboboxPositioner>
          <LoongArkComboboxContent>
            <LoongArkComboboxList>
              {filteredOptions().map((option) => (
                <LoongArkComboboxItem item={option}>
                  <LoongArkComboboxItemText>{option.label}</LoongArkComboboxItemText>
                  <LoongArkComboboxItemIndicator>
                    Check
                  </LoongArkComboboxItemIndicator>
                </LoongArkComboboxItem>
              ))}
            </LoongArkComboboxList>
          </LoongArkComboboxContent>
        </LoongArkComboboxPositioner>
      </LoongArkComboboxRoot>
      <p style={{ marginTop: "16px", "font-size": "14px", color: "#666" }}>
        Selected: {value().length > 0 ? value().join(", ") : "None"}
      </p>
    </div>
  );
};
