// examples/react/SwitchExample.tsx
import React, { useState } from "react";
import {
  LoongArkSwitch,
  LoongArkSwitchRoot,
  LoongArkSwitchControl,
  LoongArkSwitchThumb,
  LoongArkSwitchLabel,
} from "@loongark/react";

export interface SwitchExampleProps {
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  label?: string;
}

export const SwitchExample: React.FC<SwitchExampleProps> = ({
  size = "md",
  disabled = false,
  label = "通知提醒",
}) => {
  const [checked, setChecked] = useState(false);

  return (
    <LoongArkSwitchRoot
      size={size}
      disabled={disabled}
      checked={checked}
      name="notifications"
      data-testid="switch-root"
      onCheckedChange={(detail: { checked: boolean }) =>
        setChecked(detail.checked)
      }
    >
      <LoongArkSwitchControl
        size={size}
        disabled={disabled}
        data-testid="switch-control"
      >
        <LoongArkSwitchThumb size={size} data-testid="switch-thumb" />
      </LoongArkSwitchControl>
      <LoongArkSwitchLabel disabled={disabled} data-testid="switch-label">
        {label}
      </LoongArkSwitchLabel>
      <LoongArkSwitch.HiddenInput />
    </LoongArkSwitchRoot>
  );
};

// examples/solid/SwitchExample.tsx
/** @jsxImportSource solid-js */
import { createSignal, Component } from "solid-js";
import {
  LoongArkSwitchHiddenInput,
  LoongArkSwitchRoot,
  LoongArkSwitchControl,
  LoongArkSwitchThumb,
  LoongArkSwitchLabel,
} from "@loongark/solid";

export interface SwitchExampleProps {
  size?: "sm" | "md" | "lg";
  disabled?: boolean;
  label?: string;
}

export const SwitchExample: Component<SwitchExampleProps> = (props) => {
  const size = () => props.size ?? "md";
  const disabled = () => props.disabled ?? false;
  const label = () => props.label ?? "通知提醒";
  const [checked, setChecked] = createSignal(false);

  return (
    <LoongArkSwitchRoot
      size={size()}
      disabled={disabled()}
      checked={checked()}
      name="notifications"
      onCheckedChange={(detail: { checked: boolean }) =>
        setChecked(detail.checked)
      }
    >
      <LoongArkSwitchControl size={size()} disabled={disabled()}>
        <LoongArkSwitchThumb size={size()} />
      </LoongArkSwitchControl>
      <LoongArkSwitchLabel disabled={disabled()}>{label()}</LoongArkSwitchLabel>
      <LoongArkSwitchHiddenInput />
    </LoongArkSwitchRoot>
  );
};
