// packages/solid/src/components/textarea.tsx
import {
  splitProps,
  onMount,
  onCleanup,
  createEffect,
  type JSX,
} from "solid-js";
import {
  layoutAttributes,
  mountTextareaAutosize,
  textareaRows,
  type TextareaAutosizeOptions,
} from "@loongark/kit";
export type LoongArkTextareaProps =
  JSX.TextareaHTMLAttributes<HTMLTextAreaElement> & TextareaAutosizeOptions;
export const LoongArkTextarea = (props: LoongArkTextareaProps) => {
  const [local, rest] = splitProps(props, [
    "value",
    "children",
    "readOnly",
    "ref",
    "autoSize",
    "minRows",
    "maxRows",
    "rows",
  ]);
  let element!: HTMLTextAreaElement,
    controller: ReturnType<typeof mountTextareaAutosize> | undefined;
  onMount(() => {
    controller = mountTextareaAutosize(element, () => local);
  });
  createEffect(() => {
    local.value;
    local.autoSize;
    local.minRows;
    local.maxRows;
    queueMicrotask(() => controller?.update());
  });
  onCleanup(() => controller?.destroy());
  return (
    <textarea
      {...layoutAttributes("Textarea")}
      {...rest}
      readOnly={local.readOnly}
      value={local.value}
      data-autosize={local.autoSize ? "true" : undefined}
      rows={local.autoSize ? textareaRows(local).min : local.rows}
      ref={(el) => {
        element = el;
        if (typeof local.ref === "function") local.ref(el);
      }}
    >
      {local.value ?? local.children}
    </textarea>
  );
};

// packages/svelte/src/components/Textarea.svelte
<script lang="ts">
  import { onMount, tick } from "svelte";
  import {
    layoutAttributes,
    mountTextareaAutosize,
    textareaRows,
  } from "@loongark/kit";
  export let value: string | undefined = undefined;
  export let autoSize = false;
  export let minRows: number | undefined = undefined;
  export let maxRows: number | undefined = undefined;
  let element: HTMLTextAreaElement;
  let controller: ReturnType<typeof mountTextareaAutosize> | undefined;
  onMount(() => {
    controller = mountTextareaAutosize(element, () => ({
      autoSize,
      minRows,
      maxRows,
    }));
    return () => controller?.destroy();
  });
  $: {
    value;
    autoSize;
    minRows;
    maxRows;
    tick().then(() => controller?.update());
  }
</script>

<textarea
  {...layoutAttributes("Textarea")}
  {...$$restProps}
  bind:this={element}
  bind:value
  data-autosize={autoSize ? "true" : undefined}
  rows={autoSize ? textareaRows({ minRows, maxRows }).min : $$restProps.rows}
  on:input
  on:change
  on:focus
  on:blur></textarea>
