// packages/solid/src/components/avatar.tsx
/**
 * Avatar component - Solid wrapper.
 * Based on Ark UI Avatar.
 */
import { type Component, type JSX, mergeProps } from "solid-js";
import {
  Avatar as ArkAvatar,
  type AvatarRootProps as ArkAvatarRootProps,
  type AvatarImageProps as ArkAvatarImageProps,
  type AvatarFallbackProps as ArkAvatarFallbackProps,
} from "@ark-ui/solid/avatar";
import type { AvatarSize } from "@loongark/primitives";

export interface LoongArkAvatarRootProps
  extends Omit<ArkAvatarRootProps, "asChild"> {
  size?: AvatarSize;
  children?: JSX.Element;
}

export const LoongArkAvatarRoot: Component<LoongArkAvatarRootProps> = (
  props
) => {
  const merged = mergeProps({ size: "md" as AvatarSize }, props);

  return (
    <ArkAvatar.Root
      {...(props as any)}
      data-scope="avatar"
      data-part="root"
      data-size={merged.size}
    >
      {props.children}
    </ArkAvatar.Root>
  );
};

export const LoongArkAvatarImage: Component<ArkAvatarImageProps> = (props) => {
  return (
    <ArkAvatar.Image {...props} data-scope="avatar" data-part="image" />
  );
};

export const LoongArkAvatarFallback: Component<
  ArkAvatarFallbackProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkAvatar.Fallback {...props} data-scope="avatar" data-part="fallback">
      {props.children}
    </ArkAvatar.Fallback>
  );
};

// packages/react/src/components/avatar.tsx
/**
 * Avatar component - React wrapper.
 * Injects data-scope/data-part and size mapping.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Avatar } from "@ark-ui/react/avatar";
import type { AvatarSize } from "@loongark/primitives";

type ArkAvatarRootProps = ComponentPropsWithoutRef<typeof Avatar.Root>;
type ArkAvatarImageProps = ComponentPropsWithoutRef<typeof Avatar.Image>;
type ArkAvatarFallbackProps = ComponentPropsWithoutRef<typeof Avatar.Fallback>;

export interface LoongArkAvatarRootProps
  extends Omit<ArkAvatarRootProps, "asChild"> {
  size?: AvatarSize;
  children?: ReactNode;
}

export interface LoongArkAvatarImageProps
  extends Omit<ArkAvatarImageProps, "asChild"> {
  children?: ReactNode;
}

export interface LoongArkAvatarFallbackProps
  extends Omit<ArkAvatarFallbackProps, "asChild"> {
  children?: ReactNode;
}

export const LoongArkAvatarRoot = forwardRef<
  HTMLDivElement,
  LoongArkAvatarRootProps
>(({ children, size = "md", ...props }, ref) => {
  return (
    <Avatar.Root
      {...props}
      ref={ref}
      data-scope="avatar"
      data-part="root"
      data-size={size}
    >
      {children}
    </Avatar.Root>
  );
});

LoongArkAvatarRoot.displayName = "LoongArkAvatarRoot";

export const LoongArkAvatarImage = forwardRef<
  HTMLImageElement,
  LoongArkAvatarImageProps
>(({ children, ...props }, ref) => {
  return (
    <Avatar.Image
      {...props}
      ref={ref}
      data-scope="avatar"
      data-part="image"
    >
      {children}
    </Avatar.Image>
  );
});

LoongArkAvatarImage.displayName = "LoongArkAvatarImage";

export const LoongArkAvatarFallback = forwardRef<
  HTMLSpanElement,
  LoongArkAvatarFallbackProps
>(({ children, ...props }, ref) => {
  return (
    <Avatar.Fallback
      {...props}
      ref={ref}
      data-scope="avatar"
      data-part="fallback"
    >
      {children}
    </Avatar.Fallback>
  );
});

LoongArkAvatarFallback.displayName = "LoongArkAvatarFallback";
