// packages/solid/src/components/carousel.tsx
/**
 * Carousel component - Solid wrapper.
 * Uses Ark UI Carousel with data attributes for styling.
 */
import { type Component, type JSX, mergeProps, splitProps } from "solid-js";
import {
  Carousel as ArkCarousel,
  type CarouselRootProps as ArkCarouselRootProps,
  type CarouselItemGroupProps as ArkCarouselItemGroupProps,
  type CarouselItemProps as ArkCarouselItemProps,
  type CarouselControlProps as ArkCarouselControlProps,
  type CarouselNextTriggerProps as ArkCarouselNextTriggerProps,
  type CarouselPrevTriggerProps as ArkCarouselPrevTriggerProps,
  type CarouselIndicatorGroupProps as ArkCarouselIndicatorGroupProps,
  type CarouselIndicatorProps as ArkCarouselIndicatorProps,
  type CarouselAutoplayTriggerProps as ArkCarouselAutoplayTriggerProps,
  type CarouselProgressTextProps as ArkCarouselProgressTextProps,
  type CarouselAutoplayIndicatorProps as ArkCarouselAutoplayIndicatorProps,
} from "@ark-ui/solid/carousel";
import type { CarouselSize } from "@loongark/primitives";

export interface LoongArkCarouselRootProps
  extends Omit<ArkCarouselRootProps, "asChild"> {
  size?: CarouselSize;
  children?: JSX.Element;
}

export const LoongArkCarouselRoot: Component<LoongArkCarouselRootProps> = (
  props
) => {
  const merged = mergeProps({ size: "md" as CarouselSize }, props);
  const [local, others] = splitProps(merged, ["children", "size"]);

  return (
    <ArkCarousel.Root
      {...(others as any)}
      data-scope="carousel"
      data-part="root"
      data-size={local.size}
    >
      {local.children}
    </ArkCarousel.Root>
  );
};

export interface LoongArkCarouselItemGroupProps
  extends Omit<ArkCarouselItemGroupProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselItemGroup: Component<
  LoongArkCarouselItemGroupProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.ItemGroup
      {...others}
      data-scope="carousel"
      data-part="item-group"
    >
      {local.children}
    </ArkCarousel.ItemGroup>
  );
};

export interface LoongArkCarouselItemProps
  extends Omit<ArkCarouselItemProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselItem: Component<LoongArkCarouselItemProps> = (
  props
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.Item {...others} data-scope="carousel" data-part="item">
      {local.children}
    </ArkCarousel.Item>
  );
};

export interface LoongArkCarouselControlProps
  extends Omit<ArkCarouselControlProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselControl: Component<LoongArkCarouselControlProps> = (
  props
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.Control
      {...others}
      data-scope="carousel"
      data-part="control"
    >
      {local.children}
    </ArkCarousel.Control>
  );
};

export interface LoongArkCarouselNextTriggerProps
  extends Omit<ArkCarouselNextTriggerProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselNextTrigger: Component<
  LoongArkCarouselNextTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.NextTrigger
      {...others}
      data-scope="carousel"
      data-part="next-trigger"
    >
      {local.children}
    </ArkCarousel.NextTrigger>
  );
};

export interface LoongArkCarouselPrevTriggerProps
  extends Omit<ArkCarouselPrevTriggerProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselPrevTrigger: Component<
  LoongArkCarouselPrevTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.PrevTrigger
      {...others}
      data-scope="carousel"
      data-part="prev-trigger"
    >
      {local.children}
    </ArkCarousel.PrevTrigger>
  );
};

export interface LoongArkCarouselIndicatorGroupProps
  extends Omit<ArkCarouselIndicatorGroupProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselIndicatorGroup: Component<
  LoongArkCarouselIndicatorGroupProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.IndicatorGroup
      {...others}
      data-scope="carousel"
      data-part="indicator-group"
    >
      {local.children}
    </ArkCarousel.IndicatorGroup>
  );
};

export interface LoongArkCarouselIndicatorProps
  extends Omit<ArkCarouselIndicatorProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselIndicator: Component<
  LoongArkCarouselIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.Indicator
      {...others}
      data-scope="carousel"
      data-part="indicator"
    >
      {local.children}
    </ArkCarousel.Indicator>
  );
};

export interface LoongArkCarouselAutoplayTriggerProps
  extends Omit<ArkCarouselAutoplayTriggerProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselAutoplayTrigger: Component<
  LoongArkCarouselAutoplayTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.AutoplayTrigger
      {...others}
      data-scope="carousel"
      data-part="autoplay-trigger"
    >
      {local.children}
    </ArkCarousel.AutoplayTrigger>
  );
};

export interface LoongArkCarouselProgressTextProps
  extends Omit<ArkCarouselProgressTextProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselProgressText: Component<
  LoongArkCarouselProgressTextProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.ProgressText
      {...others}
      data-scope="carousel"
      data-part="progress-text"
    >
      {local.children}
    </ArkCarousel.ProgressText>
  );
};

export interface LoongArkCarouselAutoplayIndicatorProps
  extends Omit<ArkCarouselAutoplayIndicatorProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkCarouselAutoplayIndicator: Component<
  LoongArkCarouselAutoplayIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkCarousel.AutoplayIndicator
      {...others}
      data-scope="carousel"
      data-part="autoplay-indicator"
    >
      {local.children}
    </ArkCarousel.AutoplayIndicator>
  );
};

// packages/react/src/components/carousel.tsx
/**
 * Carousel component - React wrapper.
 * Uses Ark UI Carousel with data attributes for styling.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Carousel } from "@ark-ui/react/carousel";
import type { CarouselSize } from "@loongark/primitives";

type ArkCarouselRootProps = ComponentPropsWithoutRef<typeof Carousel.Root>;
type ArkCarouselItemGroupProps = ComponentPropsWithoutRef<typeof Carousel.ItemGroup>;
type ArkCarouselItemProps = ComponentPropsWithoutRef<typeof Carousel.Item>;
type ArkCarouselControlProps = ComponentPropsWithoutRef<typeof Carousel.Control>;
type ArkCarouselNextTriggerProps = ComponentPropsWithoutRef<
  typeof Carousel.NextTrigger
>;
type ArkCarouselPrevTriggerProps = ComponentPropsWithoutRef<
  typeof Carousel.PrevTrigger
>;
type ArkCarouselIndicatorGroupProps = ComponentPropsWithoutRef<
  typeof Carousel.IndicatorGroup
>;
type ArkCarouselIndicatorProps = ComponentPropsWithoutRef<
  typeof Carousel.Indicator
>;
type ArkCarouselAutoplayTriggerProps = ComponentPropsWithoutRef<
  typeof Carousel.AutoplayTrigger
>;
type ArkCarouselProgressTextProps = ComponentPropsWithoutRef<
  typeof Carousel.ProgressText
>;
type ArkCarouselAutoplayIndicatorProps = ComponentPropsWithoutRef<
  typeof Carousel.AutoplayIndicator
>;

export interface LoongArkCarouselRootProps
  extends Omit<ArkCarouselRootProps, "asChild"> {
  size?: CarouselSize;
  children?: ReactNode;
}

export const LoongArkCarouselRoot = forwardRef<
  HTMLDivElement,
  LoongArkCarouselRootProps
>(({ size = "md", children, ...props }, ref) => {
  return (
    <Carousel.Root
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="root"
      data-size={size}
    >
      {children}
    </Carousel.Root>
  );
});

LoongArkCarouselRoot.displayName = "LoongArkCarouselRoot";

export const LoongArkCarouselItemGroup = forwardRef<
  HTMLDivElement,
  ArkCarouselItemGroupProps
>((props, ref) => {
  return (
    <Carousel.ItemGroup
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="item-group"
    />
  );
});

LoongArkCarouselItemGroup.displayName = "LoongArkCarouselItemGroup";

export const LoongArkCarouselItem = forwardRef<
  HTMLDivElement,
  ArkCarouselItemProps
>((props, ref) => {
  return (
    <Carousel.Item
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="item"
    />
  );
});

LoongArkCarouselItem.displayName = "LoongArkCarouselItem";

export const LoongArkCarouselControl = forwardRef<
  HTMLDivElement,
  ArkCarouselControlProps
>((props, ref) => {
  return (
    <Carousel.Control
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="control"
    />
  );
});

LoongArkCarouselControl.displayName = "LoongArkCarouselControl";

export const LoongArkCarouselNextTrigger = forwardRef<
  HTMLButtonElement,
  ArkCarouselNextTriggerProps
>((props, ref) => {
  return (
    <Carousel.NextTrigger
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="next-trigger"
    />
  );
});

LoongArkCarouselNextTrigger.displayName = "LoongArkCarouselNextTrigger";

export const LoongArkCarouselPrevTrigger = forwardRef<
  HTMLButtonElement,
  ArkCarouselPrevTriggerProps
>((props, ref) => {
  return (
    <Carousel.PrevTrigger
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="prev-trigger"
    />
  );
});

LoongArkCarouselPrevTrigger.displayName = "LoongArkCarouselPrevTrigger";

export const LoongArkCarouselIndicatorGroup = forwardRef<
  HTMLDivElement,
  ArkCarouselIndicatorGroupProps
>((props, ref) => {
  return (
    <Carousel.IndicatorGroup
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="indicator-group"
    />
  );
});

LoongArkCarouselIndicatorGroup.displayName = "LoongArkCarouselIndicatorGroup";

export const LoongArkCarouselIndicator = forwardRef<
  HTMLButtonElement,
  ArkCarouselIndicatorProps
>((props, ref) => {
  return (
    <Carousel.Indicator
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="indicator"
    />
  );
});

LoongArkCarouselIndicator.displayName = "LoongArkCarouselIndicator";

export const LoongArkCarouselAutoplayTrigger = forwardRef<
  HTMLButtonElement,
  ArkCarouselAutoplayTriggerProps
>((props, ref) => {
  return (
    <Carousel.AutoplayTrigger
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="autoplay-trigger"
    />
  );
});

LoongArkCarouselAutoplayTrigger.displayName = "LoongArkCarouselAutoplayTrigger";

export const LoongArkCarouselProgressText = forwardRef<
  HTMLSpanElement,
  ArkCarouselProgressTextProps
>((props, ref) => {
  return (
    <Carousel.ProgressText
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="progress-text"
    />
  );
});

LoongArkCarouselProgressText.displayName = "LoongArkCarouselProgressText";

export const LoongArkCarouselAutoplayIndicator = forwardRef<
  HTMLDivElement,
  ArkCarouselAutoplayIndicatorProps
>((props, ref) => {
  return (
    <Carousel.AutoplayIndicator
      {...props}
      ref={ref}
      data-scope="carousel"
      data-part="autoplay-indicator"
    />
  );
});

LoongArkCarouselAutoplayIndicator.displayName =
  "LoongArkCarouselAutoplayIndicator";
