// packages/solid/src/components/clipboard.tsx
/**
 * Clipboard component - Solid wrapper.
 * Uses Ark UI Clipboard with data attributes for styling.
 */
import { type Component, type JSX, mergeProps, splitProps } from "solid-js";
import {
  Clipboard as ArkClipboard,
  type ClipboardRootProps as ArkClipboardRootProps,
  type ClipboardLabelProps as ArkClipboardLabelProps,
  type ClipboardControlProps as ArkClipboardControlProps,
  type ClipboardInputProps as ArkClipboardInputProps,
  type ClipboardTriggerProps as ArkClipboardTriggerProps,
  type ClipboardIndicatorProps as ArkClipboardIndicatorProps,
  type ClipboardValueTextProps as ArkClipboardValueTextProps,
} from "@ark-ui/solid/clipboard";
import type { ClipboardSize } from "@loongark/primitives";

export interface LoongArkClipboardRootProps
  extends Omit<ArkClipboardRootProps, "asChild"> {
  size?: ClipboardSize;
  disabled?: boolean;
  children?: JSX.Element;
}

export const LoongArkClipboardRoot: Component<LoongArkClipboardRootProps> = (
  props
) => {
  const merged = mergeProps({ size: "md" as ClipboardSize, disabled: false }, props);
  const [local, others] = splitProps(merged, ["children", "size", "disabled"]);

  return (
    <ArkClipboard.Root
      {...(others as any)}
      disabled={local.disabled}
      data-scope="clipboard"
      data-part="root"
      data-size={local.size}
      data-disabled={local.disabled ? "true" : undefined}
    >
      {local.children}
    </ArkClipboard.Root>
  );
};

export interface LoongArkClipboardLabelProps
  extends Omit<ArkClipboardLabelProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkClipboardLabel: Component<LoongArkClipboardLabelProps> = (
  props
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkClipboard.Label
      {...others}
      data-scope="clipboard"
      data-part="label"
    >
      {local.children}
    </ArkClipboard.Label>
  );
};

export interface LoongArkClipboardControlProps
  extends Omit<ArkClipboardControlProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkClipboardControl: Component<
  LoongArkClipboardControlProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkClipboard.Control
      {...others}
      data-scope="clipboard"
      data-part="control"
    >
      {local.children}
    </ArkClipboard.Control>
  );
};

export interface LoongArkClipboardInputProps
  extends Omit<ArkClipboardInputProps, "asChild"> {}

export const LoongArkClipboardInput: Component<LoongArkClipboardInputProps> = (
  props
) => {
  return (
    <ArkClipboard.Input
      {...props}
      data-scope="clipboard"
      data-part="input"
    />
  );
};

export interface LoongArkClipboardTriggerProps
  extends Omit<ArkClipboardTriggerProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkClipboardTrigger: Component<
  LoongArkClipboardTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkClipboard.Trigger
      {...others}
      data-scope="clipboard"
      data-part="trigger"
    >
      {local.children}
    </ArkClipboard.Trigger>
  );
};

export interface LoongArkClipboardIndicatorProps
  extends Omit<ArkClipboardIndicatorProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkClipboardIndicator: Component<
  LoongArkClipboardIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkClipboard.Indicator
      {...others}
      data-scope="clipboard"
      data-part="indicator"
    >
      {local.children}
    </ArkClipboard.Indicator>
  );
};

export interface LoongArkClipboardValueTextProps
  extends Omit<ArkClipboardValueTextProps, "asChild"> {
  children?: JSX.Element;
}

export const LoongArkClipboardValueText: Component<
  LoongArkClipboardValueTextProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkClipboard.ValueText
      {...others}
      data-scope="clipboard"
      data-part="value-text"
    >
      {local.children}
    </ArkClipboard.ValueText>
  );
};

// packages/react/src/components/clipboard.tsx
/**
 * Clipboard component - React wrapper.
 * Uses Ark UI Clipboard with data attributes for styling.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Clipboard } from "@ark-ui/react/clipboard";
import type { ClipboardSize } from "@loongark/primitives";

type ArkClipboardRootProps = ComponentPropsWithoutRef<typeof Clipboard.Root>;
type ArkClipboardLabelProps = ComponentPropsWithoutRef<typeof Clipboard.Label>;
type ArkClipboardControlProps = ComponentPropsWithoutRef<
  typeof Clipboard.Control
>;
type ArkClipboardInputProps = ComponentPropsWithoutRef<typeof Clipboard.Input>;
type ArkClipboardTriggerProps = ComponentPropsWithoutRef<
  typeof Clipboard.Trigger
>;
type ArkClipboardIndicatorProps = ComponentPropsWithoutRef<
  typeof Clipboard.Indicator
>;
type ArkClipboardValueTextProps = ComponentPropsWithoutRef<
  typeof Clipboard.ValueText
>;

export interface LoongArkClipboardRootProps extends Omit<
  ArkClipboardRootProps,
  "asChild"
> {
  size?: ClipboardSize;
  disabled?: boolean;
  children?: ReactNode;
}

export const LoongArkClipboardRoot = forwardRef<
  HTMLDivElement,
  LoongArkClipboardRootProps
>(({ size = "md", disabled = false, children, ...props }, ref) => {
  return (
    <Clipboard.Root
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="root"
      data-size={size}
      data-disabled={disabled ? "true" : undefined}
    >
      {children}
    </Clipboard.Root>
  );
});

LoongArkClipboardRoot.displayName = "LoongArkClipboardRoot";

export const LoongArkClipboardLabel = forwardRef<
  HTMLLabelElement,
  ArkClipboardLabelProps
>((props, ref) => {
  return (
    <Clipboard.Label
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="label"
    />
  );
});

LoongArkClipboardLabel.displayName = "LoongArkClipboardLabel";

export const LoongArkClipboardControl = forwardRef<
  HTMLDivElement,
  ArkClipboardControlProps
>((props, ref) => {
  return (
    <Clipboard.Control
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="control"
    />
  );
});

LoongArkClipboardControl.displayName = "LoongArkClipboardControl";

export const LoongArkClipboardInput = forwardRef<
  HTMLInputElement,
  ArkClipboardInputProps
>((props, ref) => {
  return (
    <Clipboard.Input
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="input"
    />
  );
});

LoongArkClipboardInput.displayName = "LoongArkClipboardInput";

export const LoongArkClipboardTrigger = forwardRef<
  HTMLButtonElement,
  ArkClipboardTriggerProps
>((props, ref) => {
  return (
    <Clipboard.Trigger
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="trigger"
    />
  );
});

LoongArkClipboardTrigger.displayName = "LoongArkClipboardTrigger";

export const LoongArkClipboardIndicator = forwardRef<
  HTMLDivElement,
  ArkClipboardIndicatorProps
>((props, ref) => {
  return (
    <Clipboard.Indicator
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="indicator"
    />
  );
});

LoongArkClipboardIndicator.displayName = "LoongArkClipboardIndicator";

export const LoongArkClipboardValueText = forwardRef<
  HTMLDivElement,
  ArkClipboardValueTextProps
>((props, ref) => {
  return (
    <Clipboard.ValueText
      {...props}
      ref={ref}
      data-scope="clipboard"
      data-part="value-text"
    />
  );
});

LoongArkClipboardValueText.displayName = "LoongArkClipboardValueText";
