// packages/solid/src/components/dialog.ts
import { createComponent } from "solid-js";
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
import { dataProps } from "../data-props";
import type { JSX } from "solid-js";
import { LoongArkPortal } from "./portal";
import { Dialog as ArkDialog } from "@ark-ui/solid/dialog";
import { ark } from "@ark-ui/solid";
import type { DialogPrimitiveProps } from "@loongark/primitives";
import type { Component } from "solid-js";
import { mergeProps, splitProps } from "solid-js";
import { boolAttr } from "../utils";

export type DialogSize = NonNullable<DialogPrimitiveProps["size"]>;
export type DialogPlacement = NonNullable<DialogPrimitiveProps["placement"]>;
export type DialogMotion = NonNullable<DialogPrimitiveProps["motion"]>;

export interface LoongArkDialogOverlayProps extends Omit<
  JSX.HTMLAttributes<HTMLElement>,
  "ref"
> {
  blur?: boolean;
  children?: JSX.Element;
}

export const LoongArkDialogOverlay: Component<LoongArkDialogOverlayProps> = (
  props,
) => {
  const [local, rest] = splitProps(mergeProps({ blur: true }, props), [
    "blur",
    "children",
  ]);
  return ArkDialog.Backdrop(
    dataProps(
      mergeProps(rest, {
        get children() {
          return local.children;
        },
        "data-scope": "dialog",
        "data-part": "backdrop",
        get "data-blur"() {
          return boolAttr(local.blur);
        },
      }),
    ),
  );
};

interface DialogContentProps
  extends
    Partial<DialogPrimitiveProps>,
    Omit<JSX.HTMLAttributes<HTMLElement>, "ref"> {
  overlayBlur?: boolean;
  children?: JSX.Element;
}

const dialogContentDefaults: Required<
  Pick<DialogContentProps, "size" | "motion" | "placement" | "overlayBlur">
> = {
  size: "md",
  motion: "scale",
  placement: "center",
  overlayBlur: true,
};

export const LoongArkDialogContent: Component<DialogContentProps> = (props) => {
  const [local, rest] = splitProps(mergeProps(dialogContentDefaults, props), [
    "children",
    "size",
    "motion",
    "placement",
    "overlayBlur",
  ]);

  return ArkDialog.Content(
    dataProps(
      mergeProps(rest, {
        get children() {
          return local.children;
        },
        "data-scope": "dialog",
        "data-part": "content",
        get "data-size"() {
          return local.size;
        },
        get "data-motion"() {
          return local.motion;
        },
        get "data-placement"() {
          return local.placement;
        },
        get "data-overlay-blur"() {
          return boolAttr(local.overlayBlur);
        },
      }),
    ),
  );
};

interface DialogTextProps extends Omit<JSX.HTMLAttributes<HTMLElement>, "ref"> {
  children?: JSX.Element;
}

export const LoongArkDialogTitle: Component<DialogTextProps> = (props) => {
  const [local, rest] = splitProps(props, ["children"]);
  return ArkDialog.Title(
    dataProps(
      mergeProps(rest, {
        get children() {
          return local.children;
        },
        "data-scope": "dialog",
        "data-part": "title",
      }),
    ),
  );
};

export const LoongArkDialogDescription: Component<DialogTextProps> = (
  props,
) => {
  const [local, rest] = splitProps(props, ["children"]);
  return ArkDialog.Description(
    dataProps(
      mergeProps(rest, {
        get children() {
          return local.children;
        },
        "data-scope": "dialog",
        "data-part": "description",
      }),
    ),
  );
};

export const LoongArkDialogFooter: Component<DialogTextProps> = (props) => {
  const [local, rest] = splitProps(props, ["children"]);
  return ark.footer(
    dataProps(
      mergeProps(rest, {
        get children() {
          return local.children;
        },
        "data-scope": "dialog",
        "data-part": "footer",
      }),
    ),
  );
};

export const LoongArkDialogCloseTrigger: Component<DialogTextProps> = (
  props,
) => {
  const [local, rest] = splitProps(props, ["children"]);
  return ArkDialog.CloseTrigger(
    dataProps(
      mergeProps(rest, {
        get children() {
          return (
            local.children ??
            createComponent(LoongArkIcon, { icon: controlIcons.close })
          );
        },
        "aria-label": rest["aria-label"] ?? "Close dialog",
        "data-scope": "dialog",
        "data-part": "close-trigger",
      }),
    ),
  );
};

export const LoongArkDialog = {
  Root: ArkDialog.Root,
  Trigger: ArkDialog.Trigger,
  Positioner: ArkDialog.Positioner,
  Portal: LoongArkPortal,
  Overlay: LoongArkDialogOverlay,
  Content: LoongArkDialogContent,
  Title: LoongArkDialogTitle,
  Description: LoongArkDialogDescription,
  Footer: LoongArkDialogFooter,
  CloseTrigger: LoongArkDialogCloseTrigger,
};

export const LoongArkDialogRoot = ArkDialog.Root;
export const LoongArkDialogTrigger = ArkDialog.Trigger;

export const LoongArkDialogPositioner = ArkDialog.Positioner;
export const LoongArkDialogPortal = LoongArkPortal;

// packages/react/src/components/dialog.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
import type {
  HTMLAttributes,
  InputHTMLAttributes,
  TextareaHTMLAttributes,
  ButtonHTMLAttributes,
} from "react";
import { dataProps } from "../data-props";
import { Dialog as ArkDialog } from "@ark-ui/react/dialog";
import { Portal as ArkPortal } from "./portal";
import { ark } from "@ark-ui/react";
import type { DialogPrimitiveProps } from "@loongark/primitives";
import { createElement, forwardRef } from "react";
import type { ReactNode } from "react";

export type DialogSize = NonNullable<DialogPrimitiveProps["size"]>;
export type DialogPlacement = NonNullable<DialogPrimitiveProps["placement"]>;
export type DialogMotion = NonNullable<DialogPrimitiveProps["motion"]>;

export interface LoongArkDialogOverlayProps extends HTMLAttributes<HTMLElement> {
  blur?: boolean;
  children?: ReactNode;
}

export const LoongArkDialogOverlay = forwardRef<
  HTMLDivElement,
  LoongArkDialogOverlayProps
>(({ blur = true, children, ...rest }, ref) =>
  createElement(
    ArkDialog.Backdrop,
    dataProps({
      ...rest,
      ref,
      "data-scope": "dialog",
      "data-part": "backdrop",
      "data-blur": blur ? "true" : undefined,
    }),
    children,
  ),
);

LoongArkDialogOverlay.displayName = "LoongArkDialogOverlay";

export interface LoongArkDialogContentProps
  extends Partial<DialogPrimitiveProps>, HTMLAttributes<HTMLElement> {
  children?: ReactNode;
}

export const LoongArkDialogContent = forwardRef<
  HTMLDivElement,
  LoongArkDialogContentProps
>(
  (
    {
      children,
      size = "md",
      motion = "scale",
      placement = "center",
      overlayBlur = true,
      ...rest
    },
    ref,
  ) =>
    createElement(
      ArkDialog.Content,
      dataProps({
        ...rest,
        ref,
        "data-scope": "dialog",
        "data-part": "content",
        "data-size": size,
        "data-motion": motion,
        "data-placement": placement,
        "data-overlay-blur": overlayBlur ? "true" : undefined,
      }),
      children,
    ),
);

LoongArkDialogContent.displayName = "LoongArkDialogContent";

export const LoongArkDialogTitle = ({
  children,
  ...rest
}: {
  children?: ReactNode;
}) =>
  createElement(
    ArkDialog.Title,
    dataProps({
      ...rest,
      "data-scope": "dialog",
      "data-part": "title",
    }),
    children,
  );

export const LoongArkDialogDescription = ({
  children,
  ...rest
}: {
  children?: ReactNode;
}) =>
  createElement(
    ArkDialog.Description,
    dataProps({
      ...rest,
      "data-scope": "dialog",
      "data-part": "description",
    }),
    children,
  );

export const LoongArkDialogFooter = ({
  children,
  ...rest
}: {
  children?: ReactNode;
}) =>
  createElement(
    ark.footer,
    dataProps({
      ...rest,
      "data-scope": "dialog",
      "data-part": "footer",
    }),
    children,
  );

export interface LoongArkDialogCloseTriggerProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  children?: ReactNode;
  asChild?: boolean;
}

export const LoongArkDialogCloseTrigger = ({
  children,
  asChild,
  ...rest
}: LoongArkDialogCloseTriggerProps) => {
  const decorate = !asChild;
  return createElement(
    ArkDialog.CloseTrigger,
    dataProps({
      ...rest,
      ...(asChild ? { asChild } : {}),
      ...(decorate
        ? {
            "aria-label": rest["aria-label"] ?? "Close dialog",
            "data-scope": "dialog",
            "data-part": "close-trigger",
          }
        : {}),
    }),
    children ??
      (decorate
        ? createElement(LoongArkIcon, { icon: controlIcons.close })
        : null),
  );
};

export const LoongArkDialog: {
  Root: typeof ArkDialog.Root;
  Trigger: typeof ArkDialog.Trigger;
  Positioner: typeof ArkDialog.Positioner;
  Portal: typeof ArkPortal;
  Overlay: typeof LoongArkDialogOverlay;
  Content: typeof LoongArkDialogContent;
  Title: typeof LoongArkDialogTitle;
  Description: typeof LoongArkDialogDescription;
  Footer: typeof LoongArkDialogFooter;
  CloseTrigger: typeof LoongArkDialogCloseTrigger;
} = {
  Root: ArkDialog.Root,
  Trigger: ArkDialog.Trigger,
  Positioner: ArkDialog.Positioner,

  Portal: ArkPortal,
  Overlay: LoongArkDialogOverlay,
  Content: LoongArkDialogContent,
  Title: LoongArkDialogTitle,
  Description: LoongArkDialogDescription,
  Footer: LoongArkDialogFooter,
  CloseTrigger: LoongArkDialogCloseTrigger,
};

export const LoongArkDialogRoot = ArkDialog.Root;
export const LoongArkDialogTrigger = ArkDialog.Trigger;

export const LoongArkDialogPositioner = ArkDialog.Positioner;
export const LoongArkDialogPortal = ArkPortal;
