// packages/solid/src/components/drawer-grabber.tsx
import type { ComponentProps } from "solid-js";
import { Drawer } from "@ark-ui/solid/drawer";
import { mergeProps } from "@zag-js/solid";
import { preventDrawerGrabberSelection } from "@loongark/kit";

export const DrawerGrabber = (props: ComponentProps<typeof Drawer.Grabber>) => (
  <Drawer.Grabber
    {...mergeProps(props, { onPointerDown: preventDrawerGrabberSelection })}
  />
);

// packages/react/src/components/drawer-grabber.ts
import { createElement, forwardRef, type ComponentPropsWithoutRef } from "react";
import { Drawer } from "@ark-ui/react/drawer";
import { mergeProps } from "@zag-js/react";
import { preventDrawerGrabberSelection } from "@loongark/kit";

export const DrawerGrabber = forwardRef<
  HTMLDivElement,
  ComponentPropsWithoutRef<typeof Drawer.Grabber>
>((props, ref) =>
  createElement(Drawer.Grabber, {
    ...mergeProps(props, { onPointerDown: preventDrawerGrabberSelection }),
    ref,
  }),
);
