// packages/solid/src/components/filter-bar.tsx
import { type Component, type JSX } from "solid-js";
import { boolAttr } from "../utils";

export interface LoongArkFilterBarProps
  extends JSX.HTMLAttributes<HTMLDivElement> {
  dense?: boolean;
  align?: "start" | "center";
  children?: JSX.Element;
}

export const LoongArkFilterBar: Component<LoongArkFilterBarProps> = (props) => {
  const { dense, align = "start", children, ...rest } = props;

  return (
    <div
      {...rest}
      data-scope="filter-bar"
      data-part="root"
      data-dense={boolAttr(!!dense)}
      data-align={align === "center" ? "center" : undefined}
    >
      {children}
    </div>
  );
};

export type LoongArkFilterSectionProps = JSX.HTMLAttributes<HTMLDivElement>;

const createFilterSection = (
  part: "search" | "filters" | "actions"
): Component<LoongArkFilterSectionProps> => {
  const Section: Component<LoongArkFilterSectionProps> = (props) => {
    const { children, ...rest } = props;
    return (
      <div {...rest} data-scope="filter-bar" data-part={part}>
        {children}
      </div>
    );
  };

  return Section;
};

export const LoongArkFilterBarSearch = createFilterSection("search");
export const LoongArkFilterBarFilters = createFilterSection("filters");
export const LoongArkFilterBarActions = createFilterSection("actions");

export const LoongArkFilterDivider: Component<
  Omit<JSX.HTMLAttributes<HTMLSpanElement>, "children">
> = (props) => {
  return (
    <span
      {...props}
      role="presentation"
      aria-hidden="true"
      data-scope="filter-bar"
      data-part="divider"
    />
  );
};

export interface LoongArkFilterChipProps
  extends JSX.HTMLAttributes<HTMLButtonElement> {
  active?: boolean;
  type?: "button" | "submit" | "reset";
  children?: JSX.Element;
}

export const LoongArkFilterChip: Component<LoongArkFilterChipProps> = (
  props
) => {
  const { active, type = "button", children, ...rest } = props;

  return (
    <button
      {...rest}
      type={type}
      data-scope="filter-bar"
      data-part="chip"
      data-active={boolAttr(!!active)}
      aria-pressed={active ? "true" : "false"}
    >
      {children}
    </button>
  );
};

// packages/react/src/components/filter-bar.tsx
import { ark } from "@ark-ui/react";
import { forwardRef, ReactNode } from "react";

export interface LoongArkFilterBarProps extends Record<string, unknown> {
  dense?: boolean;
  align?: "start" | "center";
  children?: ReactNode;
}

export const LoongArkFilterBar = forwardRef<
  HTMLDivElement,
  LoongArkFilterBarProps
>(({ dense, align = "start", ...rest }, ref) => {
  return (
    <ark.div
      {...rest}
      ref={ref}
      data-scope="filter-bar"
      data-part="root"
      data-dense={dense ? "true" : undefined}
      data-align={align === "center" ? "center" : undefined}
    />
  );
});

LoongArkFilterBar.displayName = "LoongArkFilterBar";

export interface LoongArkFilterSectionProps extends Record<string, unknown> {
  children?: ReactNode;
}

export const LoongArkFilterBarSearch = forwardRef<
  HTMLDivElement,
  LoongArkFilterSectionProps
>(({ children, ...rest }, ref) => (
  <ark.div {...rest} ref={ref} data-scope="filter-bar" data-part="search">
    {children}
  </ark.div>
));

LoongArkFilterBarSearch.displayName = "LoongArkFilterBarSearch";

export const LoongArkFilterBarFilters = forwardRef<
  HTMLDivElement,
  LoongArkFilterSectionProps
>(({ children, ...rest }, ref) => (
  <ark.div {...rest} ref={ref} data-scope="filter-bar" data-part="filters">
    {children}
  </ark.div>
));

LoongArkFilterBarFilters.displayName = "LoongArkFilterBarFilters";

export const LoongArkFilterBarActions = forwardRef<
  HTMLDivElement,
  LoongArkFilterSectionProps
>(({ children, ...rest }, ref) => (
  <ark.div {...rest} ref={ref} data-scope="filter-bar" data-part="actions">
    {children}
  </ark.div>
));

LoongArkFilterBarActions.displayName = "LoongArkFilterBarActions";

export const LoongArkFilterDivider = forwardRef<
  HTMLSpanElement,
  Record<string, unknown>
>((props, ref) => (
  <ark.span
    {...props}
    ref={ref}
    role="presentation"
    aria-hidden="true"
    data-scope="filter-bar"
    data-part="divider"
  />
));

LoongArkFilterDivider.displayName = "LoongArkFilterDivider";

export interface LoongArkFilterChipProps extends Record<string, unknown> {
  active?: boolean;
  children?: ReactNode;
  type?: "button" | "submit" | "reset";
}

export const LoongArkFilterChip = forwardRef<
  HTMLButtonElement,
  LoongArkFilterChipProps
>(({ active = false, type = "button", ...rest }, ref) => (
  <ark.button
    {...rest}
    ref={ref}
    type={type}
    data-scope="filter-bar"
    data-part="chip"
    data-active={active ? "true" : undefined}
    aria-pressed={active ? "true" : "false"}
  />
));

LoongArkFilterChip.displayName = "LoongArkFilterChip";
