// packages/solid/src/components/listbox.tsx
/**
 * Listbox component - Solid wrapper.
 * Uses Ark UI Listbox with data attributes for styling.
 */
import { type Component, type JSX, mergeProps } from "solid-js";
import {
  Listbox as ArkListbox,
  type ListboxRootProps as ArkListboxRootProps,
  type ListboxLabelProps as ArkListboxLabelProps,
  type ListboxContentProps as ArkListboxListProps,
  type ListboxItemGroupProps as ArkListboxItemGroupProps,
  type ListboxItemGroupLabelProps as ArkListboxItemGroupLabelProps,
  type ListboxItemProps as ArkListboxItemProps,
  type ListboxItemTextProps as ArkListboxItemTextProps,
  type ListboxItemIndicatorProps as ArkListboxItemIndicatorProps,
} from "@ark-ui/solid/listbox";
import type { ListboxOrientation, ListboxSize } from "@loongark/primitives";

export interface LoongArkListboxRootProps<
  T extends object = object,
> extends Omit<ArkListboxRootProps<T>, "asChild"> {
  size?: ListboxSize;
  orientation?: ListboxOrientation;
  children?: JSX.Element;
}

export const LoongArkListboxRoot = <T extends object>(
  props: LoongArkListboxRootProps<T>,
): JSX.Element => {
  const merged = mergeProps(
    {
      size: "md" as ListboxSize,
      orientation: "vertical" as ListboxOrientation,
    },
    props,
  );

  return (
    <ArkListbox.Root
      {...props}
      orientation={merged.orientation}
      data-scope="listbox"
      data-part="root"
      data-size={merged.size}
      data-orientation={merged.orientation}
    >
      {props.children}
    </ArkListbox.Root>
  );
};

export const LoongArkListboxLabel: Component<
  ArkListboxLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.Label {...props} data-scope="listbox" data-part="label">
      {props.children}
    </ArkListbox.Label>
  );
};

export const LoongArkListboxList: Component<
  ArkListboxListProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.Content {...props} data-scope="listbox" data-part="list">
      {props.children}
    </ArkListbox.Content>
  );
};

export const LoongArkListboxItemGroup: Component<
  ArkListboxItemGroupProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.ItemGroup
      {...props}
      data-scope="listbox"
      data-part="item-group"
    >
      {props.children}
    </ArkListbox.ItemGroup>
  );
};

export const LoongArkListboxItemGroupLabel: Component<
  ArkListboxItemGroupLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.ItemGroupLabel
      {...props}
      data-scope="listbox"
      data-part="item-group-label"
    >
      {props.children}
    </ArkListbox.ItemGroupLabel>
  );
};

export const LoongArkListboxItem: Component<
  ArkListboxItemProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.Item {...props} data-scope="listbox" data-part="item">
      {props.children}
    </ArkListbox.Item>
  );
};

export const LoongArkListboxItemText: Component<
  ArkListboxItemTextProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.ItemText {...props} data-scope="listbox" data-part="item-text">
      {props.children}
    </ArkListbox.ItemText>
  );
};

export const LoongArkListboxItemIndicator: Component<
  ArkListboxItemIndicatorProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkListbox.ItemIndicator
      {...props}
      data-scope="listbox"
      data-part="item-indicator"
    >
      {props.children}
    </ArkListbox.ItemIndicator>
  );
};

// packages/react/src/components/listbox.tsx
/**
 * Listbox component - React wrapper.
 * Uses Ark UI Listbox with data attributes for styling.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Listbox } from "@ark-ui/react/listbox";
import type { ListboxOrientation, ListboxSize } from "@loongark/primitives";

type ArkListboxRootProps<T = object> =
  import("@ark-ui/react/listbox").ListboxRootProps<T>;
type ArkListboxLabelProps = ComponentPropsWithoutRef<typeof Listbox.Label>;
type ArkListboxListProps = ComponentPropsWithoutRef<typeof Listbox.Content>;
type ArkListboxItemGroupProps = ComponentPropsWithoutRef<
  typeof Listbox.ItemGroup
>;
type ArkListboxItemGroupLabelProps = ComponentPropsWithoutRef<
  typeof Listbox.ItemGroupLabel
>;
type ArkListboxItemProps = ComponentPropsWithoutRef<typeof Listbox.Item>;
type ArkListboxItemTextProps = ComponentPropsWithoutRef<
  typeof Listbox.ItemText
>;
type ArkListboxItemIndicatorProps = ComponentPropsWithoutRef<
  typeof Listbox.ItemIndicator
>;

export interface LoongArkListboxRootProps<T = object> extends Omit<
  ArkListboxRootProps<T>,
  "asChild"
> {
  size?: ListboxSize;
  orientation?: ListboxOrientation;
  children?: ReactNode;
}

export interface LoongArkListboxLabelProps extends Omit<
  ArkListboxLabelProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkListboxListProps extends Omit<
  ArkListboxListProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkListboxItemGroupProps extends Omit<
  ArkListboxItemGroupProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkListboxItemGroupLabelProps extends Omit<
  ArkListboxItemGroupLabelProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkListboxItemProps extends Omit<
  ArkListboxItemProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkListboxItemTextProps extends Omit<
  ArkListboxItemTextProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkListboxItemIndicatorProps extends Omit<
  ArkListboxItemIndicatorProps,
  "asChild"
> {
  children?: ReactNode;
}

export const LoongArkListboxRoot = forwardRef<
  HTMLDivElement,
  LoongArkListboxRootProps
>(({ children, size = "md", orientation = "vertical", ...props }, ref) => {
  return (
    <Listbox.Root
      {...props}
      ref={ref}
      orientation={orientation}
      data-scope="listbox"
      data-part="root"
      data-size={size}
      data-orientation={orientation}
    >
      {children}
    </Listbox.Root>
  );
}) as (<T>(
  props: LoongArkListboxRootProps<T> &
    import("react").RefAttributes<HTMLDivElement>,
) => import("react").ReactElement | null) & { displayName?: string };

LoongArkListboxRoot.displayName = "LoongArkListboxRoot";

export const LoongArkListboxLabel = forwardRef<
  HTMLLabelElement,
  LoongArkListboxLabelProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.Label {...props} ref={ref} data-scope="listbox" data-part="label">
      {children}
    </Listbox.Label>
  );
});

LoongArkListboxLabel.displayName = "LoongArkListboxLabel";

export const LoongArkListboxList = forwardRef<
  HTMLDivElement,
  LoongArkListboxListProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.Content {...props} ref={ref} data-scope="listbox" data-part="list">
      {children}
    </Listbox.Content>
  );
});

LoongArkListboxList.displayName = "LoongArkListboxList";

export const LoongArkListboxItemGroup = forwardRef<
  HTMLDivElement,
  LoongArkListboxItemGroupProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.ItemGroup
      {...props}
      ref={ref}
      data-scope="listbox"
      data-part="item-group"
    >
      {children}
    </Listbox.ItemGroup>
  );
});

LoongArkListboxItemGroup.displayName = "LoongArkListboxItemGroup";

export const LoongArkListboxItemGroupLabel = forwardRef<
  HTMLDivElement,
  LoongArkListboxItemGroupLabelProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.ItemGroupLabel
      {...props}
      ref={ref}
      data-scope="listbox"
      data-part="item-group-label"
    >
      {children}
    </Listbox.ItemGroupLabel>
  );
});

LoongArkListboxItemGroupLabel.displayName = "LoongArkListboxItemGroupLabel";

export const LoongArkListboxItem = forwardRef<
  HTMLDivElement,
  LoongArkListboxItemProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.Item {...props} ref={ref} data-scope="listbox" data-part="item">
      {children}
    </Listbox.Item>
  );
});

LoongArkListboxItem.displayName = "LoongArkListboxItem";

export const LoongArkListboxItemText = forwardRef<
  HTMLDivElement,
  LoongArkListboxItemTextProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.ItemText
      {...props}
      ref={ref}
      data-scope="listbox"
      data-part="item-text"
    >
      {children}
    </Listbox.ItemText>
  );
});

LoongArkListboxItemText.displayName = "LoongArkListboxItemText";

export const LoongArkListboxItemIndicator = forwardRef<
  HTMLDivElement,
  LoongArkListboxItemIndicatorProps
>(({ children, ...props }, ref) => {
  return (
    <Listbox.ItemIndicator
      {...props}
      ref={ref}
      data-scope="listbox"
      data-part="item-indicator"
    >
      {children}
    </Listbox.ItemIndicator>
  );
});

LoongArkListboxItemIndicator.displayName = "LoongArkListboxItemIndicator";
