// packages/solid/src/components/pinInput.tsx
import { PinInput } from "@ark-ui/solid/pin-input";
import type { PinInputPrimitiveProps } from "@loongark/primitives";
import { mergeProps, splitProps, type Component, type JSX } from "solid-js";

export type PinInputSize = NonNullable<PinInputPrimitiveProps["size"]>;
export type PinInputState = NonNullable<PinInputPrimitiveProps["state"]>;

export interface LoongArkPinInputRootProps {
  children?: JSX.Element;
  size?: PinInputSize;
  state?: PinInputState;
  disabled?: boolean;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (details: { value: string[]; valueAsString: string }) => void;
  onValueComplete?: (details: {
    value: string[];
    valueAsString: string;
  }) => void;
  type?: "alphanumeric" | "numeric" | "alphabetic";
  mask?: boolean;
  otp?: boolean;
  placeholder?: string;
  autoFocus?: boolean;
  selectOnFocus?: boolean;
  blurOnComplete?: boolean;
  autoCapitalize?: boolean;
}

export const LoongArkPinInputRoot: Component<LoongArkPinInputRootProps> = (
  props
) => {
  const merged = mergeProps(
    {
      size: "md" as PinInputSize,
      state: "default" as PinInputState,
      disabled: false,
    },
    props
  );
  const [local, others] = splitProps(merged, [
    "children",
    "size",
    "state",
    "disabled",
  ]);

  return (
    <PinInput.Root
      {...others}
      disabled={local.disabled}
      data-lk-pin-input=""
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-disabled={local.disabled ? "true" : undefined}
    >
      {local.children}
    </PinInput.Root>
  );
};

export interface LoongArkPinInputControlProps {
  children?: JSX.Element;
  size?: PinInputSize;
}

export const LoongArkPinInputControl: Component<
  LoongArkPinInputControlProps
> = (props) => {
  const merged = mergeProps({ size: "md" as PinInputSize }, props);
  const [local, others] = splitProps(merged, ["children", "size"]);

  return (
    <PinInput.Control
      {...others}
      data-lk-pin-input-control=""
      data-size={local.size}
    >
      {local.children}
    </PinInput.Control>
  );
};

export interface LoongArkPinInputInputProps {
  size?: PinInputSize;
  state?: PinInputState;
  index: number;
  autoCapitalize?: boolean;
}

export const LoongArkPinInputInput: Component<LoongArkPinInputInputProps> = (
  props
) => {
  const merged = mergeProps(
    {
      size: "md" as PinInputSize,
      state: "default" as PinInputState,
      autoCapitalize: false,
    },
    props
  );
  const [local, others] = splitProps(merged, [
    "size",
    "state",
    "index",
    "autoCapitalize",
  ]);

  return (
    <PinInput.Input
      {...others}
      index={local.index}
      data-lk-pin-input-input=""
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-capitalize={local.autoCapitalize ? "true" : undefined}
    />
  );
};

export interface LoongArkPinInputLabelProps {
  children?: JSX.Element;
}

export const LoongArkPinInputLabel: Component<LoongArkPinInputLabelProps> = (
  props
) => {
  const [local, others] = splitProps(props, ["children"]);

  return (
    <PinInput.Label {...others} data-lk-pin-input-label="">
      {local.children}
    </PinInput.Label>
  );
};

export const LoongArkPinInputHiddenInput = PinInput.HiddenInput;

export const LoongArkPinInput = {
  Root: LoongArkPinInputRoot,
  Control: LoongArkPinInputControl,
  Input: LoongArkPinInputInput,
  Label: LoongArkPinInputLabel,
  HiddenInput: LoongArkPinInputHiddenInput,
};

// packages/react/src/components/pinInput.tsx
import { PinInput } from "@ark-ui/react/pin-input";
import type { PinInputPrimitiveProps } from "@loongark/primitives";
import { createElement, forwardRef } from "react";
import type { ReactNode } from "react";

export type PinInputSize = NonNullable<PinInputPrimitiveProps["size"]>;
export type PinInputState = NonNullable<PinInputPrimitiveProps["state"]>;

export interface LoongArkPinInputRootProps
  extends Partial<PinInputPrimitiveProps> {
  children?: ReactNode;
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (details: { value: string[]; valueAsString: string }) => void;
  onValueComplete?: (details: {
    value: string[];
    valueAsString: string;
  }) => void;
  type?: "alphanumeric" | "numeric" | "alphabetic";
  mask?: boolean;
  otp?: boolean;
  placeholder?: string;
  autoFocus?: boolean;
  selectOnFocus?: boolean;
  blurOnComplete?: boolean;
  autoCapitalize?: boolean;
  [key: string]: unknown;
}

export const LoongArkPinInputRoot = forwardRef<
  HTMLDivElement,
  LoongArkPinInputRootProps
>(
  (
    { children, size = "md", state = "default", disabled = false, ...rest },
    ref
  ) =>
    createElement(
      PinInput.Root,
      {
        ...rest,
        ref,
        disabled,
        "data-lk-pin-input": "",
        "data-size": size,
        "data-state": state !== "default" ? state : undefined,
        "data-disabled": disabled ? "true" : undefined,
      },
      children
    )
);

LoongArkPinInputRoot.displayName = "LoongArkPinInputRoot";

export interface LoongArkPinInputControlProps
  extends Partial<PinInputPrimitiveProps> {
  children?: ReactNode;
  [key: string]: unknown;
}

export const LoongArkPinInputControl = forwardRef<
  HTMLDivElement,
  LoongArkPinInputControlProps
>(({ children, size = "md", ...rest }, ref) =>
  createElement(
    PinInput.Control,
    {
      ...rest,
      ref,
      "data-lk-pin-input-control": "",
      "data-size": size,
    },
    children
  )
);

LoongArkPinInputControl.displayName = "LoongArkPinInputControl";

export interface LoongArkPinInputInputProps
  extends Partial<PinInputPrimitiveProps> {
  index: number;
  autoCapitalize?: boolean;
  [key: string]: unknown;
}

export const LoongArkPinInputInput = forwardRef<
  HTMLInputElement,
  LoongArkPinInputInputProps
>(
  (
    { size = "md", state = "default", index, autoCapitalize = false, ...rest },
    ref
  ) =>
    createElement(PinInput.Input, {
      ...rest,
      ref,
      index,
      style: autoCapitalize ? { textTransform: "uppercase" } : undefined,
      "data-lk-pin-input-input": "",
      "data-size": size,
      "data-state": state !== "default" ? state : undefined,
    })
);

LoongArkPinInputInput.displayName = "LoongArkPinInputInput";

export interface LoongArkPinInputLabelProps {
  children?: ReactNode;
  [key: string]: unknown;
}

export const LoongArkPinInputLabel = ({
  children,
  ...rest
}: LoongArkPinInputLabelProps) =>
  createElement(
    PinInput.Label,
    {
      ...rest,
      "data-lk-pin-input-label": "",
    },
    children
  );

export const LoongArkPinInputHiddenInput: React.ComponentType<
  React.ComponentPropsWithoutRef<typeof PinInput.HiddenInput>
> = PinInput.HiddenInput;

export const LoongArkPinInput: {
  Root: typeof LoongArkPinInputRoot;
  Control: typeof LoongArkPinInputControl;
  Input: typeof LoongArkPinInputInput;
  Label: typeof LoongArkPinInputLabel;
  HiddenInput: typeof LoongArkPinInputHiddenInput;
} = {
  Root: LoongArkPinInputRoot,
  Control: LoongArkPinInputControl,
  Input: LoongArkPinInputInput,
  Label: LoongArkPinInputLabel,
  HiddenInput: LoongArkPinInputHiddenInput,
};
