// packages/svelte/src/components/QuestionnaireTree.svelte
<script lang="ts">
  import type { LoongArkQuestionnaireRenderers } from "./questionnaire-custom.types";
  import type { QuestionnaireRenderNode } from "@loongark/kit";
  let {
    node,
    renderers,
  }: {
    node: QuestionnaireRenderNode;
    renderers: LoongArkQuestionnaireRenderers;
  } = $props();
</script>

{#snippet tree(current: QuestionnaireRenderNode)}
  {#if current.kind === "text"}{current.text}
  {:else if current.kind === "html"}<div data-part="advanced-answer">
      {@html current.html}
    </div>
  {:else if current.kind === "custom"}{@render renderers[
      current.context.question.customKind!
    ](current.context)}
  {:else if current.tag === "input"}<input {...current.attrs} />
  {:else}<svelte:element this={current.tag} {...current.attrs}
      >{#each current.children as child (child.key)}{@render tree(
          child,
        )}{/each}</svelte:element
    >{/if}
{/snippet}
{@render tree(node)}

// packages/react/src/components/questionnaire-tree.tsx
import { createElement, type ReactNode } from "react";
import type {
  QuestionnaireCustomContext,
  QuestionnaireRenderNode,
} from "@loongark/kit";
export type LoongArkQuestionnaireRenderers = Readonly<
  Record<string, (context: QuestionnaireCustomContext) => ReactNode>
>;
export function QuestionnaireTree({
  node,
  renderers,
}: {
  node: QuestionnaireRenderNode;
  renderers: LoongArkQuestionnaireRenderers;
}): ReactNode {
  if (node.kind === "text") return node.text;
  if (node.kind === "html")
    return (
      <div
        data-part="advanced-answer"
        dangerouslySetInnerHTML={{ __html: node.html }}
      />
    );
  if (node.kind === "custom")
    return renderers[node.context.question.customKind!](node.context);
  const attrs = Object.fromEntries(
    Object.entries(node.attrs).map(([key, value]) => [
      key === "tabindex" ? "tabIndex" : key,
      value,
    ]),
  );
  return createElement(
    node.tag,
    attrs,
    ...node.children.map((child) => (
      <QuestionnaireTree key={child.key} node={child} renderers={renderers} />
    )),
  );
}
