// packages/solid/src/components/steps.tsx
/**
 * Steps component - Solid wrapper.
 * Uses Ark UI Steps with data attributes for styling.
 */
import { type Component, type JSX, mergeProps, splitProps } from "solid-js";
import {
  Steps as ArkSteps,
  type StepsRootProps as ArkStepsRootProps,
  type StepsListProps as ArkStepsListProps,
  type StepsItemProps as ArkStepsItemProps,
  type StepsIndicatorProps as ArkStepsIndicatorProps,
  type StepsSeparatorProps as ArkStepsSeparatorProps,
  type StepsTriggerProps as ArkStepsTriggerProps,
  type StepsContentProps as ArkStepsContentProps,
  type StepsCompletedContentProps as ArkStepsCompletedContentProps,
  type StepsProgressProps as ArkStepsProgressProps,
  type StepsNextTriggerProps as ArkStepsNextTriggerProps,
  type StepsPrevTriggerProps as ArkStepsPrevTriggerProps,
} from "@ark-ui/solid/steps";
import type { StepsOrientation, StepsSize } from "@loongark/primitives";

export interface LoongArkStepsRootProps extends Omit<
  ArkStepsRootProps,
  "asChild"
> {
  size?: StepsSize;
  orientation?: StepsOrientation;
  children?: JSX.Element;
}

export const LoongArkStepsRoot: Component<LoongArkStepsRootProps> = (props) => {
  const merged = mergeProps(
    { size: "md" as StepsSize, orientation: "horizontal" as StepsOrientation },
    props,
  );
  const [local, others] = splitProps(merged, [
    "children",
    "size",
    "orientation",
  ]);

  return (
    <ArkSteps.Root
      {...others}
      orientation={local.orientation}
      data-scope="steps"
      data-part="root"
      data-size={local.size}
      data-orientation={local.orientation}
    >
      {local.children}
    </ArkSteps.Root>
  );
};

export interface LoongArkStepsListProps extends Omit<
  ArkStepsListProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsList: Component<LoongArkStepsListProps> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.List {...others} data-scope="steps" data-part="list">
      {local.children}
    </ArkSteps.List>
  );
};

export interface LoongArkStepsItemProps extends Omit<
  ArkStepsItemProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsItem: Component<LoongArkStepsItemProps> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.Item
      role="presentation"
      // Ark preserves undefined overrides; null clears state on this presentational container.
      aria-current={null as unknown as LoongArkStepsItemProps["aria-current"]}
      {...others}
      data-scope="steps"
      data-part="item"
    >
      {local.children}
    </ArkSteps.Item>
  );
};

export interface LoongArkStepsIndicatorProps extends Omit<
  ArkStepsIndicatorProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsIndicator: Component<LoongArkStepsIndicatorProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.Indicator {...others} data-scope="steps" data-part="indicator">
      {local.children}
    </ArkSteps.Indicator>
  );
};

export interface LoongArkStepsSeparatorProps extends Omit<
  ArkStepsSeparatorProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsSeparator: Component<LoongArkStepsSeparatorProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.Separator {...others} data-scope="steps" data-part="separator">
      {local.children}
    </ArkSteps.Separator>
  );
};

export interface LoongArkStepsTriggerProps extends Omit<
  ArkStepsTriggerProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsTrigger: Component<LoongArkStepsTriggerProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.Trigger {...others} data-scope="steps" data-part="trigger">
      {local.children}
    </ArkSteps.Trigger>
  );
};

export interface LoongArkStepsContentProps extends Omit<
  ArkStepsContentProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsContent: Component<LoongArkStepsContentProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.Content {...others} data-scope="steps" data-part="content">
      {local.children}
    </ArkSteps.Content>
  );
};

export interface LoongArkStepsCompletedContentProps extends Omit<
  ArkStepsCompletedContentProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsCompletedContent: Component<
  LoongArkStepsCompletedContentProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.CompletedContent
      {...others}
      data-scope="steps"
      data-part="completed-content"
    >
      {local.children}
    </ArkSteps.CompletedContent>
  );
};

export interface LoongArkStepsProgressProps extends Omit<
  ArkStepsProgressProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsProgress: Component<LoongArkStepsProgressProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.Progress {...others} data-scope="steps" data-part="progress">
      {local.children}
    </ArkSteps.Progress>
  );
};

export interface LoongArkStepsNextTriggerProps extends Omit<
  ArkStepsNextTriggerProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsNextTrigger: Component<
  LoongArkStepsNextTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.NextTrigger
      {...others}
      data-scope="steps"
      data-part="next-trigger"
    >
      {local.children}
    </ArkSteps.NextTrigger>
  );
};

export interface LoongArkStepsPrevTriggerProps extends Omit<
  ArkStepsPrevTriggerProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkStepsPrevTrigger: Component<
  LoongArkStepsPrevTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSteps.PrevTrigger
      {...others}
      data-scope="steps"
      data-part="prev-trigger"
    >
      {local.children}
    </ArkSteps.PrevTrigger>
  );
};

// packages/react/src/components/steps.tsx
/**
 * Steps component - React wrapper.
 * Uses Ark UI Steps with data attributes for styling.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Steps } from "@ark-ui/react/steps";
import type { StepsOrientation, StepsSize } from "@loongark/primitives";

type ArkStepsRootProps = ComponentPropsWithoutRef<typeof Steps.Root>;
type ArkStepsListProps = ComponentPropsWithoutRef<typeof Steps.List>;
type ArkStepsItemProps = ComponentPropsWithoutRef<typeof Steps.Item>;
type ArkStepsIndicatorProps = ComponentPropsWithoutRef<typeof Steps.Indicator>;
type ArkStepsSeparatorProps = ComponentPropsWithoutRef<typeof Steps.Separator>;
type ArkStepsTriggerProps = ComponentPropsWithoutRef<typeof Steps.Trigger>;
type ArkStepsContentProps = ComponentPropsWithoutRef<typeof Steps.Content>;
type ArkStepsCompletedContentProps = ComponentPropsWithoutRef<
  typeof Steps.CompletedContent
>;
type ArkStepsProgressProps = ComponentPropsWithoutRef<typeof Steps.Progress>;
type ArkStepsNextTriggerProps = ComponentPropsWithoutRef<
  typeof Steps.NextTrigger
>;
type ArkStepsPrevTriggerProps = ComponentPropsWithoutRef<
  typeof Steps.PrevTrigger
>;

export interface LoongArkStepsRootProps extends Omit<
  ArkStepsRootProps,
  "asChild"
> {
  size?: StepsSize;
  orientation?: StepsOrientation;
  children?: ReactNode;
}

export interface LoongArkStepsListProps extends Omit<
  ArkStepsListProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsItemProps extends Omit<
  ArkStepsItemProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsIndicatorProps extends Omit<
  ArkStepsIndicatorProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsSeparatorProps extends Omit<
  ArkStepsSeparatorProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsTriggerProps extends Omit<
  ArkStepsTriggerProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsContentProps extends Omit<
  ArkStepsContentProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsCompletedContentProps extends Omit<
  ArkStepsCompletedContentProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsProgressProps extends Omit<
  ArkStepsProgressProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsNextTriggerProps extends Omit<
  ArkStepsNextTriggerProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkStepsPrevTriggerProps extends Omit<
  ArkStepsPrevTriggerProps,
  "asChild"
> {
  children?: ReactNode;
}

export const LoongArkStepsRoot = forwardRef<
  HTMLDivElement,
  LoongArkStepsRootProps
>(({ children, size = "md", orientation = "horizontal", ...props }, ref) => {
  return (
    <Steps.Root
      {...props}
      ref={ref}
      orientation={orientation}
      data-scope="steps"
      data-part="root"
      data-size={size}
      data-orientation={orientation}
    >
      {children}
    </Steps.Root>
  );
});

LoongArkStepsRoot.displayName = "LoongArkStepsRoot";

export const LoongArkStepsList = forwardRef<
  HTMLDivElement,
  LoongArkStepsListProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.List {...props} ref={ref} data-scope="steps" data-part="list">
      {children}
    </Steps.List>
  );
});

LoongArkStepsList.displayName = "LoongArkStepsList";

export const LoongArkStepsItem = forwardRef<
  HTMLDivElement,
  LoongArkStepsItemProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.Item
      role="presentation"
      // Ark preserves undefined overrides; null clears state on this presentational container.
      aria-current={null as unknown as LoongArkStepsItemProps["aria-current"]}
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="item"
    >
      {children}
    </Steps.Item>
  );
});

LoongArkStepsItem.displayName = "LoongArkStepsItem";

export const LoongArkStepsIndicator = forwardRef<
  HTMLDivElement,
  LoongArkStepsIndicatorProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.Indicator
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="indicator"
    >
      {children}
    </Steps.Indicator>
  );
});

LoongArkStepsIndicator.displayName = "LoongArkStepsIndicator";

export const LoongArkStepsSeparator = forwardRef<
  HTMLDivElement,
  LoongArkStepsSeparatorProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.Separator
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="separator"
    >
      {children}
    </Steps.Separator>
  );
});

LoongArkStepsSeparator.displayName = "LoongArkStepsSeparator";

export const LoongArkStepsTrigger = forwardRef<
  HTMLButtonElement,
  LoongArkStepsTriggerProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.Trigger {...props} ref={ref} data-scope="steps" data-part="trigger">
      {children}
    </Steps.Trigger>
  );
});

LoongArkStepsTrigger.displayName = "LoongArkStepsTrigger";

export const LoongArkStepsContent = forwardRef<
  HTMLDivElement,
  LoongArkStepsContentProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.Content {...props} ref={ref} data-scope="steps" data-part="content">
      {children}
    </Steps.Content>
  );
});

LoongArkStepsContent.displayName = "LoongArkStepsContent";

export const LoongArkStepsCompletedContent = forwardRef<
  HTMLDivElement,
  LoongArkStepsCompletedContentProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.CompletedContent
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="completed-content"
    >
      {children}
    </Steps.CompletedContent>
  );
});

LoongArkStepsCompletedContent.displayName = "LoongArkStepsCompletedContent";

export const LoongArkStepsProgress = forwardRef<
  HTMLDivElement,
  LoongArkStepsProgressProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.Progress
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="progress"
    >
      {children}
    </Steps.Progress>
  );
});

LoongArkStepsProgress.displayName = "LoongArkStepsProgress";

export const LoongArkStepsNextTrigger = forwardRef<
  HTMLButtonElement,
  LoongArkStepsNextTriggerProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.NextTrigger
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="next-trigger"
    >
      {children}
    </Steps.NextTrigger>
  );
});

LoongArkStepsNextTrigger.displayName = "LoongArkStepsNextTrigger";

export const LoongArkStepsPrevTrigger = forwardRef<
  HTMLButtonElement,
  LoongArkStepsPrevTriggerProps
>(({ children, ...props }, ref) => {
  return (
    <Steps.PrevTrigger
      {...props}
      ref={ref}
      data-scope="steps"
      data-part="prev-trigger"
    >
      {children}
    </Steps.PrevTrigger>
  );
});

LoongArkStepsPrevTrigger.displayName = "LoongArkStepsPrevTrigger";
