// packages/solid/src/components/switch.ts
import { useFieldContext } from "@ark-ui/solid/field";
import { nativeSelectionFieldDescription } from "@loongark/kit";
import { nativeSelectionRef } from "../native-selection";
import {
  useSwitchContext,
  type SwitchHiddenInputProps,
} from "@ark-ui/solid/switch";
import type { JSX } from "solid-js";
import { Switch as ArkSwitch } from "@ark-ui/solid/switch";
import { ark } from "@ark-ui/solid";
import type { SwitchPrimitiveProps } from "@loongark/primitives";
import { mergeProps, splitProps, type Component } from "solid-js";
import { boolAttr } from "../utils";

export type SwitchSize = NonNullable<SwitchPrimitiveProps["size"]>;

export interface LoongArkSwitchProps
  extends
    Partial<SwitchPrimitiveProps>,
    Omit<JSX.HTMLAttributes<HTMLElement>, "ref"> {
  children?: JSX.Element;
  disabled?: boolean;
  name?: string;
  form?: string;
  value?: string;
  readOnly?: boolean;
  required?: boolean;
  invalid?: boolean;
  checked?: boolean;
  defaultChecked?: boolean;
  onCheckedChange?: (details: { checked: boolean }) => void;
}

const defaults: Required<Pick<LoongArkSwitchProps, "size">> = {
  size: "md",
};

export const LoongArkSwitchRoot: Component<LoongArkSwitchProps> = (props) => {
  const merged = mergeProps(defaults, props);
  const [local, rest] = splitProps(merged, ["size"]);
  return ArkSwitch.Root(
    mergeProps(rest, {
      "data-scope": "switch",
      "data-part": "root",
      get "data-size"() {
        return local.size;
      },
      get "data-disabled"() {
        return boolAttr(merged.disabled);
      },
    }),
  );
};

export const LoongArkSwitchControl: Component<LoongArkSwitchProps> = (
  props,
) => {
  const merged = mergeProps(defaults, props);
  const [local, rest] = splitProps(merged, ["size", "disabled"]);
  return ArkSwitch.Control(
    mergeProps(rest, {
      get disabled() {
        return local.disabled;
      },
      "data-scope": "switch",
      "data-part": "control",
      get "data-size"() {
        return local.size;
      },
      get "data-disabled"() {
        return boolAttr(local.disabled);
      },
    }),
  );
};

export const LoongArkSwitchThumb: Component<
  Partial<SwitchPrimitiveProps> & Omit<JSX.HTMLAttributes<HTMLElement>, "ref">
> = (props) => {
  const merged = mergeProps({ size: "md" as SwitchSize }, props);
  const [local, rest] = splitProps(merged, ["size"]);
  return ArkSwitch.Thumb(
    mergeProps(rest, {
      "data-scope": "switch",
      "data-part": "thumb",
      get "data-size"() {
        return local.size;
      },
    }),
  );
};

export const LoongArkSwitchLabel: Component<{
  disabled?: boolean;
  children?: JSX.Element;
}> = (props) => {
  const merged = mergeProps({ disabled: false }, props);
  const [local, rest] = splitProps(merged, ["disabled"]);
  return ArkSwitch.Label(
    mergeProps(rest, {
      "data-scope": "switch",
      "data-part": "label",
      get "data-disabled"() {
        return boolAttr(local.disabled);
      },
    }),
  );
};

export const LoongArkSwitchHiddenInput: Component<SwitchHiddenInputProps> = (
  props,
) => {
  const field = useFieldContext();
  const api = useSwitchContext();
  const ref = nativeSelectionRef(() => ({ checked: api().checked }), props.ref);
  return ArkSwitch.HiddenInput(
    mergeProps(props, {
      ref,
      get "aria-describedby"() {
        return nativeSelectionFieldDescription(
          props["aria-describedby"],
          field?.(),
          api().getHiddenInputProps()["aria-invalid"],
        );
      },
    }),
  );
};
export const LoongArkSwitch = {
  Root: LoongArkSwitchRoot,
  Control: LoongArkSwitchControl,
  Thumb: LoongArkSwitchThumb,
  Label: LoongArkSwitchLabel,
  HiddenInput: LoongArkSwitchHiddenInput,
};

// packages/react/src/components/switch.tsx
import { useFieldContext } from "@ark-ui/react/field";
import { nativeSelectionFieldDescription } from "@loongark/kit";
import type {
  HTMLAttributes,
  InputHTMLAttributes,
  TextareaHTMLAttributes,
  ButtonHTMLAttributes,
} from "react";
import { nativeSelectionProps } from "@loongark/kit";
import { dataProps } from "../data-props";
import { useNativeSelection } from "../native-selection";
import {
  useSwitchContext,
  type SwitchHiddenInputProps,
} from "@ark-ui/react/switch";
import { Switch as ArkSwitch } from "@ark-ui/react/switch";
import type { SwitchPrimitiveProps } from "@loongark/primitives";
import { forwardRef, createElement } from "react";
import type { ReactNode } from "react";

export type SwitchSize = NonNullable<SwitchPrimitiveProps["size"]>;

type ArkSwitchRootProps = {
  onCheckedChange?: (details: { checked: boolean }) => void;
};

export interface LoongArkSwitchProps
  extends Partial<SwitchPrimitiveProps>, HTMLAttributes<HTMLElement> {
  children?: ReactNode;
  disabled?: boolean;
  name?: string;
  form?: string;
  value?: string;
  readOnly?: boolean;
  required?: boolean;
  invalid?: boolean;
  checked?: boolean;
  defaultChecked?: boolean;
  onCheckedChange?: ArkSwitchRootProps["onCheckedChange"];
}

export const LoongArkSwitchRoot = forwardRef<
  HTMLLabelElement,
  LoongArkSwitchProps
>(({ children, size = "md", disabled, onCheckedChange, ...rest }, ref) =>
  createElement(
    ArkSwitch.Root,
    dataProps(
      nativeSelectionProps({
        ...rest,
        onCheckedChange,
        disabled,
        ref,
        "data-scope": "switch",
        "data-part": "root",
        "data-size": size,
        "data-disabled": disabled ? "true" : undefined,
      }),
    ),
    children,
  ),
);

LoongArkSwitchRoot.displayName = "LoongArkSwitchRoot";

export const LoongArkSwitchControl = forwardRef<
  HTMLButtonElement,
  LoongArkSwitchProps
>(({ size = "md", disabled, ...rest }, ref) =>
  createElement(
    ArkSwitch.Control,
    dataProps({
      ...rest,
      disabled,
      ref,
      "data-scope": "switch",
      "data-part": "control",
      "data-size": size,
      "data-disabled": disabled ? "true" : undefined,
    }),
  ),
);

LoongArkSwitchControl.displayName = "LoongArkSwitchControl";

export const LoongArkSwitchThumb = forwardRef<
  HTMLSpanElement,
  Partial<SwitchPrimitiveProps>
>(({ size = "md", ...rest }, ref) =>
  createElement(
    ArkSwitch.Thumb,
    dataProps({
      ...rest,
      ref,
      "data-scope": "switch",
      "data-part": "thumb",
      "data-size": size,
    }),
  ),
);

LoongArkSwitchThumb.displayName = "LoongArkSwitchThumb";

export const LoongArkSwitchLabel = ({
  children,
  disabled,
  ...rest
}: {
  children?: ReactNode;
  disabled?: boolean;
}) =>
  createElement(
    ArkSwitch.Label,
    dataProps({
      ...rest,
      "data-scope": "switch",
      "data-part": "label",
      "data-disabled": disabled ? "true" : undefined,
    }),
    children,
  );

export const LoongArkSwitchHiddenInput = forwardRef<
  HTMLInputElement,
  SwitchHiddenInputProps
>((props, ref) => {
  const field = useFieldContext();
  const api = useSwitchContext();
  const input = useNativeSelection(api, "checkbox", ref);
  return createElement(ArkSwitch.HiddenInput, {
    ...props,
    ref: input,
    "aria-describedby": nativeSelectionFieldDescription(
      props["aria-describedby"],
      field,
      api.getHiddenInputProps()["aria-invalid"],
    ),
  });
});
LoongArkSwitchHiddenInput.displayName = "LoongArkSwitchHiddenInput";

export const LoongArkSwitch = {
  Root: LoongArkSwitchRoot,
  Control: LoongArkSwitchControl,
  Thumb: LoongArkSwitchThumb,
  Label: LoongArkSwitchLabel,
  HiddenInput: LoongArkSwitchHiddenInput,
};
