// packages/solid/src/components/toggle.tsx
/**
 * Toggle component - Solid wrapper.
 * Based on Ark UI Toggle.
 */
import { type Component, type JSX, mergeProps } from "solid-js";
import {
  Toggle as ArkToggle,
  type ToggleRootProps as ArkToggleRootProps,
  type ToggleIndicatorProps as ArkToggleIndicatorProps,
} from "@ark-ui/solid/toggle";
import type { ToggleSize } from "@loongark/primitives";

export interface LoongArkToggleRootProps extends Omit<
  ArkToggleRootProps,
  "asChild"
> {
  size?: ToggleSize;
  children?: JSX.Element;
}

export const LoongArkToggleRoot: Component<LoongArkToggleRootProps> = (
  props,
) => {
  const merged = mergeProps({ size: "md" as ToggleSize }, props);

  return (
    <ArkToggle.Root
      {...props}
      data-scope="toggle"
      data-part="root"
      data-size={merged.size}
    >
      {props.children}
    </ArkToggle.Root>
  );
};

export const LoongArkToggleIndicator: Component<
  ArkToggleIndicatorProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkToggle.Indicator {...props} data-scope="toggle" data-part="indicator">
      {props.children}
    </ArkToggle.Indicator>
  );
};

// packages/react/src/components/toggle.tsx
/**
 * Toggle component - React wrapper.
 * Injects data-scope/data-part and size mapping.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Toggle } from "@ark-ui/react/toggle";
import type { ToggleSize } from "@loongark/primitives";

type ArkToggleRootProps = ComponentPropsWithoutRef<typeof Toggle.Root>;
type ArkToggleIndicatorProps = ComponentPropsWithoutRef<typeof Toggle.Indicator>;

export interface LoongArkToggleRootProps
  extends Omit<ArkToggleRootProps, "asChild"> {
  size?: ToggleSize;
  children?: ReactNode;
}

export interface LoongArkToggleIndicatorProps
  extends Omit<ArkToggleIndicatorProps, "asChild"> {
  children?: ReactNode;
}

export const LoongArkToggleRoot = forwardRef<
  HTMLButtonElement,
  LoongArkToggleRootProps
>(({ children, size = "md", ...props }, ref) => {
  return (
    <Toggle.Root
      {...props}
      ref={ref}
      data-scope="toggle"
      data-part="root"
      data-size={size}
    >
      {children}
    </Toggle.Root>
  );
});

LoongArkToggleRoot.displayName = "LoongArkToggleRoot";

export const LoongArkToggleIndicator = forwardRef<
  HTMLDivElement,
  LoongArkToggleIndicatorProps
>(({ children, ...props }, ref) => {
  return (
    <Toggle.Indicator
      {...props}
      ref={ref}
      data-scope="toggle"
      data-part="indicator"
    >
      {children}
    </Toggle.Indicator>
  );
});

LoongArkToggleIndicator.displayName = "LoongArkToggleIndicator";
