// packages/solid/src/components/use-toc.ts
import { createUniqueId, createMemo } from "solid-js";
import { useMachine, normalizeProps } from "@zag-js/solid";
import { useEnvironmentContext } from "@ark-ui/solid/environment";
import { useLocaleContext } from "@ark-ui/solid/locale";
import type { UseTocProps, UseTocReturn } from "@ark-ui/solid/toc";
import { createTocMachine, connectToc, definedTocProps } from "@loongark/kit";
export const useToc = (props?: UseTocProps): UseTocReturn => {
  const id = createUniqueId(),
    env = useEnvironmentContext(),
    locale = useLocaleContext();
  const machineProps = createMemo(() => ({
    id,
    dir: locale().dir,
    getRootNode: env().getRootNode,
    scrollBehavior: "auto" as const,
    items: [],
    ...definedTocProps(props ?? {}),
  }));
  const service = useMachine(
    createTocMachine(() => props?.onActiveChange),
    machineProps,
  );
  return createMemo(() => connectToc(service, normalizeProps));
};

// packages/react/src/components/use-toc.ts
import { useId, useRef } from "react";
import { useMachine, normalizeProps } from "@zag-js/react";
import { useEnvironmentContext } from "@ark-ui/react/environment";
import { useLocaleContext } from "@ark-ui/react/locale";
import type { UseTocProps, UseTocReturn } from "@ark-ui/react/toc";
import { createTocMachine, connectToc, definedTocProps } from "@loongark/kit";
export const useToc = (props: UseTocProps): UseTocReturn => {
  const id = useId(),
    env = useEnvironmentContext(),
    locale = useLocaleContext();
  const callback = useRef(props.onActiveChange);
  callback.current = props.onActiveChange;
  const service = useMachine(
    createTocMachine(() => callback.current),
    {
      id,
      dir: locale.dir,
      getRootNode: env.getRootNode,
      scrollBehavior: "auto",
      ...definedTocProps(props ?? {}),
    },
  );
  return connectToc(service, normalizeProps);
};
