// packages/react/src/components/checkbox.tsx
import { useFieldContext } from "@ark-ui/react/field";
import { nativeSelectionFieldDescription } from "@loongark/kit";
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
import React, { forwardRef } from "react";
import { useNativeSelection } from "../native-selection";
import { useCheckboxContext } from "@ark-ui/react/checkbox";
import { Checkbox } from "@ark-ui/react/checkbox";
import type { CheckboxSize } from "@loongark/primitives";
import type {
  CheckboxRootProps as RootProps,
  CheckboxControlProps as ControlProps,
  CheckboxLabelProps as LabelProps,
  CheckboxIndicatorProps as IndicatorProps,
  CheckboxHiddenInputProps as HiddenInputProps,
} from "@ark-ui/react/checkbox";

// ========== Props 接口 ==========
export interface LoongArkCheckboxRootProps extends Omit<RootProps, "asChild"> {
  size?: CheckboxSize;
}

export interface LoongArkCheckboxControlProps extends Omit<
  ControlProps,
  "asChild"
> {
  size?: CheckboxSize;
}

export interface LoongArkCheckboxLabelProps extends Omit<
  LabelProps,
  "asChild"
> {}

export interface LoongArkCheckboxIndicatorProps extends Omit<
  IndicatorProps,
  "asChild"
> {}

export interface LoongArkCheckboxHiddenInputProps extends Omit<
  HiddenInputProps,
  "asChild"
> {}

// ========== 组件实现 ==========

export const LoongArkCheckboxRoot = forwardRef<
  HTMLLabelElement,
  LoongArkCheckboxRootProps
>(({ size = "md", ...props }, ref) => {
  return (
    <Checkbox.Root
      ref={ref}
      {...props}
      data-scope="checkbox"
      data-part="root"
      data-size={size}
    />
  );
});

LoongArkCheckboxRoot.displayName = "LoongArkCheckboxRoot";

export const LoongArkCheckboxControl = forwardRef<
  HTMLDivElement,
  LoongArkCheckboxControlProps
>(({ size = "md", ...props }, ref) => {
  return (
    <Checkbox.Control
      ref={ref}
      {...props}
      data-scope="checkbox"
      data-part="control"
      data-size={size}
    />
  );
});

LoongArkCheckboxControl.displayName = "LoongArkCheckboxControl";

export const LoongArkCheckboxLabel = forwardRef<
  HTMLSpanElement,
  LoongArkCheckboxLabelProps
>((props, ref) => {
  return (
    <Checkbox.Label
      ref={ref}
      {...props}
      data-scope="checkbox"
      data-part="label"
    />
  );
});

LoongArkCheckboxLabel.displayName = "LoongArkCheckboxLabel";

export const LoongArkCheckboxIndicator = forwardRef<
  HTMLDivElement,
  LoongArkCheckboxIndicatorProps
>(({ children, ...props }, ref) => {
  return (
    <Checkbox.Indicator
      ref={ref}
      {...props}
      data-scope="checkbox"
      data-part="indicator"
    >
      {children ?? (
        <LoongArkIcon
          icon={props.indeterminate ? controlIcons.minus : controlIcons.check}
          size="sm"
        />
      )}
    </Checkbox.Indicator>
  );
});

LoongArkCheckboxIndicator.displayName = "LoongArkCheckboxIndicator";

export const LoongArkCheckboxHiddenInput = forwardRef<
  HTMLInputElement,
  LoongArkCheckboxHiddenInputProps
>((props, ref) => {
  const field = useFieldContext();
  const api = useCheckboxContext();
  const input = useNativeSelection(api, "checkbox", ref);
  return (
    <Checkbox.HiddenInput
      ref={input}
      {...props}
      aria-describedby={nativeSelectionFieldDescription(
        props["aria-describedby"],
        field,
        api.getHiddenInputProps()["aria-invalid"],
      )}
      data-scope="checkbox"
      data-part="hidden-input"
    />
  );
});

LoongArkCheckboxHiddenInput.displayName = "LoongArkCheckboxHiddenInput";

// packages/solid/src/components/checkbox.tsx
import { useFieldContext } from "@ark-ui/solid/field";
import { nativeSelectionFieldDescription } from "@loongark/kit";
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
import type { JSX } from "solid-js";
import { type Component, mergeProps, splitProps } from "solid-js";
import { nativeSelectionRef } from "../native-selection";
import {
  useCheckboxContext,
  type CheckboxHiddenInputProps,
} from "@ark-ui/solid/checkbox";
import { Checkbox } from "@ark-ui/solid/checkbox";
import type { CheckboxSize } from "@loongark/primitives";
import type { CheckboxRootProps as RootProps } from "@ark-ui/solid/checkbox";

// ========== Props 接口 ==========
export interface LoongArkCheckboxRootProps extends RootProps {
  size?: CheckboxSize;
}

export interface LoongArkCheckboxControlProps {
  size?: CheckboxSize;
  children?: JSX.Element;
}

export interface LoongArkCheckboxLabelProps {
  children?: JSX.Element;
}

export interface LoongArkCheckboxIndicatorProps {
  indeterminate?: boolean;
  children?: JSX.Element;
}

// ========== 组件实现 ==========

export const LoongArkCheckboxRoot: Component<LoongArkCheckboxRootProps> = (
  props,
) => {
  const merged = mergeProps({ size: "md" as CheckboxSize }, props);
  const [local, others] = splitProps(merged, ["size"]);

  return (
    <Checkbox.Root
      {...others}
      data-scope="checkbox"
      data-part="root"
      data-size={local.size}
    />
  );
};

export const LoongArkCheckboxControl: Component<
  LoongArkCheckboxControlProps
> = (props) => {
  const merged = mergeProps({ size: "md" as CheckboxSize }, props);
  const [local, others] = splitProps(merged, ["size"]);

  return (
    <Checkbox.Control
      {...others}
      data-scope="checkbox"
      data-part="control"
      data-size={local.size}
    />
  );
};

export const LoongArkCheckboxLabel: Component<LoongArkCheckboxLabelProps> = (
  props,
) => {
  return <Checkbox.Label {...props} data-scope="checkbox" data-part="label" />;
};

export const LoongArkCheckboxIndicator: Component<
  LoongArkCheckboxIndicatorProps
> = (props) => {
  return (
    <Checkbox.Indicator {...props} data-scope="checkbox" data-part="indicator">
      {props.children ?? (
        <LoongArkIcon
          icon={props.indeterminate ? controlIcons.minus : controlIcons.check}
          size="sm"
        />
      )}
    </Checkbox.Indicator>
  );
};

export const LoongArkCheckboxHiddenInput: Component<
  CheckboxHiddenInputProps
> = (props) => {
  const field = useFieldContext();
  const api = useCheckboxContext();
  const ref = nativeSelectionRef(
    () => ({
      checked: api().checked,
      indeterminate: api().indeterminate,
    }),
    props.ref,
  );
  return (
    <Checkbox.HiddenInput
      {...props}
      aria-describedby={nativeSelectionFieldDescription(
        props["aria-describedby"],
        field?.(),
        api().getHiddenInputProps()["aria-invalid"],
      )}
      ref={ref}
      data-scope="checkbox"
      data-part="hidden-input"
    />
  );
};
