// packages/react/src/components/combobox.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
/**
 * Combobox component - React wrapper.
 * Based on Ark UI Combobox, injects data-scope/data-part attributes.
 */
import React, {
  createContext,
  createElement,
  forwardRef,
  useContext,
  type FC,
  type ReactNode,
} from "react";
import {
  Combobox as ArkCombobox,
  type ComboboxRootProps as ArkComboboxRootProps,
  type ComboboxLabelProps as ArkComboboxLabelProps,
  type ComboboxControlProps as ArkComboboxControlProps,
  type ComboboxInputProps as ArkComboboxInputProps,
  type ComboboxTriggerProps as ArkComboboxTriggerProps,
  type ComboboxClearTriggerProps as ArkComboboxClearTriggerProps,
  type ComboboxPositionerProps as ArkComboboxPositionerProps,
  type ComboboxContentProps as ArkComboboxContentProps,
  type ComboboxListProps as ArkComboboxListProps,
  type ComboboxItemGroupProps as ArkComboboxItemGroupProps,
  type ComboboxItemGroupLabelProps as ArkComboboxItemGroupLabelProps,
  type ComboboxItemProps as ArkComboboxItemProps,
  type ComboboxItemTextProps as ArkComboboxItemTextProps,
  type ComboboxItemIndicatorProps as ArkComboboxItemIndicatorProps,
} from "@ark-ui/react/combobox";
import { Portal as ArkPortal } from "./portal";
import type { ComboboxSize } from "@loongark/primitives";

const SafePortal: FC<{ children?: ReactNode }> = ({ children }) =>
  createElement(ArkPortal, null, children);

const ComboboxContext = createContext<{ size: ComboboxSize }>({ size: "md" });

export interface LoongArkComboboxRootProps<T = object> extends Omit<
  ArkComboboxRootProps<T>,
  "asChild"
> {
  size?: ComboboxSize;
  children?: ReactNode;
}

export const LoongArkComboboxRoot = forwardRef<
  HTMLDivElement,
  LoongArkComboboxRootProps
>(({ size = "md", children, ...props }, ref) => {
  return (
    <ComboboxContext.Provider value={{ size }}>
      <ArkCombobox.Root
        {...props}
        ref={ref}
        data-scope="combobox"
        data-part="root"
        data-size={size}
      >
        {children}
      </ArkCombobox.Root>
    </ComboboxContext.Provider>
  );
}) as (<T>(
  props: LoongArkComboboxRootProps<T> &
    import("react").RefAttributes<HTMLDivElement>,
) => import("react").ReactElement | null) & { displayName?: string };

LoongArkComboboxRoot.displayName = "LoongArkComboboxRoot";

export const LoongArkComboboxLabel = forwardRef<
  HTMLLabelElement,
  ArkComboboxLabelProps
>((props, ref) => {
  return (
    <ArkCombobox.Label
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="label"
    />
  );
});

LoongArkComboboxLabel.displayName = "LoongArkComboboxLabel";

export const LoongArkComboboxControl = forwardRef<
  HTMLDivElement,
  ArkComboboxControlProps
>((props, ref) => {
  return (
    <ArkCombobox.Control
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="control"
    />
  );
});

LoongArkComboboxControl.displayName = "LoongArkComboboxControl";

export const LoongArkComboboxInput = forwardRef<
  HTMLInputElement,
  ArkComboboxInputProps
>((props, ref) => {
  return (
    <ArkCombobox.Input
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="input"
    />
  );
});

LoongArkComboboxInput.displayName = "LoongArkComboboxInput";

export const LoongArkComboboxTrigger = forwardRef<
  HTMLButtonElement,
  ArkComboboxTriggerProps
>((props, ref) => {
  return (
    <ArkCombobox.Trigger
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="trigger"
    >
      {props.children ?? (
        <LoongArkIcon icon={controlIcons.chevronDown} size="sm" />
      )}
    </ArkCombobox.Trigger>
  );
});

LoongArkComboboxTrigger.displayName = "LoongArkComboboxTrigger";

export const LoongArkComboboxClearTrigger = forwardRef<
  HTMLButtonElement,
  ArkComboboxClearTriggerProps
>((props, ref) => {
  return (
    <ArkCombobox.ClearTrigger
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="clear-trigger"
    />
  );
});

LoongArkComboboxClearTrigger.displayName = "LoongArkComboboxClearTrigger";

export const LoongArkComboboxPositioner = forwardRef<
  HTMLDivElement,
  ArkComboboxPositionerProps
>((props, ref) => {
  return (
    <SafePortal>
      <ArkCombobox.Positioner
        {...props}
        ref={ref}
        data-scope="combobox"
        data-part="positioner"
      />
    </SafePortal>
  );
});

LoongArkComboboxPositioner.displayName = "LoongArkComboboxPositioner";

export const LoongArkComboboxContent = forwardRef<
  HTMLDivElement,
  ArkComboboxContentProps
>((props, ref) => {
  const { size } = useContext(ComboboxContext);
  return (
    <ArkCombobox.Content
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="content"
      data-size={size}
    />
  );
});

LoongArkComboboxContent.displayName = "LoongArkComboboxContent";

export const LoongArkComboboxList = forwardRef<
  HTMLDivElement,
  ArkComboboxListProps
>((props, ref) => {
  return (
    <ArkCombobox.List
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="list"
    />
  );
});

LoongArkComboboxList.displayName = "LoongArkComboboxList";

export const LoongArkComboboxItemGroup = forwardRef<
  HTMLDivElement,
  ArkComboboxItemGroupProps
>((props, ref) => {
  return (
    <ArkCombobox.ItemGroup
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="item-group"
    />
  );
});

LoongArkComboboxItemGroup.displayName = "LoongArkComboboxItemGroup";

export const LoongArkComboboxItemGroupLabel = forwardRef<
  HTMLDivElement,
  ArkComboboxItemGroupLabelProps
>((props, ref) => {
  return (
    <ArkCombobox.ItemGroupLabel
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="item-group-label"
    />
  );
});

LoongArkComboboxItemGroupLabel.displayName = "LoongArkComboboxItemGroupLabel";

export const LoongArkComboboxItem = forwardRef<
  HTMLDivElement,
  ArkComboboxItemProps
>((props, ref) => {
  return (
    <ArkCombobox.Item
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="item"
    />
  );
});

LoongArkComboboxItem.displayName = "LoongArkComboboxItem";

export const LoongArkComboboxItemText = forwardRef<
  HTMLDivElement,
  ArkComboboxItemTextProps
>((props, ref) => {
  return (
    <ArkCombobox.ItemText
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="item-text"
    />
  );
});

LoongArkComboboxItemText.displayName = "LoongArkComboboxItemText";

export const LoongArkComboboxItemIndicator = forwardRef<
  HTMLDivElement,
  ArkComboboxItemIndicatorProps
>(({ children, ...props }, ref) => {
  return (
    <ArkCombobox.ItemIndicator
      {...props}
      ref={ref}
      data-scope="combobox"
      data-part="item-indicator"
    >
      {children || <LoongArkIcon icon={controlIcons.check} size="sm" />}
    </ArkCombobox.ItemIndicator>
  );
});

LoongArkComboboxItemIndicator.displayName = "LoongArkComboboxItemIndicator";

// packages/solid/src/components/combobox.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
/**
 * Combobox component - Solid wrapper.
 * Uses Ark UI Combobox with data attributes for styling.
 */
import {
  type Component,
  type JSX,
  createContext,
  mergeProps,
  useContext,
} from "solid-js";
import {
  Combobox as ArkCombobox,
  type ComboboxRootProps as ArkComboboxRootProps,
  type ComboboxLabelProps as ArkComboboxLabelProps,
  type ComboboxControlProps as ArkComboboxControlProps,
  type ComboboxInputProps as ArkComboboxInputProps,
  type ComboboxTriggerProps as ArkComboboxTriggerProps,
  type ComboboxClearTriggerProps as ArkComboboxClearTriggerProps,
  type ComboboxPositionerProps as ArkComboboxPositionerProps,
  type ComboboxContentProps as ArkComboboxContentProps,
  type ComboboxListProps as ArkComboboxListProps,
  type ComboboxItemGroupProps as ArkComboboxItemGroupProps,
  type ComboboxItemGroupLabelProps as ArkComboboxItemGroupLabelProps,
  type ComboboxItemProps as ArkComboboxItemProps,
  type ComboboxItemTextProps as ArkComboboxItemTextProps,
  type ComboboxItemIndicatorProps as ArkComboboxItemIndicatorProps,
} from "@ark-ui/solid/combobox";
import type { ComboboxSize } from "@loongark/primitives";

const ComboboxContext = createContext<{ size: ComboboxSize }>({ size: "md" });

export interface LoongArkComboboxRootProps<
  T extends object = object,
> extends Omit<ArkComboboxRootProps<T>, "asChild"> {
  size?: ComboboxSize;
  children?: JSX.Element;
}

export const LoongArkComboboxRoot = <T extends object>(
  props: LoongArkComboboxRootProps<T>,
): JSX.Element => {
  const merged = mergeProps({ size: "md" as ComboboxSize }, props);

  return (
    <ComboboxContext.Provider value={{ size: merged.size }}>
      <ArkCombobox.Root
        {...props}
        data-scope="combobox"
        data-part="root"
        data-size={merged.size}
      >
        {props.children}
      </ArkCombobox.Root>
    </ComboboxContext.Provider>
  );
};

export const LoongArkComboboxLabel: Component<
  ArkComboboxLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.Label {...props} data-scope="combobox" data-part="label">
      {props.children}
    </ArkCombobox.Label>
  );
};

export const LoongArkComboboxControl: Component<
  ArkComboboxControlProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.Control {...props} data-scope="combobox" data-part="control">
      {props.children}
    </ArkCombobox.Control>
  );
};

export const LoongArkComboboxInput: Component<ArkComboboxInputProps> = (
  props,
) => {
  return (
    <ArkCombobox.Input {...props} data-scope="combobox" data-part="input" />
  );
};

export const LoongArkComboboxTrigger: Component<
  ArkComboboxTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.Trigger {...props} data-scope="combobox" data-part="trigger">
      {props.children ?? (
        <LoongArkIcon icon={controlIcons.chevronDown} size="sm" />
      )}
    </ArkCombobox.Trigger>
  );
};

export const LoongArkComboboxClearTrigger: Component<
  ArkComboboxClearTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.ClearTrigger
      {...props}
      data-scope="combobox"
      data-part="clear-trigger"
    >
      {props.children}
    </ArkCombobox.ClearTrigger>
  );
};

export const LoongArkComboboxPositioner: Component<
  ArkComboboxPositionerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.Positioner
      {...props}
      data-scope="combobox"
      data-part="positioner"
    >
      {props.children}
    </ArkCombobox.Positioner>
  );
};

export const LoongArkComboboxContent: Component<
  ArkComboboxContentProps & { children?: JSX.Element }
> = (props) => {
  const { size } = useContext(ComboboxContext);
  return (
    <ArkCombobox.Content
      {...props}
      data-scope="combobox"
      data-part="content"
      data-size={size}
    >
      {props.children}
    </ArkCombobox.Content>
  );
};

export const LoongArkComboboxList: Component<
  ArkComboboxListProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.List {...props} data-scope="combobox" data-part="list">
      {props.children}
    </ArkCombobox.List>
  );
};

export const LoongArkComboboxItemGroup: Component<
  ArkComboboxItemGroupProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.ItemGroup
      {...props}
      data-scope="combobox"
      data-part="item-group"
    >
      {props.children}
    </ArkCombobox.ItemGroup>
  );
};

export const LoongArkComboboxItemGroupLabel: Component<
  ArkComboboxItemGroupLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.ItemGroupLabel
      {...props}
      data-scope="combobox"
      data-part="item-group-label"
    >
      {props.children}
    </ArkCombobox.ItemGroupLabel>
  );
};

export const LoongArkComboboxItem: Component<
  ArkComboboxItemProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.Item {...props} data-scope="combobox" data-part="item">
      {props.children}
    </ArkCombobox.Item>
  );
};

export const LoongArkComboboxItemText: Component<
  ArkComboboxItemTextProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.ItemText
      {...props}
      data-scope="combobox"
      data-part="item-text"
    >
      {props.children}
    </ArkCombobox.ItemText>
  );
};

export const LoongArkComboboxItemIndicator: Component<
  ArkComboboxItemIndicatorProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkCombobox.ItemIndicator
      {...props}
      data-scope="combobox"
      data-part="item-indicator"
    >
      {props.children ?? <LoongArkIcon icon={controlIcons.check} size="sm" />}
    </ArkCombobox.ItemIndicator>
  );
};
