// packages/react/src/components/date-picker.tsx
/**
 * Date Picker component - React wrapper.
 * Injects data-scope/data-part and size mapping.
 */
import React, {
  forwardRef,
  createContext,
  useContext,
  createElement,
  type ReactNode,
  type FC,
} from "react";
import {
  DatePicker,
  type DatePickerRootProps as ArkDatePickerRootProps,
  type DatePickerLabelProps as ArkDatePickerLabelProps,
  type DatePickerControlProps as ArkDatePickerControlProps,
  type DatePickerInputProps as ArkDatePickerInputProps,
  type DatePickerTriggerProps as ArkDatePickerTriggerProps,
  type DatePickerClearTriggerProps as ArkDatePickerClearTriggerProps,
  type DatePickerPositionerProps as ArkDatePickerPositionerProps,
  type DatePickerContentProps as ArkDatePickerContentProps,
  type DatePickerViewProps as ArkDatePickerViewProps,
  type DatePickerViewControlProps as ArkDatePickerViewControlProps,
  type DatePickerViewTriggerProps as ArkDatePickerViewTriggerProps,
  type DatePickerPrevTriggerProps as ArkDatePickerPrevTriggerProps,
  type DatePickerNextTriggerProps as ArkDatePickerNextTriggerProps,
  type DatePickerMonthSelectProps as ArkDatePickerMonthSelectProps,
  type DatePickerYearSelectProps as ArkDatePickerYearSelectProps,
  type DatePickerRangeTextProps as ArkDatePickerRangeTextProps,
  type DatePickerPresetTriggerProps as ArkDatePickerPresetTriggerProps,
  type DatePickerTableProps as ArkDatePickerTableProps,
  type DatePickerTableHeadProps as ArkDatePickerTableHeadProps,
  type DatePickerTableBodyProps as ArkDatePickerTableBodyProps,
  type DatePickerTableRowProps as ArkDatePickerTableRowProps,
  type DatePickerTableHeaderProps as ArkDatePickerTableHeaderProps,
  type DatePickerTableCellProps as ArkDatePickerTableCellProps,
  type DatePickerTableCellTriggerProps as ArkDatePickerTableCellTriggerProps,
} from "@ark-ui/react/date-picker";
import type { DatePickerSize } from "@loongark/primitives";
import { Portal as ArkPortal } from "./portal";

const SafePortal: FC<{ children?: ReactNode }> = ({ children }) =>
  createElement(ArkPortal, null, children);

const DatePickerSizeContext = createContext<{ size: DatePickerSize }>({
  size: "md",
});

export interface LoongArkDatePickerRootProps extends Omit<
  ArkDatePickerRootProps,
  "asChild"
> {
  size?: DatePickerSize;
  children?: ReactNode;
}

export const LoongArkDatePickerRoot = forwardRef<
  HTMLDivElement,
  LoongArkDatePickerRootProps
>(({ size = "md", children, ...props }, ref) => {
  return (
    <DatePickerSizeContext.Provider value={{ size }}>
      <DatePicker.Root
        {...props}
        ref={ref}
        data-scope="date-picker"
        data-part="root"
        data-size={size}
      >
        {children}
      </DatePicker.Root>
    </DatePickerSizeContext.Provider>
  );
});

LoongArkDatePickerRoot.displayName = "LoongArkDatePickerRoot";

export const LoongArkDatePickerLabel = forwardRef<
  HTMLLabelElement,
  ArkDatePickerLabelProps
>((props, ref) => {
  return (
    <DatePicker.Label
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="label"
    />
  );
});

LoongArkDatePickerLabel.displayName = "LoongArkDatePickerLabel";

export const LoongArkDatePickerControl = forwardRef<
  HTMLDivElement,
  ArkDatePickerControlProps
>((props, ref) => {
  return (
    <DatePicker.Control
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="control"
    />
  );
});

LoongArkDatePickerControl.displayName = "LoongArkDatePickerControl";

export const LoongArkDatePickerInput = forwardRef<
  HTMLInputElement,
  ArkDatePickerInputProps
>((props, ref) => {
  return (
    <DatePicker.Input
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="input"
    />
  );
});

LoongArkDatePickerInput.displayName = "LoongArkDatePickerInput";

export const LoongArkDatePickerTrigger = forwardRef<
  HTMLButtonElement,
  ArkDatePickerTriggerProps
>((props, ref) => {
  return (
    <DatePicker.Trigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="trigger"
    />
  );
});

LoongArkDatePickerTrigger.displayName = "LoongArkDatePickerTrigger";

export const LoongArkDatePickerClearTrigger = forwardRef<
  HTMLButtonElement,
  ArkDatePickerClearTriggerProps
>((props, ref) => {
  return (
    <DatePicker.ClearTrigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="clear-trigger"
    />
  );
});

LoongArkDatePickerClearTrigger.displayName = "LoongArkDatePickerClearTrigger";

export const LoongArkDatePickerPositioner = forwardRef<
  HTMLDivElement,
  ArkDatePickerPositionerProps
>((props, ref) => {
  return (
    <SafePortal>
      <DatePicker.Positioner
        {...props}
        ref={ref}
        data-scope="date-picker"
        data-part="positioner"
      />
    </SafePortal>
  );
});

LoongArkDatePickerPositioner.displayName = "LoongArkDatePickerPositioner";

export const LoongArkDatePickerContent = forwardRef<
  HTMLDivElement,
  ArkDatePickerContentProps
>((props, ref) => {
  const { size } = useContext(DatePickerSizeContext);
  return (
    <DatePicker.Content
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="content"
      data-size={size}
    />
  );
});

LoongArkDatePickerContent.displayName = "LoongArkDatePickerContent";

export const LoongArkDatePickerView = forwardRef<
  HTMLDivElement,
  ArkDatePickerViewProps
>((props, ref) => {
  return (
    <DatePicker.View
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="view"
    />
  );
});

LoongArkDatePickerView.displayName = "LoongArkDatePickerView";

export const LoongArkDatePickerViewControl = forwardRef<
  HTMLDivElement,
  ArkDatePickerViewControlProps
>((props, ref) => {
  return (
    <DatePicker.ViewControl
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="view-control"
    />
  );
});

LoongArkDatePickerViewControl.displayName = "LoongArkDatePickerViewControl";

export const LoongArkDatePickerViewTrigger = forwardRef<
  HTMLButtonElement,
  ArkDatePickerViewTriggerProps
>((props, ref) => {
  return (
    <DatePicker.ViewTrigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="view-trigger"
    />
  );
});

LoongArkDatePickerViewTrigger.displayName = "LoongArkDatePickerViewTrigger";

export const LoongArkDatePickerPrevTrigger = forwardRef<
  HTMLButtonElement,
  ArkDatePickerPrevTriggerProps
>((props, ref) => {
  return (
    <DatePicker.PrevTrigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="prev-trigger"
    />
  );
});

LoongArkDatePickerPrevTrigger.displayName = "LoongArkDatePickerPrevTrigger";

export const LoongArkDatePickerNextTrigger = forwardRef<
  HTMLButtonElement,
  ArkDatePickerNextTriggerProps
>((props, ref) => {
  return (
    <DatePicker.NextTrigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="next-trigger"
    />
  );
});

LoongArkDatePickerNextTrigger.displayName = "LoongArkDatePickerNextTrigger";

export const LoongArkDatePickerMonthSelect = forwardRef<
  HTMLSelectElement,
  ArkDatePickerMonthSelectProps
>((props, ref) => {
  return (
    <DatePicker.MonthSelect
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="month-select"
    />
  );
});

LoongArkDatePickerMonthSelect.displayName = "LoongArkDatePickerMonthSelect";

export const LoongArkDatePickerYearSelect = forwardRef<
  HTMLSelectElement,
  ArkDatePickerYearSelectProps
>((props, ref) => {
  return (
    <DatePicker.YearSelect
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="year-select"
    />
  );
});

LoongArkDatePickerYearSelect.displayName = "LoongArkDatePickerYearSelect";

export const LoongArkDatePickerRangeText = forwardRef<
  HTMLDivElement,
  ArkDatePickerRangeTextProps
>((props, ref) => {
  return (
    <DatePicker.RangeText
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="range-text"
    />
  );
});

LoongArkDatePickerRangeText.displayName = "LoongArkDatePickerRangeText";

export const LoongArkDatePickerPresetTrigger = forwardRef<
  HTMLButtonElement,
  ArkDatePickerPresetTriggerProps
>((props, ref) => {
  return (
    <DatePicker.PresetTrigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="preset-trigger"
    />
  );
});

LoongArkDatePickerPresetTrigger.displayName = "LoongArkDatePickerPresetTrigger";

export const LoongArkDatePickerTable = forwardRef<
  HTMLTableElement,
  ArkDatePickerTableProps
>((props, ref) => {
  return (
    <DatePicker.Table
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table"
    />
  );
});

LoongArkDatePickerTable.displayName = "LoongArkDatePickerTable";

export const LoongArkDatePickerTableHead = forwardRef<
  HTMLTableSectionElement,
  ArkDatePickerTableHeadProps
>((props, ref) => {
  return (
    <DatePicker.TableHead
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table-head"
    />
  );
});

LoongArkDatePickerTableHead.displayName = "LoongArkDatePickerTableHead";

export const LoongArkDatePickerTableBody = forwardRef<
  HTMLTableSectionElement,
  ArkDatePickerTableBodyProps
>((props, ref) => {
  return (
    <DatePicker.TableBody
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table-body"
    />
  );
});

LoongArkDatePickerTableBody.displayName = "LoongArkDatePickerTableBody";

export const LoongArkDatePickerTableRow = forwardRef<
  HTMLTableRowElement,
  ArkDatePickerTableRowProps
>((props, ref) => {
  return (
    <DatePicker.TableRow
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table-row"
    />
  );
});

LoongArkDatePickerTableRow.displayName = "LoongArkDatePickerTableRow";

export const LoongArkDatePickerTableHeader = forwardRef<
  HTMLTableCellElement,
  ArkDatePickerTableHeaderProps
>((props, ref) => {
  return (
    <DatePicker.TableHeader
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table-header"
    />
  );
});

LoongArkDatePickerTableHeader.displayName = "LoongArkDatePickerTableHeader";

export const LoongArkDatePickerTableCell = forwardRef<
  HTMLTableCellElement,
  ArkDatePickerTableCellProps
>((props, ref) => {
  return (
    <DatePicker.TableCell
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table-cell"
    />
  );
});

LoongArkDatePickerTableCell.displayName = "LoongArkDatePickerTableCell";

export const LoongArkDatePickerTableCellTrigger = forwardRef<
  HTMLDivElement,
  ArkDatePickerTableCellTriggerProps
>((props, ref) => {
  return (
    <DatePicker.TableCellTrigger
      {...props}
      ref={ref}
      data-scope="date-picker"
      data-part="table-cell-trigger"
    />
  );
});

LoongArkDatePickerTableCellTrigger.displayName =
  "LoongArkDatePickerTableCellTrigger";

// packages/solid/src/components/date-picker.tsx
/**
 * Date Picker component - Solid wrapper.
 * Injects data-scope/data-part and size mapping.
 */
import {
  type Component,
  type JSX,
  mergeProps,
  createContext,
  useContext,
} from "solid-js";
import {
  DatePicker as ArkDatePicker,
  type DatePickerRootProps as ArkDatePickerRootProps,
  type DatePickerLabelProps as ArkDatePickerLabelProps,
  type DatePickerControlProps as ArkDatePickerControlProps,
  type DatePickerInputProps as ArkDatePickerInputProps,
  type DatePickerTriggerProps as ArkDatePickerTriggerProps,
  type DatePickerClearTriggerProps as ArkDatePickerClearTriggerProps,
  type DatePickerPositionerProps as ArkDatePickerPositionerProps,
  type DatePickerContentProps as ArkDatePickerContentProps,
  type DatePickerViewProps as ArkDatePickerViewProps,
  type DatePickerViewControlProps as ArkDatePickerViewControlProps,
  type DatePickerViewTriggerProps as ArkDatePickerViewTriggerProps,
  type DatePickerPrevTriggerProps as ArkDatePickerPrevTriggerProps,
  type DatePickerNextTriggerProps as ArkDatePickerNextTriggerProps,
  type DatePickerMonthSelectProps as ArkDatePickerMonthSelectProps,
  type DatePickerYearSelectProps as ArkDatePickerYearSelectProps,
  type DatePickerRangeTextProps as ArkDatePickerRangeTextProps,
  type DatePickerPresetTriggerProps as ArkDatePickerPresetTriggerProps,
  type DatePickerTableProps as ArkDatePickerTableProps,
  type DatePickerTableHeadProps as ArkDatePickerTableHeadProps,
  type DatePickerTableBodyProps as ArkDatePickerTableBodyProps,
  type DatePickerTableRowProps as ArkDatePickerTableRowProps,
  type DatePickerTableHeaderProps as ArkDatePickerTableHeaderProps,
  type DatePickerTableCellProps as ArkDatePickerTableCellProps,
  type DatePickerTableCellTriggerProps as ArkDatePickerTableCellTriggerProps,
} from "@ark-ui/solid/date-picker";
import type { DatePickerSize } from "@loongark/primitives";

const DatePickerContext = createContext<{ size: DatePickerSize }>({
  size: "md",
});

export interface LoongArkDatePickerRootProps extends Omit<
  ArkDatePickerRootProps,
  "asChild"
> {
  size?: DatePickerSize;
  children?: JSX.Element;
}

export const LoongArkDatePickerRoot: Component<LoongArkDatePickerRootProps> = (
  props,
) => {
  const merged = mergeProps({ size: "md" as DatePickerSize }, props);
  return (
    <DatePickerContext.Provider value={{ size: merged.size }}>
      <ArkDatePicker.Root
        {...props}
        data-scope="date-picker"
        data-part="root"
        data-size={merged.size}
      >
        {props.children}
      </ArkDatePicker.Root>
    </DatePickerContext.Provider>
  );
};

export const LoongArkDatePickerLabel: Component<
  ArkDatePickerLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.Label {...props} data-scope="date-picker" data-part="label">
      {props.children}
    </ArkDatePicker.Label>
  );
};

export const LoongArkDatePickerControl: Component<
  ArkDatePickerControlProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.Control
      {...props}
      data-scope="date-picker"
      data-part="control"
    >
      {props.children}
    </ArkDatePicker.Control>
  );
};

export const LoongArkDatePickerInput: Component<
  ArkDatePickerInputProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.Input {...props} data-scope="date-picker" data-part="input">
      {props.children}
    </ArkDatePicker.Input>
  );
};

export const LoongArkDatePickerTrigger: Component<
  ArkDatePickerTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.Trigger
      {...props}
      data-scope="date-picker"
      data-part="trigger"
    >
      {props.children}
    </ArkDatePicker.Trigger>
  );
};

export const LoongArkDatePickerClearTrigger: Component<
  ArkDatePickerClearTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.ClearTrigger
      {...props}
      data-scope="date-picker"
      data-part="clear-trigger"
    >
      {props.children}
    </ArkDatePicker.ClearTrigger>
  );
};

export const LoongArkDatePickerPositioner: Component<
  ArkDatePickerPositionerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.Positioner
      {...props}
      data-scope="date-picker"
      data-part="positioner"
    >
      {props.children}
    </ArkDatePicker.Positioner>
  );
};

export const LoongArkDatePickerContent: Component<
  ArkDatePickerContentProps & { children?: JSX.Element }
> = (props) => {
  const { size } = useContext(DatePickerContext);
  return (
    <ArkDatePicker.Content
      {...props}
      data-scope="date-picker"
      data-part="content"
      data-size={size}
    >
      {props.children}
    </ArkDatePicker.Content>
  );
};

export const LoongArkDatePickerView: Component<
  ArkDatePickerViewProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.View {...props} data-scope="date-picker" data-part="view">
      {props.children}
    </ArkDatePicker.View>
  );
};

export const LoongArkDatePickerViewControl: Component<
  ArkDatePickerViewControlProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.ViewControl
      {...props}
      data-scope="date-picker"
      data-part="view-control"
    >
      {props.children}
    </ArkDatePicker.ViewControl>
  );
};

export const LoongArkDatePickerViewTrigger: Component<
  ArkDatePickerViewTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.ViewTrigger
      {...props}
      data-scope="date-picker"
      data-part="view-trigger"
    >
      {props.children}
    </ArkDatePicker.ViewTrigger>
  );
};

export const LoongArkDatePickerPrevTrigger: Component<
  ArkDatePickerPrevTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.PrevTrigger
      {...props}
      data-scope="date-picker"
      data-part="prev-trigger"
    >
      {props.children}
    </ArkDatePicker.PrevTrigger>
  );
};

export const LoongArkDatePickerNextTrigger: Component<
  ArkDatePickerNextTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.NextTrigger
      {...props}
      data-scope="date-picker"
      data-part="next-trigger"
    >
      {props.children}
    </ArkDatePicker.NextTrigger>
  );
};

export const LoongArkDatePickerMonthSelect: Component<
  ArkDatePickerMonthSelectProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.MonthSelect
      {...props}
      data-scope="date-picker"
      data-part="month-select"
    >
      {props.children}
    </ArkDatePicker.MonthSelect>
  );
};

export const LoongArkDatePickerYearSelect: Component<
  ArkDatePickerYearSelectProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.YearSelect
      {...props}
      data-scope="date-picker"
      data-part="year-select"
    >
      {props.children}
    </ArkDatePicker.YearSelect>
  );
};

export const LoongArkDatePickerRangeText: Component<
  ArkDatePickerRangeTextProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.RangeText
      {...props}
      data-scope="date-picker"
      data-part="range-text"
    >
      {props.children}
    </ArkDatePicker.RangeText>
  );
};

export const LoongArkDatePickerPresetTrigger: Component<
  ArkDatePickerPresetTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.PresetTrigger
      {...props}
      data-scope="date-picker"
      data-part="preset-trigger"
    >
      {props.children}
    </ArkDatePicker.PresetTrigger>
  );
};

export const LoongArkDatePickerTable: Component<
  ArkDatePickerTableProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.Table {...props} data-scope="date-picker" data-part="table">
      {props.children}
    </ArkDatePicker.Table>
  );
};

export const LoongArkDatePickerTableHead: Component<
  ArkDatePickerTableHeadProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.TableHead
      {...props}
      data-scope="date-picker"
      data-part="table-head"
    >
      {props.children}
    </ArkDatePicker.TableHead>
  );
};

export const LoongArkDatePickerTableBody: Component<
  ArkDatePickerTableBodyProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.TableBody
      {...props}
      data-scope="date-picker"
      data-part="table-body"
    >
      {props.children}
    </ArkDatePicker.TableBody>
  );
};

export const LoongArkDatePickerTableRow: Component<
  ArkDatePickerTableRowProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.TableRow
      {...props}
      data-scope="date-picker"
      data-part="table-row"
    >
      {props.children}
    </ArkDatePicker.TableRow>
  );
};

export const LoongArkDatePickerTableHeader: Component<
  ArkDatePickerTableHeaderProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.TableHeader
      {...props}
      data-scope="date-picker"
      data-part="table-header"
    >
      {props.children}
    </ArkDatePicker.TableHeader>
  );
};

export const LoongArkDatePickerTableCell: Component<
  ArkDatePickerTableCellProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.TableCell
      {...props}
      data-scope="date-picker"
      data-part="table-cell"
    >
      {props.children}
    </ArkDatePicker.TableCell>
  );
};

export const LoongArkDatePickerTableCellTrigger: Component<
  ArkDatePickerTableCellTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkDatePicker.TableCellTrigger
      {...props}
      data-scope="date-picker"
      data-part="table-cell-trigger"
    >
      {props.children}
    </ArkDatePicker.TableCellTrigger>
  );
};
