// packages/react/src/components/drawer-actions.ts
import {
  createElement,
  forwardRef,
  useId,
  type ComponentPropsWithoutRef,
} from "react";
import { Drawer } from "@ark-ui/react/drawer";
import { dataProps } from "../data-props";
const action = (variant: "solid" | "outline") =>
  forwardRef<
    HTMLButtonElement,
    ComponentPropsWithoutRef<typeof Drawer.CloseTrigger>
  >((props, ref) => {
    const id = useId();
    return createElement(
      Drawer.CloseTrigger,
      dataProps({
        ...props,
        ref,
        id: props.id ?? id,
        "data-scope": "button",
        "data-part": "root",
        "data-variant": variant,
        "data-size": "md",
      }),
    );
  });
export const DrawerAction = action("solid");
export const DrawerCancel = action("outline");

// packages/solid/src/components/drawer-actions.tsx
import { createUniqueId } from "solid-js";
import { Drawer, type DrawerCloseTriggerProps } from "@ark-ui/solid/drawer";
const action =
  (variant: "solid" | "outline") => (props: DrawerCloseTriggerProps) => {
    const id = createUniqueId();
    return (
      <Drawer.CloseTrigger
        {...props}
        id={props.id ?? id}
        data-scope="button"
        data-part="root"
        data-variant={variant}
        data-size="md"
      />
    );
  };
export const DrawerAction = action("solid");
export const DrawerCancel = action("outline");
