// packages/react/src/components/number-input.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
/**
 * Number Input component - React wrapper.
 * Based on Ark UI Number Input with data-scope/data-part bindings.
 */
import React, { forwardRef, type ReactNode } from "react";
import {
  NumberInput as ArkNumberInput,
  type NumberInputRootProps as ArkNumberInputRootProps,
  type NumberInputLabelProps as ArkNumberInputLabelProps,
  type NumberInputControlProps as ArkNumberInputControlProps,
  type NumberInputInputProps as ArkNumberInputInputProps,
  type NumberInputIncrementTriggerProps as ArkNumberInputIncrementTriggerProps,
  type NumberInputDecrementTriggerProps as ArkNumberInputDecrementTriggerProps,
  type NumberInputValueTextProps as ArkNumberInputValueTextProps,
  type NumberInputScrubberProps as ArkNumberInputScrubberProps,
} from "@ark-ui/react/number-input";
import type {
  NumberInputPrimitiveProps,
  NumberInputSize,
  NumberInputState,
} from "@loongark/primitives";

export interface LoongArkNumberInputRootProps
  extends
    Omit<ArkNumberInputRootProps, "asChild">,
    Partial<NumberInputPrimitiveProps> {
  children?: ReactNode;
}

export interface LoongArkNumberInputLabelProps extends Omit<
  ArkNumberInputLabelProps,
  "asChild"
> {
  children?: ReactNode;
}

export interface LoongArkNumberInputControlProps
  extends
    Omit<ArkNumberInputControlProps, "asChild">,
    Partial<NumberInputPrimitiveProps> {
  children?: ReactNode;
}

export interface LoongArkNumberInputInputProps
  extends
    Omit<ArkNumberInputInputProps, "asChild" | "size">,
    Partial<NumberInputPrimitiveProps> {}

export interface LoongArkNumberInputIncrementTriggerProps
  extends
    Omit<ArkNumberInputIncrementTriggerProps, "asChild">,
    Partial<NumberInputPrimitiveProps> {
  children?: ReactNode;
}

export interface LoongArkNumberInputDecrementTriggerProps
  extends
    Omit<ArkNumberInputDecrementTriggerProps, "asChild">,
    Partial<NumberInputPrimitiveProps> {
  children?: ReactNode;
}

export interface LoongArkNumberInputValueTextProps
  extends
    Omit<ArkNumberInputValueTextProps, "asChild">,
    Partial<NumberInputPrimitiveProps> {
  children?: ReactNode;
}

export interface LoongArkNumberInputScrubberProps extends Omit<
  ArkNumberInputScrubberProps,
  "asChild"
> {
  children?: ReactNode;
}

export const LoongArkNumberInputRoot = forwardRef<
  HTMLDivElement,
  LoongArkNumberInputRootProps
>(
  (
    {
      children,
      size = "md",
      state = "default",
      disabled = false,
      readOnly = false,
      ...props
    },
    ref,
  ) => {
    return (
      <ArkNumberInput.Root
        {...props}
        ref={ref}
        disabled={disabled}
        readOnly={readOnly}
        data-scope="number-input"
        data-part="root"
        data-size={size}
        data-state={state !== "default" ? state : undefined}
        data-disabled={disabled ? "true" : undefined}
        data-readonly={readOnly ? "true" : undefined}
      >
        {children}
      </ArkNumberInput.Root>
    );
  },
);

LoongArkNumberInputRoot.displayName = "LoongArkNumberInputRoot";

export const LoongArkNumberInputLabel = forwardRef<
  HTMLLabelElement,
  LoongArkNumberInputLabelProps
>((props, ref) => {
  return (
    <ArkNumberInput.Label
      {...props}
      ref={ref}
      data-scope="number-input"
      data-part="label"
    />
  );
});

LoongArkNumberInputLabel.displayName = "LoongArkNumberInputLabel";

export const LoongArkNumberInputControl = forwardRef<
  HTMLDivElement,
  LoongArkNumberInputControlProps
>(
  (
    { children, size = "md", state = "default", disabled = false, ...props },
    ref,
  ) => {
    return (
      <ArkNumberInput.Control
        {...props}
        ref={ref}
        data-scope="number-input"
        data-part="control"
        data-size={size}
        data-state={state !== "default" ? state : undefined}
        data-disabled={disabled ? "true" : undefined}
      >
        {children}
      </ArkNumberInput.Control>
    );
  },
);

LoongArkNumberInputControl.displayName = "LoongArkNumberInputControl";

export const LoongArkNumberInputInput = forwardRef<
  HTMLInputElement,
  LoongArkNumberInputInputProps
>(
  (
    {
      size = "md",
      state = "default",
      disabled = false,
      readOnly = false,
      ...props
    },
    ref,
  ) => {
    return (
      <ArkNumberInput.Input
        {...props}
        ref={ref}
        disabled={disabled}
        readOnly={readOnly}
        data-scope="number-input"
        data-part="input"
        data-size={size}
        data-state={state !== "default" ? state : undefined}
        data-disabled={disabled ? "true" : undefined}
        data-readonly={readOnly ? "true" : undefined}
      />
    );
  },
);

LoongArkNumberInputInput.displayName = "LoongArkNumberInputInput";

export const LoongArkNumberInputIncrementTrigger = forwardRef<
  HTMLButtonElement,
  LoongArkNumberInputIncrementTriggerProps
>(
  (
    { children, size = "md", state = "default", disabled = false, ...props },
    ref,
  ) => {
    return (
      <ArkNumberInput.IncrementTrigger
        {...props}
        ref={ref}
        disabled={disabled}
        data-scope="number-input"
        data-part="increment-trigger"
        data-size={size}
        data-state={state !== "default" ? state : undefined}
        data-disabled={disabled ? "true" : undefined}
      >
        {children ?? <LoongArkIcon icon={controlIcons.plus} size="sm" />}
      </ArkNumberInput.IncrementTrigger>
    );
  },
);

LoongArkNumberInputIncrementTrigger.displayName =
  "LoongArkNumberInputIncrementTrigger";

export const LoongArkNumberInputDecrementTrigger = forwardRef<
  HTMLButtonElement,
  LoongArkNumberInputDecrementTriggerProps
>(
  (
    { children, size = "md", state = "default", disabled = false, ...props },
    ref,
  ) => {
    return (
      <ArkNumberInput.DecrementTrigger
        {...props}
        ref={ref}
        disabled={disabled}
        data-scope="number-input"
        data-part="decrement-trigger"
        data-size={size}
        data-state={state !== "default" ? state : undefined}
        data-disabled={disabled ? "true" : undefined}
      >
        {children ?? <LoongArkIcon icon={controlIcons.minus} size="sm" />}
      </ArkNumberInput.DecrementTrigger>
    );
  },
);

LoongArkNumberInputDecrementTrigger.displayName =
  "LoongArkNumberInputDecrementTrigger";

export const LoongArkNumberInputValueText = forwardRef<
  HTMLSpanElement,
  LoongArkNumberInputValueTextProps
>(({ children, size = "md", ...props }, ref) => {
  return (
    <ArkNumberInput.ValueText
      {...props}
      ref={ref}
      data-scope="number-input"
      data-part="value-text"
      data-size={size}
    >
      {children}
    </ArkNumberInput.ValueText>
  );
});

LoongArkNumberInputValueText.displayName = "LoongArkNumberInputValueText";

export const LoongArkNumberInputScrubber = forwardRef<
  HTMLDivElement,
  LoongArkNumberInputScrubberProps
>(({ children, ...props }, ref) => {
  return (
    <ArkNumberInput.Scrubber
      {...props}
      ref={ref}
      data-scope="number-input"
      data-part="scrubber"
    >
      {children}
    </ArkNumberInput.Scrubber>
  );
});

LoongArkNumberInputScrubber.displayName = "LoongArkNumberInputScrubber";

export type { NumberInputSize, NumberInputState };

// packages/solid/src/components/number-input.tsx
/** @jsxImportSource solid-js */
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
/**
 * Number Input component - Solid wrapper.
 * Uses Ark UI Number Input with data attributes for styling.
 */
import { type Component, type JSX, mergeProps, splitProps } from "solid-js";
import {
  NumberInput as ArkNumberInput,
  type NumberInputRootProps as ArkNumberInputRootProps,
  type NumberInputLabelProps as ArkNumberInputLabelProps,
  type NumberInputControlProps as ArkNumberInputControlProps,
  type NumberInputInputProps as ArkNumberInputInputProps,
  type NumberInputIncrementTriggerProps as ArkNumberInputIncrementTriggerProps,
  type NumberInputDecrementTriggerProps as ArkNumberInputDecrementTriggerProps,
  type NumberInputValueTextProps as ArkNumberInputValueTextProps,
  type NumberInputScrubberProps as ArkNumberInputScrubberProps,
} from "@ark-ui/solid/number-input";
import type { NumberInputSize, NumberInputState } from "@loongark/primitives";

export interface LoongArkNumberInputRootProps extends Omit<
  ArkNumberInputRootProps,
  "asChild"
> {
  size?: NumberInputSize;
  state?: NumberInputState;
  children?: JSX.Element;
}

export const LoongArkNumberInputRoot: Component<
  LoongArkNumberInputRootProps
> = (props) => {
  const merged = mergeProps(
    {
      size: "md" as NumberInputSize,
      state: "default" as NumberInputState,
      disabled: false,
      readOnly: false,
    },
    props,
  );
  const [local, others] = splitProps(merged, [
    "children",
    "size",
    "state",
    "disabled",
    "readOnly",
  ]);

  return (
    <ArkNumberInput.Root
      {...others}
      disabled={local.disabled}
      readOnly={local.readOnly}
      data-scope="number-input"
      data-part="root"
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-disabled={local.disabled ? "true" : undefined}
      data-readonly={local.readOnly ? "true" : undefined}
    >
      {local.children}
    </ArkNumberInput.Root>
  );
};

export interface LoongArkNumberInputLabelProps extends Omit<
  ArkNumberInputLabelProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkNumberInputLabel: Component<
  LoongArkNumberInputLabelProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);

  return (
    <ArkNumberInput.Label
      {...others}
      data-scope="number-input"
      data-part="label"
    >
      {local.children}
    </ArkNumberInput.Label>
  );
};

export interface LoongArkNumberInputControlProps extends Omit<
  ArkNumberInputControlProps,
  "asChild"
> {
  size?: NumberInputSize;
  state?: NumberInputState;
  disabled?: boolean;
  children?: JSX.Element;
}

export const LoongArkNumberInputControl: Component<
  LoongArkNumberInputControlProps
> = (props) => {
  const merged = mergeProps(
    {
      size: "md" as NumberInputSize,
      state: "default" as NumberInputState,
      disabled: false,
    },
    props,
  );
  const [local, others] = splitProps(merged, [
    "children",
    "size",
    "state",
    "disabled",
  ]);

  return (
    <ArkNumberInput.Control
      {...others}
      data-scope="number-input"
      data-part="control"
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-disabled={local.disabled ? "true" : undefined}
    >
      {local.children}
    </ArkNumberInput.Control>
  );
};

export interface LoongArkNumberInputInputProps extends Omit<
  ArkNumberInputInputProps,
  "asChild"
> {
  size?: NumberInputSize;
  state?: NumberInputState;
  disabled?: boolean;
  readOnly?: boolean;
}

export const LoongArkNumberInputInput: Component<
  LoongArkNumberInputInputProps
> = (props) => {
  const merged = mergeProps(
    {
      size: "md" as NumberInputSize,
      state: "default" as NumberInputState,
      disabled: false,
      readOnly: false,
    },
    props,
  );
  const [local, others] = splitProps(merged, [
    "size",
    "state",
    "disabled",
    "readOnly",
  ]);

  return (
    <ArkNumberInput.Input
      {...others}
      disabled={local.disabled}
      readOnly={local.readOnly}
      data-scope="number-input"
      data-part="input"
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-disabled={local.disabled ? "true" : undefined}
      data-readonly={local.readOnly ? "true" : undefined}
    />
  );
};

export interface LoongArkNumberInputIncrementTriggerProps extends Omit<
  ArkNumberInputIncrementTriggerProps,
  "asChild"
> {
  size?: NumberInputSize;
  state?: NumberInputState;
  disabled?: boolean;
  children?: JSX.Element;
}

export const LoongArkNumberInputIncrementTrigger: Component<
  LoongArkNumberInputIncrementTriggerProps
> = (props) => {
  const merged = mergeProps(
    {
      size: "md" as NumberInputSize,
      state: "default" as NumberInputState,
      disabled: false,
    },
    props,
  );
  const [local, others] = splitProps(merged, [
    "children",
    "size",
    "state",
    "disabled",
  ]);

  return (
    <ArkNumberInput.IncrementTrigger
      {...others}
      disabled={local.disabled}
      data-scope="number-input"
      data-part="increment-trigger"
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-disabled={local.disabled ? "true" : undefined}
    >
      {local.children ?? <LoongArkIcon icon={controlIcons.plus} size="sm" />}
    </ArkNumberInput.IncrementTrigger>
  );
};

export interface LoongArkNumberInputDecrementTriggerProps extends Omit<
  ArkNumberInputDecrementTriggerProps,
  "asChild"
> {
  size?: NumberInputSize;
  state?: NumberInputState;
  disabled?: boolean;
  children?: JSX.Element;
}

export const LoongArkNumberInputDecrementTrigger: Component<
  LoongArkNumberInputDecrementTriggerProps
> = (props) => {
  const merged = mergeProps(
    {
      size: "md" as NumberInputSize,
      state: "default" as NumberInputState,
      disabled: false,
    },
    props,
  );
  const [local, others] = splitProps(merged, [
    "children",
    "size",
    "state",
    "disabled",
  ]);

  return (
    <ArkNumberInput.DecrementTrigger
      {...others}
      disabled={local.disabled}
      data-scope="number-input"
      data-part="decrement-trigger"
      data-size={local.size}
      data-state={local.state !== "default" ? local.state : undefined}
      data-disabled={local.disabled ? "true" : undefined}
    >
      {local.children ?? <LoongArkIcon icon={controlIcons.minus} size="sm" />}
    </ArkNumberInput.DecrementTrigger>
  );
};

export interface LoongArkNumberInputValueTextProps extends Omit<
  ArkNumberInputValueTextProps,
  "asChild"
> {
  size?: NumberInputSize;
  children?: JSX.Element;
}

export const LoongArkNumberInputValueText: Component<
  LoongArkNumberInputValueTextProps
> = (props) => {
  const merged = mergeProps({ size: "md" as NumberInputSize }, props);
  const [local, others] = splitProps(merged, ["children", "size"]);

  return (
    <ArkNumberInput.ValueText
      {...others}
      data-scope="number-input"
      data-part="value-text"
      data-size={local.size}
    >
      {local.children}
    </ArkNumberInput.ValueText>
  );
};

export interface LoongArkNumberInputScrubberProps extends Omit<
  ArkNumberInputScrubberProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkNumberInputScrubber: Component<
  LoongArkNumberInputScrubberProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);

  return (
    <ArkNumberInput.Scrubber
      {...others}
      data-scope="number-input"
      data-part="scrubber"
    >
      {local.children}
    </ArkNumberInput.Scrubber>
  );
};
