// packages/react/src/components/select.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
/**
 * Select 组件 - React 实现
 * 基于 Ark UI Select 的下拉选择器
 */

import React, {
  forwardRef,
  createContext,
  useContext,
  createElement,
  type FC,
  type ReactNode,
} from "react";
import {
  Select as ArkSelect,
  type SelectRootProps as ArkSelectRootProps,
  type SelectLabelProps as ArkSelectLabelProps,
  type SelectControlProps as ArkSelectControlProps,
  type SelectTriggerProps as ArkSelectTriggerProps,
  type SelectValueTextProps as ArkSelectValueTextProps,
  type SelectIndicatorProps as ArkSelectIndicatorProps,
  type SelectClearTriggerProps as ArkSelectClearTriggerProps,
  type SelectPositionerProps as ArkSelectPositionerProps,
  type SelectContentProps as ArkSelectContentProps,
  type SelectListProps as ArkSelectListProps,
  type SelectItemGroupProps as ArkSelectItemGroupProps,
  type SelectItemGroupLabelProps as ArkSelectItemGroupLabelProps,
  type SelectItemProps as ArkSelectItemProps,
  type SelectItemTextProps as ArkSelectItemTextProps,
  type SelectItemIndicatorProps as ArkSelectItemIndicatorProps,
  type SelectHiddenSelectProps as ArkSelectHiddenSelectProps,
} from "@ark-ui/react/select";
import type { SelectSize } from "@loongark/primitives";
import { Portal as ArkPortal } from "./portal";

const SafePortal: FC<{ children?: ReactNode }> = ({ children }) =>
  createElement(ArkPortal, null, children);

const SelectContext = createContext<{ size: SelectSize }>({ size: "md" });

/**
 * Select Root Props
 */
export interface SelectRootProps<T = object> extends Omit<
  ArkSelectRootProps<T>,
  "asChild"
> {
  size?: SelectSize;
}

/**
 * Select Root 组件
 */
export function SelectRoot<T = object>(props: SelectRootProps<T>) {
  const { size = "md", ...rest } = props;

  return (
    <SelectContext.Provider value={{ size }}>
      <ArkSelect.Root
        {...rest}
        data-scope="select"
        data-part="root"
        data-size={size}
      />
    </SelectContext.Provider>
  );
}

SelectRoot.displayName = "LoongArkSelectRoot";

/**
 * Select Label 组件
 */
export const SelectLabel = forwardRef<HTMLLabelElement, ArkSelectLabelProps>(
  (props, ref) => {
    return (
      <ArkSelect.Label
        {...props}
        ref={ref}
        data-scope="select"
        data-part="label"
      />
    );
  },
);

SelectLabel.displayName = "LoongArkSelectLabel";

/**
 * Select Control 组件
 */
export const SelectControl = forwardRef<HTMLDivElement, ArkSelectControlProps>(
  (props, ref) => {
    return (
      <ArkSelect.Control
        {...props}
        ref={ref}
        data-scope="select"
        data-part="control"
      />
    );
  },
);

SelectControl.displayName = "LoongArkSelectControl";

/**
 * Select Trigger 组件
 */
export const SelectTrigger = forwardRef<
  HTMLButtonElement,
  ArkSelectTriggerProps
>((props, ref) => {
  return (
    <ArkSelect.Trigger
      {...props}
      ref={ref}
      data-scope="select"
      data-part="trigger"
    />
  );
});

SelectTrigger.displayName = "LoongArkSelectTrigger";

/**
 * Select ValueText 组件
 */
export const SelectValueText = forwardRef<
  HTMLSpanElement,
  ArkSelectValueTextProps
>((props, ref) => {
  return (
    <ArkSelect.ValueText
      {...props}
      ref={ref}
      data-scope="select"
      data-part="value-text"
    />
  );
});

SelectValueText.displayName = "LoongArkSelectValueText";

/**
 * Select Indicator 组件
 */
export const SelectIndicator = forwardRef<
  HTMLDivElement,
  ArkSelectIndicatorProps
>((props, ref) => {
  return (
    <ArkSelect.Indicator
      {...props}
      ref={ref}
      data-scope="select"
      data-part="indicator"
    >
      {props.children ?? (
        <LoongArkIcon icon={controlIcons.chevronDown} size="sm" />
      )}
    </ArkSelect.Indicator>
  );
});

SelectIndicator.displayName = "LoongArkSelectIndicator";

/**
 * Select ClearTrigger 组件
 */
export const SelectClearTrigger = forwardRef<
  HTMLButtonElement,
  ArkSelectClearTriggerProps
>((props, ref) => {
  return (
    <ArkSelect.ClearTrigger
      {...props}
      ref={ref}
      data-scope="select"
      data-part="clear-trigger"
    />
  );
});

SelectClearTrigger.displayName = "LoongArkSelectClearTrigger";

/**
 * Select Positioner 组件
 */
export const SelectPositioner = forwardRef<
  HTMLDivElement,
  ArkSelectPositionerProps
>((props, ref) => {
  return (
    <SafePortal>
      <ArkSelect.Positioner
        {...props}
        ref={ref}
        data-scope="select"
        data-part="positioner"
      />
    </SafePortal>
  );
});

SelectPositioner.displayName = "LoongArkSelectPositioner";

/**
 * Select Content 组件
 */
export const SelectContent = forwardRef<HTMLDivElement, ArkSelectContentProps>(
  (props, ref) => {
    const { size } = useContext(SelectContext);
    return (
      <ArkSelect.Content
        {...props}
        ref={ref}
        data-scope="select"
        data-part="content"
        data-size={size}
      />
    );
  },
);

SelectContent.displayName = "LoongArkSelectContent";

/**
 * Select List 组件
 */
export const SelectList = forwardRef<HTMLDivElement, ArkSelectListProps>(
  (props, ref) => {
    return (
      <ArkSelect.List
        {...props}
        ref={ref}
        data-scope="select"
        data-part="list"
      />
    );
  },
);

SelectList.displayName = "LoongArkSelectList";

/**
 * Select ItemGroup 组件
 */
export const SelectItemGroup = forwardRef<
  HTMLDivElement,
  ArkSelectItemGroupProps
>((props, ref) => {
  return (
    <ArkSelect.ItemGroup
      {...props}
      ref={ref}
      data-scope="select"
      data-part="item-group"
    />
  );
});

SelectItemGroup.displayName = "LoongArkSelectItemGroup";

/**
 * Select ItemGroupLabel 组件
 */
export const SelectItemGroupLabel = forwardRef<
  HTMLDivElement,
  ArkSelectItemGroupLabelProps
>((props, ref) => {
  return (
    <ArkSelect.ItemGroupLabel
      {...props}
      ref={ref}
      data-scope="select"
      data-part="item-group-label"
    />
  );
});

SelectItemGroupLabel.displayName = "LoongArkSelectItemGroupLabel";

/**
 * Select Item 组件
 */
export const SelectItem = forwardRef<HTMLDivElement, ArkSelectItemProps>(
  (props, ref) => {
    return (
      <ArkSelect.Item
        {...props}
        ref={ref}
        data-scope="select"
        data-part="item"
      />
    );
  },
);

SelectItem.displayName = "LoongArkSelectItem";

/**
 * Select ItemText 组件
 */
export const SelectItemText = forwardRef<
  HTMLDivElement,
  ArkSelectItemTextProps
>((props, ref) => {
  return (
    <ArkSelect.ItemText
      {...props}
      ref={ref}
      data-scope="select"
      data-part="item-text"
    />
  );
});

SelectItemText.displayName = "LoongArkSelectItemText";

/**
 * Select ItemIndicator 组件
 */
export const SelectItemIndicator = forwardRef<
  HTMLDivElement,
  ArkSelectItemIndicatorProps
>(({ children, ...props }, ref) => {
  return (
    <ArkSelect.ItemIndicator
      {...props}
      ref={ref}
      data-scope="select"
      data-part="item-indicator"
    >
      {children || <LoongArkIcon icon={controlIcons.check} size="sm" />}
    </ArkSelect.ItemIndicator>
  );
});

SelectItemIndicator.displayName = "LoongArkSelectItemIndicator";

/**
 * Select HiddenSelect 组件 (用于表单提交)
 */
export const SelectHiddenSelect = forwardRef<
  HTMLSelectElement,
  ArkSelectHiddenSelectProps
>((props, ref) => {
  return (
    <ArkSelect.HiddenSelect
      {...props}
      ref={ref}
      data-scope="select"
      data-part="hidden-select"
    />
  );
});

SelectHiddenSelect.displayName = "LoongArkSelectHiddenSelect";

// packages/solid/src/components/select.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "./icon";
/**
 * Select 组件 - Solid 实现
 * 基于 Ark UI Select 的下拉选择器
 */

import {
  type Component,
  type JSX,
  mergeProps,
  createContext,
  useContext,
} from "solid-js";
import {
  Select as ArkSelect,
  type SelectRootProps as ArkSelectRootProps,
  type SelectLabelProps as ArkSelectLabelProps,
  type SelectControlProps as ArkSelectControlProps,
  type SelectTriggerProps as ArkSelectTriggerProps,
  type SelectValueTextProps as ArkSelectValueTextProps,
  type SelectIndicatorProps as ArkSelectIndicatorProps,
  type SelectClearTriggerProps as ArkSelectClearTriggerProps,
  type SelectPositionerProps as ArkSelectPositionerProps,
  type SelectContentProps as ArkSelectContentProps,
  type SelectListProps as ArkSelectListProps,
  type SelectItemGroupProps as ArkSelectItemGroupProps,
  type SelectItemGroupLabelProps as ArkSelectItemGroupLabelProps,
  type SelectItemProps as ArkSelectItemProps,
  type SelectItemTextProps as ArkSelectItemTextProps,
  type SelectItemIndicatorProps as ArkSelectItemIndicatorProps,
  type SelectHiddenSelectProps as ArkSelectHiddenSelectProps,
} from "@ark-ui/solid/select";
import type { SelectSize } from "@loongark/primitives";

const SelectContext = createContext<{ size: SelectSize }>({ size: "md" });

/**
 * Select Root Props
 */
export interface LoongArkSelectRootProps<
  T extends object = object,
> extends Omit<ArkSelectRootProps<T>, "asChild"> {
  size?: SelectSize;
  children?: JSX.Element;
}

/**
 * Select Root 组件
 */
export const LoongArkSelectRoot = <T extends object>(
  props: LoongArkSelectRootProps<T>,
): JSX.Element => {
  const merged = mergeProps({ size: "md" as SelectSize }, props);

  return (
    <SelectContext.Provider value={{ size: merged.size }}>
      <ArkSelect.Root
        {...props}
        data-scope="select"
        data-part="root"
        data-size={merged.size}
      >
        {props.children}
      </ArkSelect.Root>
    </SelectContext.Provider>
  );
};

/**
 * Select Label 组件
 */
export const LoongArkSelectLabel: Component<
  ArkSelectLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.Label {...props} data-scope="select" data-part="label">
      {props.children}
    </ArkSelect.Label>
  );
};

/**
 * Select Control 组件
 */
export const LoongArkSelectControl: Component<
  ArkSelectControlProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.Control {...props} data-scope="select" data-part="control">
      {props.children}
    </ArkSelect.Control>
  );
};

/**
 * Select Trigger 组件
 */
export const LoongArkSelectTrigger: Component<
  ArkSelectTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.Trigger {...props} data-scope="select" data-part="trigger">
      {props.children}
    </ArkSelect.Trigger>
  );
};

/**
 * Select ValueText 组件
 */
export const LoongArkSelectValueText: Component<
  ArkSelectValueTextProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.ValueText {...props} data-scope="select" data-part="value-text">
      {props.children}
    </ArkSelect.ValueText>
  );
};

/**
 * Select Indicator 组件
 */
export const LoongArkSelectIndicator: Component<
  ArkSelectIndicatorProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.Indicator {...props} data-scope="select" data-part="indicator">
      {props.children ?? (
        <LoongArkIcon icon={controlIcons.chevronDown} size="sm" />
      )}
    </ArkSelect.Indicator>
  );
};

/**
 * Select ClearTrigger 组件
 */
export const LoongArkSelectClearTrigger: Component<
  ArkSelectClearTriggerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.ClearTrigger
      {...props}
      data-scope="select"
      data-part="clear-trigger"
    >
      {props.children}
    </ArkSelect.ClearTrigger>
  );
};

/**
 * Select Positioner 组件
 */
export const LoongArkSelectPositioner: Component<
  ArkSelectPositionerProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.Positioner {...props} data-scope="select" data-part="positioner">
      {props.children}
    </ArkSelect.Positioner>
  );
};

/**
 * Select Content 组件
 */
export const LoongArkSelectContent: Component<
  ArkSelectContentProps & { children?: JSX.Element }
> = (props) => {
  const { size } = useContext(SelectContext);
  return (
    <ArkSelect.Content
      {...props}
      data-scope="select"
      data-part="content"
      data-size={size}
    >
      {props.children}
    </ArkSelect.Content>
  );
};

/**
 * Select List 组件
 */
export const LoongArkSelectList: Component<
  ArkSelectListProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.List {...props} data-scope="select" data-part="list">
      {props.children}
    </ArkSelect.List>
  );
};

/**
 * Select ItemGroup 组件
 */
export const LoongArkSelectItemGroup: Component<
  ArkSelectItemGroupProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.ItemGroup {...props} data-scope="select" data-part="item-group">
      {props.children}
    </ArkSelect.ItemGroup>
  );
};

/**
 * Select ItemGroupLabel 组件
 */
export const LoongArkSelectItemGroupLabel: Component<
  ArkSelectItemGroupLabelProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.ItemGroupLabel
      {...props}
      data-scope="select"
      data-part="item-group-label"
    >
      {props.children}
    </ArkSelect.ItemGroupLabel>
  );
};

/**
 * Select Item 组件
 */
export const LoongArkSelectItem: Component<
  ArkSelectItemProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.Item {...props} data-scope="select" data-part="item">
      {props.children}
    </ArkSelect.Item>
  );
};

/**
 * Select ItemText 组件
 */
export const LoongArkSelectItemText: Component<
  ArkSelectItemTextProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.ItemText {...props} data-scope="select" data-part="item-text">
      {props.children}
    </ArkSelect.ItemText>
  );
};

/**
 * Select ItemIndicator 组件
 */
export const LoongArkSelectItemIndicator: Component<
  ArkSelectItemIndicatorProps & { children?: JSX.Element }
> = (props) => {
  return (
    <ArkSelect.ItemIndicator
      {...props}
      data-scope="select"
      data-part="item-indicator"
    >
      {props.children ?? <LoongArkIcon icon={controlIcons.check} size="sm" />}
    </ArkSelect.ItemIndicator>
  );
};

/**
 * Select HiddenSelect 组件
 */
export const LoongArkSelectHiddenSelect: Component<
  ArkSelectHiddenSelectProps
> = (props) => {
  return (
    <ArkSelect.HiddenSelect
      {...props}
      data-scope="select"
      data-part="hidden-select"
    />
  );
};
