// packages/react/src/components/splitter.tsx
/**
 * Splitter component - React wrapper.
 * Uses Ark UI Splitter with data attributes for styling.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { Splitter } from "@ark-ui/react/splitter";
import type { SplitterSize } from "@loongark/primitives";

type ArkSplitterRootProps = ComponentPropsWithoutRef<typeof Splitter.Root>;
type ArkSplitterPanelProps = ComponentPropsWithoutRef<typeof Splitter.Panel>;
type ArkSplitterResizeTriggerProps = ComponentPropsWithoutRef<
  typeof Splitter.ResizeTrigger
>;
type ArkSplitterResizeTriggerIndicatorProps = ComponentPropsWithoutRef<
  typeof Splitter.ResizeTriggerIndicator
>;

export interface LoongArkSplitterRootProps extends Omit<
  ArkSplitterRootProps,
  "asChild" | "size"
> {
  size?: SplitterSize;
  children?: ReactNode;
}

export const LoongArkSplitterRoot = forwardRef<
  HTMLDivElement,
  LoongArkSplitterRootProps
>(({ size = "md", children, ...props }, ref) => {
  return (
    <Splitter.Root
      {...props}
      ref={ref}
      data-scope="splitter"
      data-part="root"
      data-size={size}
    >
      {children}
    </Splitter.Root>
  );
});

LoongArkSplitterRoot.displayName = "LoongArkSplitterRoot";

export const LoongArkSplitterPanel = forwardRef<
  HTMLDivElement,
  ArkSplitterPanelProps
>((props, ref) => {
  return (
    <Splitter.Panel
      {...props}
      ref={ref}
      data-scope="splitter"
      data-part="panel"
    />
  );
});

LoongArkSplitterPanel.displayName = "LoongArkSplitterPanel";

export const LoongArkSplitterResizeTrigger = forwardRef<
  HTMLButtonElement,
  ArkSplitterResizeTriggerProps
>((props, ref) => {
  return (
    <Splitter.ResizeTrigger
      aria-label="Resize panels"
      {...props}
      ref={ref}
      data-scope="splitter"
      data-part="resize-trigger"
    />
  );
});

LoongArkSplitterResizeTrigger.displayName = "LoongArkSplitterResizeTrigger";

export const LoongArkSplitterResizeTriggerIndicator = forwardRef<
  HTMLDivElement,
  ArkSplitterResizeTriggerIndicatorProps
>((props, ref) => {
  return (
    <Splitter.ResizeTriggerIndicator
      {...props}
      ref={ref}
      data-scope="splitter"
      data-part="resize-trigger-indicator"
    />
  );
});

LoongArkSplitterResizeTriggerIndicator.displayName =
  "LoongArkSplitterResizeTriggerIndicator";

// packages/solid/src/components/splitter.tsx
/**
 * Splitter component - Solid wrapper.
 * Uses Ark UI Splitter with data attributes for styling.
 */
import { type Component, type JSX, mergeProps, splitProps } from "solid-js";
import {
  Splitter as ArkSplitter,
  type SplitterRootProps as ArkSplitterRootProps,
  type SplitterPanelProps as ArkSplitterPanelProps,
  type SplitterResizeTriggerProps as ArkSplitterResizeTriggerProps,
  type SplitterResizeTriggerIndicatorProps as ArkSplitterResizeTriggerIndicatorProps,
} from "@ark-ui/solid/splitter";
import type { SplitterSize } from "@loongark/primitives";

export interface LoongArkSplitterRootProps extends Omit<
  ArkSplitterRootProps,
  "asChild" | "size"
> {
  size?: SplitterSize;
  children?: JSX.Element;
}

export const LoongArkSplitterRoot: Component<LoongArkSplitterRootProps> = (
  props,
) => {
  const merged = mergeProps({ size: "md" as SplitterSize }, props);
  const [local, others] = splitProps(merged, ["children", "size"]);

  return (
    <ArkSplitter.Root
      {...others}
      data-scope="splitter"
      data-part="root"
      data-size={local.size}
    >
      {local.children}
    </ArkSplitter.Root>
  );
};

export interface LoongArkSplitterPanelProps extends Omit<
  ArkSplitterPanelProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkSplitterPanel: Component<LoongArkSplitterPanelProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSplitter.Panel {...others} data-scope="splitter" data-part="panel">
      {local.children}
    </ArkSplitter.Panel>
  );
};

export interface LoongArkSplitterResizeTriggerProps extends Omit<
  ArkSplitterResizeTriggerProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkSplitterResizeTrigger: Component<
  LoongArkSplitterResizeTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSplitter.ResizeTrigger
      aria-label="Resize panels"
      {...others}
      data-scope="splitter"
      data-part="resize-trigger"
    >
      {local.children}
    </ArkSplitter.ResizeTrigger>
  );
};

export interface LoongArkSplitterResizeTriggerIndicatorProps extends Omit<
  ArkSplitterResizeTriggerIndicatorProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkSplitterResizeTriggerIndicator: Component<
  LoongArkSplitterResizeTriggerIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkSplitter.ResizeTriggerIndicator
      {...others}
      data-scope="splitter"
      data-part="resize-trigger-indicator"
    >
      {local.children}
    </ArkSplitter.ResizeTriggerIndicator>
  );
};
