// packages/react/src/components/textarea.ts
import {
  createElement,
  forwardRef,
  useRef,
  useEffect,
  useLayoutEffect,
  useImperativeHandle,
  type TextareaHTMLAttributes,
} from "react";
import {
  layoutAttributes,
  mountTextareaAutosize,
  textareaRows,
  type TextareaAutosizeOptions,
} from "@loongark/kit";
export type LoongArkTextareaProps =
  TextareaHTMLAttributes<HTMLTextAreaElement> & TextareaAutosizeOptions;
export const LoongArkTextarea = forwardRef<
  HTMLTextAreaElement,
  LoongArkTextareaProps
>(({ autoSize = false, minRows, maxRows, ...props }, ref) => {
  const element = useRef<HTMLTextAreaElement>(null),
    controller = useRef<ReturnType<typeof mountTextareaAutosize> | undefined>(
      undefined,
    );
  const options = useRef({ autoSize, minRows, maxRows });
  options.current = { autoSize, minRows, maxRows };
  useImperativeHandle(ref, () => element.current!);
  useEffect(() => {
    if (!element.current) return;
    controller.current = mountTextareaAutosize(
      element.current,
      () => options.current,
    );
    return () => controller.current?.destroy();
  }, []);
  useLayoutEffect(() => {
    controller.current?.update();
  }, [props.value, props.defaultValue, autoSize, minRows, maxRows, props.rows]);
  return createElement("textarea", {
    ...layoutAttributes("Textarea"),
    ...props,
    ref: element,
    "data-autosize": autoSize ? "true" : undefined,
    rows: autoSize ? textareaRows({ minRows, maxRows }).min : props.rows,
  });
});
LoongArkTextarea.displayName = "LoongArkTextarea";

// packages/solid/src/components/textarea.tsx
import {
  splitProps,
  onMount,
  onCleanup,
  createEffect,
  type JSX,
} from "solid-js";
import {
  layoutAttributes,
  mountTextareaAutosize,
  textareaRows,
  type TextareaAutosizeOptions,
} from "@loongark/kit";
export type LoongArkTextareaProps =
  JSX.TextareaHTMLAttributes<HTMLTextAreaElement> & TextareaAutosizeOptions;
export const LoongArkTextarea = (props: LoongArkTextareaProps) => {
  const [local, rest] = splitProps(props, [
    "value",
    "children",
    "readOnly",
    "ref",
    "autoSize",
    "minRows",
    "maxRows",
    "rows",
  ]);
  let element!: HTMLTextAreaElement,
    controller: ReturnType<typeof mountTextareaAutosize> | undefined;
  onMount(() => {
    controller = mountTextareaAutosize(element, () => local);
  });
  createEffect(() => {
    local.value;
    local.autoSize;
    local.minRows;
    local.maxRows;
    queueMicrotask(() => controller?.update());
  });
  onCleanup(() => controller?.destroy());
  return (
    <textarea
      {...layoutAttributes("Textarea")}
      {...rest}
      readOnly={local.readOnly}
      value={local.value}
      data-autosize={local.autoSize ? "true" : undefined}
      rows={local.autoSize ? textareaRows(local).min : local.rows}
      ref={(el) => {
        element = el;
        if (typeof local.ref === "function") local.ref(el);
      }}
    >
      {local.value ?? local.children}
    </textarea>
  );
};
