// packages/react/src/components/tooltip.tsx
/**
 * Tooltip 组件 - React 封装
 * 基于 Ark UI Tooltip，注入 data-scope/data-part 与 interactive 映射
 */
import React, {
  forwardRef,
  createElement,
  type FC,
  type ReactNode,
} from "react";
import {
  Tooltip as ArkTooltip,
  type TooltipRootProps as ArkTooltipRootProps,
  type TooltipTriggerProps as ArkTooltipTriggerProps,
  type TooltipContentProps as ArkTooltipContentProps,
  type TooltipPositionerProps as ArkTooltipPositionerProps,
  type TooltipArrowProps as ArkTooltipArrowProps,
  type TooltipArrowTipProps as ArkTooltipArrowTipProps,
} from "@ark-ui/react/tooltip";
import { Portal as ArkPortal } from "./portal";

const SafePortal: FC<{ children?: ReactNode }> = ({ children }) =>
  createElement(ArkPortal, null, children);

export interface LoongArkTooltipRootProps extends Omit<
  ArkTooltipRootProps,
  "asChild"
> {}

export const LoongArkTooltipRoot = (props: LoongArkTooltipRootProps) => {
  return <ArkTooltip.Root {...props} data-scope="tooltip" data-part="root" />;
};

export const LoongArkTooltipTrigger = forwardRef<
  HTMLButtonElement,
  ArkTooltipTriggerProps
>(({ asChild = true, children, ...rest }, ref) => {
  return (
    <ArkTooltip.Trigger
      {...rest}
      asChild={asChild}
      ref={ref}
      data-scope="tooltip"
      data-part="trigger"
    >
      {children}
    </ArkTooltip.Trigger>
  );
});
LoongArkTooltipTrigger.displayName = "LoongArkTooltipTrigger";

export const LoongArkTooltipPositioner = forwardRef<
  HTMLDivElement,
  Omit<ArkTooltipPositionerProps, "asChild">
>((props, ref) => {
  return (
    <SafePortal>
      <ArkTooltip.Positioner
        {...props}
        ref={ref}
        data-scope="tooltip"
        data-part="positioner"
      />
    </SafePortal>
  );
});
LoongArkTooltipPositioner.displayName = "LoongArkTooltipPositioner";

export const LoongArkTooltipContent = forwardRef<
  HTMLDivElement,
  Omit<ArkTooltipContentProps, "asChild"> & { interactive?: boolean }
>(({ children, interactive, ...rest }, ref) => {
  return (
    <ArkTooltip.Content
      {...rest}
      ref={ref}
      data-scope="tooltip"
      data-part="content"
      data-interactive={interactive ? "true" : undefined}
    >
      {children}
    </ArkTooltip.Content>
  );
});
LoongArkTooltipContent.displayName = "LoongArkTooltipContent";

export const LoongArkTooltipArrow = forwardRef<
  HTMLDivElement,
  Omit<ArkTooltipArrowProps, "asChild">
>((props, ref) => {
  return (
    <ArkTooltip.Arrow
      {...props}
      ref={ref}
      data-scope="tooltip"
      data-part="arrow"
    />
  );
});
LoongArkTooltipArrow.displayName = "LoongArkTooltipArrow";

export const LoongArkTooltipArrowTip = forwardRef<
  HTMLDivElement,
  Omit<ArkTooltipArrowTipProps, "asChild">
>((props, ref) => {
  return (
    <ArkTooltip.ArrowTip
      {...props}
      ref={ref}
      data-scope="tooltip"
      data-part="arrow-tip"
    />
  );
});
LoongArkTooltipArrowTip.displayName = "LoongArkTooltipArrowTip";

// packages/solid/src/components/tooltip.tsx
import { createMemo, JSX } from "solid-js";
import {
  Tooltip as ArkTooltip,
  type TooltipRootProps as ArkTooltipRootProps,
  type TooltipTriggerProps as ArkTooltipTriggerProps,
  type TooltipContentProps as ArkTooltipContentProps,
  type TooltipPositionerProps as ArkTooltipPositionerProps,
  type TooltipArrowProps as ArkTooltipArrowProps,
  type TooltipArrowTipProps as ArkTooltipArrowTipProps,
} from "@ark-ui/solid/tooltip";

import { LoongArkPortal } from "./portal";

export const LoongArkTooltipRoot = (
  props: ArkTooltipRootProps,
): JSX.Element => (
  <ArkTooltip.Root {...props} data-scope="tooltip" data-part="root" />
);

export const LoongArkTooltipTrigger = (
  props: ArkTooltipTriggerProps,
): JSX.Element => {
  const merged = createMemo(() => ({ ...props }));
  return (
    <ArkTooltip.Trigger
      {...merged()}
      data-scope="tooltip"
      data-part="trigger"
    />
  );
};

export const LoongArkTooltipPositioner = (
  props: ArkTooltipPositionerProps & { children?: JSX.Element },
): JSX.Element => {
  return (
    <LoongArkPortal>
      <ArkTooltip.Positioner
        {...props}
        data-scope="tooltip"
        data-part="positioner"
      />
    </LoongArkPortal>
  );
};

export const LoongArkTooltipContent = (
  props: ArkTooltipContentProps & { interactive?: boolean },
): JSX.Element => {
  const interactive = props.interactive ? "true" : undefined;
  return (
    <ArkTooltip.Content
      {...props}
      data-scope="tooltip"
      data-part="content"
      data-interactive={interactive}
    />
  );
};

export const LoongArkTooltipArrow = (
  props: ArkTooltipArrowProps,
): JSX.Element => (
  <ArkTooltip.Arrow {...props} data-scope="tooltip" data-part="arrow" />
);

export const LoongArkTooltipArrowTip = (
  props: ArkTooltipArrowTipProps,
): JSX.Element => (
  <ArkTooltip.ArrowTip {...props} data-scope="tooltip" data-part="arrow-tip" />
);
