// packages/react/src/components/tree-view.tsx
/**
 * Tree View component - React wrapper.
 * Uses Ark UI Tree View with data attributes for styling.
 */
import React, { forwardRef } from "react";
import type { ComponentPropsWithoutRef, ReactNode } from "react";
import { TreeView } from "@ark-ui/react/tree-view";
import type { TreeViewSize } from "@loongark/primitives";

type ArkTreeViewRootProps<T = object> =
  import("@ark-ui/react/tree-view").TreeViewRootProps<T>;
type ArkTreeViewLabelProps = ComponentPropsWithoutRef<typeof TreeView.Label>;
type ArkTreeViewTreeProps = ComponentPropsWithoutRef<typeof TreeView.Tree>;
type ArkTreeViewItemProps = ComponentPropsWithoutRef<typeof TreeView.Item>;
type ArkTreeViewItemIndicatorProps = ComponentPropsWithoutRef<
  typeof TreeView.ItemIndicator
>;
type ArkTreeViewItemTextProps = ComponentPropsWithoutRef<
  typeof TreeView.ItemText
>;
type ArkTreeViewBranchProps = ComponentPropsWithoutRef<typeof TreeView.Branch>;
type ArkTreeViewBranchContentProps = ComponentPropsWithoutRef<
  typeof TreeView.BranchContent
>;
type ArkTreeViewBranchControlProps = ComponentPropsWithoutRef<
  typeof TreeView.BranchControl
>;
type ArkTreeViewBranchTriggerProps = ComponentPropsWithoutRef<
  typeof TreeView.BranchTrigger
>;
type ArkTreeViewBranchIndicatorProps = ComponentPropsWithoutRef<
  typeof TreeView.BranchIndicator
>;
type ArkTreeViewBranchTextProps = ComponentPropsWithoutRef<
  typeof TreeView.BranchText
>;
type ArkTreeViewBranchIndentGuideProps = ComponentPropsWithoutRef<
  typeof TreeView.BranchIndentGuide
>;
type ArkTreeViewNodeCheckboxProps = ComponentPropsWithoutRef<
  typeof TreeView.NodeCheckbox
>;
type ArkTreeViewNodeCheckboxIndicatorProps = ComponentPropsWithoutRef<
  typeof TreeView.NodeCheckboxIndicator
>;
type ArkTreeViewNodeRenameInputProps = ComponentPropsWithoutRef<
  typeof TreeView.NodeRenameInput
>;

export interface LoongArkTreeViewRootProps<T = object> extends Omit<
  ArkTreeViewRootProps<T>,
  "asChild"
> {
  size?: TreeViewSize;
  children?: ReactNode;
}

export const LoongArkTreeViewRoot = forwardRef<
  HTMLDivElement,
  LoongArkTreeViewRootProps
>(({ size = "md", children, ...props }, ref) => {
  return (
    <TreeView.Root
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="root"
      data-size={size}
    >
      {children}
    </TreeView.Root>
  );
}) as (<T>(
  props: LoongArkTreeViewRootProps<T> &
    import("react").RefAttributes<HTMLDivElement>,
) => import("react").ReactElement | null) & { displayName?: string };

LoongArkTreeViewRoot.displayName = "LoongArkTreeViewRoot";

export const LoongArkTreeViewLabel = forwardRef<
  HTMLHeadingElement,
  ArkTreeViewLabelProps
>((props, ref) => {
  return (
    <TreeView.Label
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="label"
    />
  );
});

LoongArkTreeViewLabel.displayName = "LoongArkTreeViewLabel";

export const LoongArkTreeViewTree = forwardRef<
  HTMLDivElement,
  ArkTreeViewTreeProps
>((props, ref) => {
  return (
    <TreeView.Tree
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="tree"
    />
  );
});

LoongArkTreeViewTree.displayName = "LoongArkTreeViewTree";

export const LoongArkTreeViewItem = forwardRef<
  HTMLDivElement,
  ArkTreeViewItemProps
>((props, ref) => {
  return (
    <TreeView.Item
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="item"
    />
  );
});

LoongArkTreeViewItem.displayName = "LoongArkTreeViewItem";

export const LoongArkTreeViewItemIndicator = forwardRef<
  HTMLDivElement,
  ArkTreeViewItemIndicatorProps
>((props, ref) => {
  return (
    <TreeView.ItemIndicator
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="item-indicator"
    />
  );
});

LoongArkTreeViewItemIndicator.displayName = "LoongArkTreeViewItemIndicator";

export const LoongArkTreeViewItemText = forwardRef<
  HTMLSpanElement,
  ArkTreeViewItemTextProps
>((props, ref) => {
  return (
    <TreeView.ItemText
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="item-text"
    />
  );
});

LoongArkTreeViewItemText.displayName = "LoongArkTreeViewItemText";

export const LoongArkTreeViewBranch = forwardRef<
  HTMLDivElement,
  ArkTreeViewBranchProps
>((props, ref) => {
  return (
    <TreeView.Branch
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch"
    />
  );
});

LoongArkTreeViewBranch.displayName = "LoongArkTreeViewBranch";

export const LoongArkTreeViewBranchContent = forwardRef<
  HTMLDivElement,
  ArkTreeViewBranchContentProps
>((props, ref) => {
  return (
    <TreeView.BranchContent
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch-content"
    />
  );
});

LoongArkTreeViewBranchContent.displayName = "LoongArkTreeViewBranchContent";

export const LoongArkTreeViewBranchControl = forwardRef<
  HTMLDivElement,
  ArkTreeViewBranchControlProps
>((props, ref) => {
  return (
    <TreeView.BranchControl
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch-control"
    />
  );
});

LoongArkTreeViewBranchControl.displayName = "LoongArkTreeViewBranchControl";

export const LoongArkTreeViewBranchTrigger = forwardRef<
  HTMLDivElement,
  ArkTreeViewBranchTriggerProps
>((props, ref) => {
  return (
    <TreeView.BranchTrigger
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch-trigger"
    />
  );
});

LoongArkTreeViewBranchTrigger.displayName = "LoongArkTreeViewBranchTrigger";

export const LoongArkTreeViewBranchIndicator = forwardRef<
  HTMLDivElement,
  ArkTreeViewBranchIndicatorProps
>((props, ref) => {
  return (
    <TreeView.BranchIndicator
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch-indicator"
    />
  );
});

LoongArkTreeViewBranchIndicator.displayName = "LoongArkTreeViewBranchIndicator";

export const LoongArkTreeViewBranchText = forwardRef<
  HTMLSpanElement,
  ArkTreeViewBranchTextProps
>((props, ref) => {
  return (
    <TreeView.BranchText
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch-text"
    />
  );
});

LoongArkTreeViewBranchText.displayName = "LoongArkTreeViewBranchText";

export const LoongArkTreeViewBranchIndentGuide = forwardRef<
  HTMLDivElement,
  ArkTreeViewBranchIndentGuideProps
>((props, ref) => {
  return (
    <TreeView.BranchIndentGuide
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="branch-indent-guide"
    />
  );
});

LoongArkTreeViewBranchIndentGuide.displayName =
  "LoongArkTreeViewBranchIndentGuide";

export const LoongArkTreeViewNodeCheckbox = forwardRef<
  HTMLSpanElement,
  ArkTreeViewNodeCheckboxProps
>((props, ref) => {
  return (
    <TreeView.NodeCheckbox
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="node-checkbox"
    />
  );
});

LoongArkTreeViewNodeCheckbox.displayName = "LoongArkTreeViewNodeCheckbox";

export const LoongArkTreeViewNodeCheckboxIndicator = forwardRef<
  HTMLSpanElement,
  ArkTreeViewNodeCheckboxIndicatorProps
>((props, ref) => {
  return (
    <TreeView.NodeCheckboxIndicator
      {...props}
      data-scope="tree-view"
      data-part="node-checkbox-indicator"
    />
  );
});

LoongArkTreeViewNodeCheckboxIndicator.displayName =
  "LoongArkTreeViewNodeCheckboxIndicator";

export const LoongArkTreeViewNodeRenameInput = forwardRef<
  HTMLInputElement,
  ArkTreeViewNodeRenameInputProps
>((props, ref) => {
  return (
    <TreeView.NodeRenameInput
      {...props}
      ref={ref}
      data-scope="tree-view"
      data-part="node-rename-input"
    />
  );
});

LoongArkTreeViewNodeRenameInput.displayName = "LoongArkTreeViewNodeRenameInput";

// packages/solid/src/components/tree-view.tsx
/**
 * Tree View component - Solid wrapper.
 * Uses Ark UI Tree View with data attributes for styling.
 */
import { type Component, type JSX, mergeProps, splitProps } from "solid-js";
import {
  TreeView as ArkTreeView,
  type TreeViewRootProps as ArkTreeViewRootProps,
  type TreeViewLabelProps as ArkTreeViewLabelProps,
  type TreeViewTreeProps as ArkTreeViewTreeProps,
  type TreeViewItemProps as ArkTreeViewItemProps,
  type TreeViewItemIndicatorProps as ArkTreeViewItemIndicatorProps,
  type TreeViewItemTextProps as ArkTreeViewItemTextProps,
  type TreeViewBranchProps as ArkTreeViewBranchProps,
  type TreeViewBranchContentProps as ArkTreeViewBranchContentProps,
  type TreeViewBranchControlProps as ArkTreeViewBranchControlProps,
  type TreeViewBranchTriggerProps as ArkTreeViewBranchTriggerProps,
  type TreeViewBranchIndicatorProps as ArkTreeViewBranchIndicatorProps,
  type TreeViewBranchTextProps as ArkTreeViewBranchTextProps,
  type TreeViewBranchIndentGuideProps as ArkTreeViewBranchIndentGuideProps,
  type TreeViewNodeCheckboxProps as ArkTreeViewNodeCheckboxProps,
  type TreeViewNodeCheckboxIndicatorProps as ArkTreeViewNodeCheckboxIndicatorProps,
  type TreeViewNodeRenameInputProps as ArkTreeViewNodeRenameInputProps,
} from "@ark-ui/solid/tree-view";
import type { TreeViewSize } from "@loongark/primitives";

export interface LoongArkTreeViewRootProps<
  T extends object = object,
> extends Omit<ArkTreeViewRootProps<T>, "asChild"> {
  size?: TreeViewSize;
  children?: JSX.Element;
}

export const LoongArkTreeViewRoot = <T extends object>(
  props: LoongArkTreeViewRootProps<T>,
): JSX.Element => {
  const merged = mergeProps({ size: "md" as TreeViewSize }, props);
  const [local, others] = splitProps(merged, ["children", "size"]);

  return (
    <ArkTreeView.Root
      {...others}
      data-scope="tree-view"
      data-part="root"
      data-size={local.size}
    >
      {local.children}
    </ArkTreeView.Root>
  );
};

export interface LoongArkTreeViewLabelProps extends Omit<
  ArkTreeViewLabelProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewLabel: Component<LoongArkTreeViewLabelProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.Label {...others} data-scope="tree-view" data-part="label">
      {local.children}
    </ArkTreeView.Label>
  );
};

export interface LoongArkTreeViewTreeProps extends Omit<
  ArkTreeViewTreeProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewTree: Component<LoongArkTreeViewTreeProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.Tree {...others} data-scope="tree-view" data-part="tree">
      {local.children}
    </ArkTreeView.Tree>
  );
};

export interface LoongArkTreeViewItemProps extends Omit<
  ArkTreeViewItemProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewItem: Component<LoongArkTreeViewItemProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.Item {...others} data-scope="tree-view" data-part="item">
      {local.children}
    </ArkTreeView.Item>
  );
};

export interface LoongArkTreeViewItemIndicatorProps extends Omit<
  ArkTreeViewItemIndicatorProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewItemIndicator: Component<
  LoongArkTreeViewItemIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.ItemIndicator
      {...others}
      data-scope="tree-view"
      data-part="item-indicator"
    >
      {local.children}
    </ArkTreeView.ItemIndicator>
  );
};

export interface LoongArkTreeViewItemTextProps extends Omit<
  ArkTreeViewItemTextProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewItemText: Component<
  LoongArkTreeViewItemTextProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.ItemText
      {...others}
      data-scope="tree-view"
      data-part="item-text"
    >
      {local.children}
    </ArkTreeView.ItemText>
  );
};

export interface LoongArkTreeViewBranchProps extends Omit<
  ArkTreeViewBranchProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranch: Component<LoongArkTreeViewBranchProps> = (
  props,
) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.Branch {...others} data-scope="tree-view" data-part="branch">
      {local.children}
    </ArkTreeView.Branch>
  );
};

export interface LoongArkTreeViewBranchContentProps extends Omit<
  ArkTreeViewBranchContentProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranchContent: Component<
  LoongArkTreeViewBranchContentProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.BranchContent
      {...others}
      data-scope="tree-view"
      data-part="branch-content"
    >
      {local.children}
    </ArkTreeView.BranchContent>
  );
};

export interface LoongArkTreeViewBranchControlProps extends Omit<
  ArkTreeViewBranchControlProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranchControl: Component<
  LoongArkTreeViewBranchControlProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.BranchControl
      {...others}
      data-scope="tree-view"
      data-part="branch-control"
    >
      {local.children}
    </ArkTreeView.BranchControl>
  );
};

export interface LoongArkTreeViewBranchTriggerProps extends Omit<
  ArkTreeViewBranchTriggerProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranchTrigger: Component<
  LoongArkTreeViewBranchTriggerProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.BranchTrigger
      {...others}
      data-scope="tree-view"
      data-part="branch-trigger"
    >
      {local.children}
    </ArkTreeView.BranchTrigger>
  );
};

export interface LoongArkTreeViewBranchIndicatorProps extends Omit<
  ArkTreeViewBranchIndicatorProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranchIndicator: Component<
  LoongArkTreeViewBranchIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.BranchIndicator
      {...others}
      data-scope="tree-view"
      data-part="branch-indicator"
    >
      {local.children}
    </ArkTreeView.BranchIndicator>
  );
};

export interface LoongArkTreeViewBranchTextProps extends Omit<
  ArkTreeViewBranchTextProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranchText: Component<
  LoongArkTreeViewBranchTextProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.BranchText
      {...others}
      data-scope="tree-view"
      data-part="branch-text"
    >
      {local.children}
    </ArkTreeView.BranchText>
  );
};

export interface LoongArkTreeViewBranchIndentGuideProps extends Omit<
  ArkTreeViewBranchIndentGuideProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewBranchIndentGuide: Component<
  LoongArkTreeViewBranchIndentGuideProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.BranchIndentGuide
      {...others}
      data-scope="tree-view"
      data-part="branch-indent-guide"
    >
      {local.children}
    </ArkTreeView.BranchIndentGuide>
  );
};

export interface LoongArkTreeViewNodeCheckboxProps extends Omit<
  ArkTreeViewNodeCheckboxProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewNodeCheckbox: Component<
  LoongArkTreeViewNodeCheckboxProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.NodeCheckbox
      {...others}
      data-scope="tree-view"
      data-part="node-checkbox"
    >
      {local.children}
    </ArkTreeView.NodeCheckbox>
  );
};

export interface LoongArkTreeViewNodeCheckboxIndicatorProps extends Omit<
  ArkTreeViewNodeCheckboxIndicatorProps,
  "asChild"
> {
  children?: JSX.Element;
}

export const LoongArkTreeViewNodeCheckboxIndicator: Component<
  LoongArkTreeViewNodeCheckboxIndicatorProps
> = (props) => {
  const [local, others] = splitProps(props, ["children"]);
  return (
    <ArkTreeView.NodeCheckboxIndicator
      {...others}
      data-scope="tree-view"
      data-part="node-checkbox-indicator"
    >
      {local.children}
    </ArkTreeView.NodeCheckboxIndicator>
  );
};

export interface LoongArkTreeViewNodeRenameInputProps extends Omit<
  ArkTreeViewNodeRenameInputProps,
  "asChild"
> {}

export const LoongArkTreeViewNodeRenameInput: Component<
  LoongArkTreeViewNodeRenameInputProps
> = (props) => {
  return (
    <ArkTreeView.NodeRenameInput
      {...props}
      data-scope="tree-view"
      data-part="node-rename-input"
    />
  );
};
