// packages/react/src/components/use-rating.ts
import { useId } from "react";
import { useMachine, normalizeProps } from "@zag-js/react";
import { useEnvironmentContext } from "@ark-ui/react/environment";
import { useLocaleContext } from "@ark-ui/react/locale";
import { useFieldContext } from "@ark-ui/react/field";
import type {
  UseRatingGroupProps,
  UseRatingGroupReturn,
} from "@ark-ui/react/rating-group";
import {
  ratingGroupMachine,
  connectRatingGroup,
  definedRatingGroupProps,
} from "@loongark/kit";
export const useRatingGroup = (
  props: UseRatingGroupProps = {},
): UseRatingGroupReturn => {
  const id = useId(),
    env = useEnvironmentContext(),
    locale = useLocaleContext(),
    field = useFieldContext();
  return connectRatingGroup(
    useMachine(ratingGroupMachine, {
      id,
      dir: locale.dir,
      getRootNode: env.getRootNode,
      ids: {
        label: field?.ids.label,
        hiddenInput: field?.ids.control,
        ...props.ids,
      },
      disabled: field?.disabled,
      readOnly: field?.readOnly,
      required: field?.required,
      ...definedRatingGroupProps(props),
    }),
    normalizeProps,
  );
};

// packages/solid/src/components/use-rating.ts
import { createUniqueId, createMemo } from "solid-js";
import { useMachine, normalizeProps } from "@zag-js/solid";
import { useEnvironmentContext } from "@ark-ui/solid/environment";
import { useLocaleContext } from "@ark-ui/solid/locale";
import { useFieldContext } from "@ark-ui/solid/field";
import type {
  UseRatingGroupProps,
  UseRatingGroupReturn,
} from "@ark-ui/solid/rating-group";
import {
  ratingGroupMachine,
  connectRatingGroup,
  definedRatingGroupProps,
} from "@loongark/kit";
export const useRatingGroup = (
  props: UseRatingGroupProps = {},
): UseRatingGroupReturn => {
  const id = createUniqueId(),
    env = useEnvironmentContext(),
    locale = useLocaleContext(),
    field = useFieldContext();
  const options = createMemo(() => ({
    id,
    dir: locale().dir,
    getRootNode: env().getRootNode,
    ids: {
      label: field?.().ids.label,
      hiddenInput: field?.().ids.control,
      ...props.ids,
    },
    disabled: field?.().disabled,
    readOnly: field?.().readOnly,
    required: field?.().required,
    ...definedRatingGroupProps(props),
  }));
  const service = useMachine(ratingGroupMachine, options);
  return createMemo(() => connectRatingGroup(service, normalizeProps));
};
