// packages/react/src/provider.ts
import {
  useContext,
  useMemo,
  useEffect,
  useLayoutEffect,
  useRef,
  useId,
  createElement,
  ReactNode,
  FC,
} from "react";
import {
  createLoongArkTheme,
  LoongArkTheme,
  type CreateThemeOptions,
} from "@loongark/theme";
import { bootstrapKit } from "@loongark/kit/bootstrap";

import { ThemeContext } from "./theme-context";
const useThemeEffect =
  typeof document === "undefined" ? useEffect : useLayoutEffect;

export interface LoongArkProviderProps extends CreateThemeOptions {
  mode?: "light" | "dark" | "high-contrast";
  brand?: string;
  accent?: string;
  overrides?: CreateThemeOptions["overrides"];
  children?: ReactNode;
}

export const LoongArkProvider: FC<LoongArkProviderProps> = ({
  children,
  mode,
  brand,
  accent,
  overrides,
  targetId,
  motionPreference,
}) => {
  const scopeId = useId();
  const theme = useMemo(() => {
    const instance = createLoongArkTheme({
      mode,
      brand,
      accent,
      overrides,
      targetId: targetId ?? scopeId,
      motionPreference,
    });
    return instance;
  }, [mode, brand, accent, overrides, targetId, scopeId, motionPreference]);
  const scope = useRef<HTMLDivElement | null>(null);

  useThemeEffect(() => {
    if (!scope.current) return;
    theme.mount(scope.current);
    bootstrapKit(theme);
    return () => theme.unmount();
  }, [theme]);

  return createElement(
    ThemeContext.Provider,
    { value: theme },
    createElement(
      "div",
      { ref: scope, "data-lk-theme": theme.id, style: { display: "contents" } },
      children,
    ),
  );
};

export const useLoongArkTheme = () => {
  const theme = useContext(ThemeContext);
  if (!theme) {
    throw new Error("LoongArk theme context is missing");
  }
  return theme;
};

// packages/solid/src/provider.tsx
import {
  createMemo,
  createEffect,
  createUniqueId,
  onCleanup,
  type ParentComponent,
} from "solid-js";
import { createLoongArkTheme, type CreateThemeOptions } from "@loongark/theme";
import { bootstrapKit } from "@loongark/kit/bootstrap";
import { ThemeContext } from "./theme-context";
export type LoongArkProviderProps = CreateThemeOptions;
export const LoongArkProvider: ParentComponent<LoongArkProviderProps> = (
  props,
) => {
  let scope!: HTMLDivElement;
  const scopeId = createUniqueId();
  const theme = createMemo(() =>
    createLoongArkTheme({
      mode: props.mode,
      brand: props.brand,
      accent: props.accent,
      overrides: props.overrides,
      targetId: props.targetId ?? scopeId,
      motionPreference: props.motionPreference,
    }),
  );
  createEffect(() => {
    const instance = theme();
    instance.mount(scope);
    bootstrapKit(instance);
    onCleanup(() => instance.unmount());
  });
  return (
    <ThemeContext.Provider value={theme}>
      <div
        ref={scope}
        data-lk-theme={theme().id}
        style={{ display: "contents" }}
      >
        {props.children}
      </div>
    </ThemeContext.Provider>
  );
};
