// packages/svelte/src/components/Provider.svelte
<script lang="ts">
  import { setContext, onDestroy, type Snippet } from "svelte";
  import { writable } from "svelte/store";
  import {
    createLoongArkTheme,
    type CreateThemeOptions,
  } from "@loongark/theme";
  import { bootstrapKit } from "@loongark/kit/bootstrap";
  const scopeId = $props.id();
  let {
    mode = "light",
    brand,
    accent,
    overrides,
    targetId,
    motionPreference = "auto",
    children,
  }: CreateThemeOptions & { children?: Snippet } = $props();
  let scope = $state<HTMLDivElement>();
  const initialTheme = createLoongArkTheme({
    mode,
    brand,
    accent,
    overrides,
    targetId: targetId ?? scopeId,
    motionPreference,
  });
  let theme = $state(initialTheme);
  const store = writable(initialTheme);
  setContext("loongark-theme", store);
  $effect(() => {
    if (!scope) return;
    const next = createLoongArkTheme({
      mode,
      brand,
      accent,
      overrides,
      targetId: targetId ?? scopeId,
      motionPreference,
    });
    theme = next;
    next.mount(scope);
    bootstrapKit(next);
    store.set(next);
    return () => next.unmount();
  });
  onDestroy(() => theme.unmount());
</script>

<div bind:this={scope} data-lk-theme={theme.id} style="display: contents">
  {#if children}{@render children()}{/if}
</div>

// packages/solid/src/provider.tsx
import {
  createMemo,
  createEffect,
  createUniqueId,
  onCleanup,
  type ParentComponent,
} from "solid-js";
import { createLoongArkTheme, type CreateThemeOptions } from "@loongark/theme";
import { bootstrapKit } from "@loongark/kit/bootstrap";
import { ThemeContext } from "./theme-context";
export type LoongArkProviderProps = CreateThemeOptions;
export const LoongArkProvider: ParentComponent<LoongArkProviderProps> = (
  props,
) => {
  let scope!: HTMLDivElement;
  const scopeId = createUniqueId();
  const theme = createMemo(() =>
    createLoongArkTheme({
      mode: props.mode,
      brand: props.brand,
      accent: props.accent,
      overrides: props.overrides,
      targetId: props.targetId ?? scopeId,
      motionPreference: props.motionPreference,
    }),
  );
  createEffect(() => {
    const instance = theme();
    instance.mount(scope);
    bootstrapKit(instance);
    onCleanup(() => instance.unmount());
  });
  return (
    <ThemeContext.Provider value={theme}>
      <div
        ref={scope}
        data-lk-theme={theme().id}
        style={{ display: "contents" }}
      >
        {props.children}
      </div>
    </ThemeContext.Provider>
  );
};
