// examples/svelte/JsonTreeViewExample.svelte
<script lang="ts">
  import { controlIcons } from "@loongark/kit";
  import { LoongArkIcon } from "@loongark/svelte";

  import * as L from "@loongark/svelte";
  import { inspectionData } from "../shared/arkAdditionsDemo";
  let data = $state(inspectionData);
</script>

<L.LoongArkStack gap="md" style="width:100%;max-width:640px">
  <L.LoongArkTypography as="h2">Inspect structured data</L.LoongArkTypography>
  <L.LoongArkTypography variant="muted"
    >Expand branches with arrow keys. Values are rendered as text.</L.LoongArkTypography
  >
  <L.LoongArkButton
    type="button"
    variant="outline"
    onclick={() =>
      (data = {
        ...inspectionData,
        project: data.project === "LoongArk" ? "Updated project" : "LoongArk",
      })}>Update data</L.LoongArkButton
  >
  <L.LoongArkJsonTreeViewRoot {data} defaultExpandedDepth={1}
    ><L.LoongArkJsonTreeViewTree aria-label="Project data"
      >{#snippet arrow()}<span aria-hidden="true"
          ><LoongArkIcon icon={controlIcons.chevronRight} size="sm" /></span
        >{/snippet}</L.LoongArkJsonTreeViewTree
    ></L.LoongArkJsonTreeViewRoot
  >
</L.LoongArkStack>

// examples/react/JsonTreeViewExample.tsx
import { controlIcons } from "@loongark/kit";
import { LoongArkIcon } from "@loongark/react";
import { useState } from "react";
import * as L from "@loongark/react";
import { inspectionData } from "../shared/arkAdditionsDemo";
export function JsonTreeViewExample() {
  const [data, setData] = useState(inspectionData);
  return (
    <L.LoongArkStack gap="md" style={{ width: "100%", maxWidth: 640 }}>
      <L.LoongArkTypography as="h2">
        Inspect structured data
      </L.LoongArkTypography>
      <L.LoongArkTypography variant="muted">
        Expand branches with arrow keys. Values are rendered as text.
      </L.LoongArkTypography>
      <L.LoongArkButton
        type="button"
        variant="outline"
        onClick={() =>
          setData({
            ...inspectionData,
            project:
              data.project === "LoongArk" ? "Updated project" : "LoongArk",
          })
        }
      >
        Update data
      </L.LoongArkButton>
      <L.LoongArkJsonTreeViewRoot data={data} defaultExpandedDepth={1}>
        <L.LoongArkJsonTreeViewTree
          aria-label="Project data"
          arrow={
            <span aria-hidden="true">
              <LoongArkIcon icon={controlIcons.chevronRight} size="sm" />
            </span>
          }
        />
      </L.LoongArkJsonTreeViewRoot>
    </L.LoongArkStack>
  );
}
