// examples/svelte/ProgressExample.svelte
<script lang="ts">
  import {
    LoongArkProgressRoot,
    LoongArkProgressLabel,
    LoongArkProgressTrack,
    LoongArkProgressRange,
    LoongArkProgressValueText,
    LoongArkProgressView,
    LoongArkProgressCircle,
    LoongArkProgressCircleTrack,
    LoongArkProgressCircleRange,
  } from "@loongark/svelte";
  import type { ProgressOrientation, ProgressSize } from "@loongark/primitives";

  export let size: ProgressSize = "md";
  export let orientation: ProgressOrientation = "horizontal";
  export let value = 48;
</script>

<div style="display: grid; gap: 20px;">
  <LoongArkProgressRoot {value} {size} {orientation}>
    <LoongArkProgressLabel>Project setup</LoongArkProgressLabel>
    <LoongArkProgressTrack>
      <LoongArkProgressRange />
    </LoongArkProgressTrack>
    <LoongArkProgressValueText />
  </LoongArkProgressRoot>
  <LoongArkProgressRoot {value} {size}>
    <LoongArkProgressView state="loading">
      <LoongArkProgressCircle>
        <LoongArkProgressCircleTrack />
        <LoongArkProgressCircleRange />
      </LoongArkProgressCircle>
    </LoongArkProgressView>
    <LoongArkProgressValueText />
  </LoongArkProgressRoot>
</div>

// examples/react/ProgressExample.tsx
import React from "react";
import {
  LoongArkProgressRoot,
  LoongArkProgressLabel,
  LoongArkProgressTrack,
  LoongArkProgressRange,
  LoongArkProgressValueText,
  LoongArkProgressView,
  LoongArkProgressCircle,
  LoongArkProgressCircleTrack,
  LoongArkProgressCircleRange,
} from "@loongark/react";
import type { ProgressOrientation, ProgressSize } from "@loongark/primitives";

interface ProgressExampleProps {
  size?: ProgressSize;
  orientation?: ProgressOrientation;
  value?: number;
}

export const ProgressExample: React.FC<ProgressExampleProps> = ({
  size = "md",
  orientation = "horizontal",
  value = 48,
}) => {
  return (
    <div style={{ display: "grid", gap: 20 }}>
      <LoongArkProgressRoot value={value} size={size} orientation={orientation}>
        <LoongArkProgressLabel>Project setup</LoongArkProgressLabel>
        <LoongArkProgressTrack>
          <LoongArkProgressRange />
        </LoongArkProgressTrack>
        <LoongArkProgressValueText />
      </LoongArkProgressRoot>
      <LoongArkProgressRoot value={value} size={size}>
        <LoongArkProgressView state="loading">
          <LoongArkProgressCircle>
            <LoongArkProgressCircleTrack />
            <LoongArkProgressCircleRange />
          </LoongArkProgressCircle>
        </LoongArkProgressView>
        <LoongArkProgressValueText />
      </LoongArkProgressRoot>
    </div>
  );
};
