// examples/solid/QuestionnaireRatingControl.tsx
/** @jsxImportSource solid-js */
import { onMount, onCleanup } from "solid-js";
import * as L from "@loongark/solid";
import { controlIcons, type QuestionnaireCustomContext } from "@loongark/kit";
function Registration(props: {
  context: QuestionnaireCustomContext;
  element: () => HTMLElement;
}) {
  onMount(() =>
    onCleanup(
      props.context.registerControl({
        element: props.element(),
        focus: () =>
          props
            .element()
            .querySelector<HTMLElement>('[role="radio"][tabindex="0"]')
            ?.focus(),
      }),
    ),
  );
  return null;
}
export function QuestionnaireRatingControl(props: {
  context: QuestionnaireCustomContext;
  suggest: (context: QuestionnaireCustomContext) => void;
}) {
  let root!: HTMLDivElement;
  return (
    <L.LoongArkStack gap="sm">
      <div ref={root}>
        <L.LoongArkRatingGroupRoot
          value={Number(props.context.answer) || 0}
          disabled={props.context.disabled}
          count={5}
          required={props.context.question.required}
          size={
            props.context.question.customKind === "compact-rating" ? "sm" : "md"
          }
          ids={{
            label: props.context.labelId,
            control: props.context.controlId,
          }}
          onValueChange={({ value }) =>
            props.context.onAnswerChange(String(value))
          }
        >
          <L.LoongArkRatingGroupControl
            aria-required={props.context.question.required ? "true" : undefined}
            aria-describedby={
              props.context.descriptionId + " " + props.context.errorId
            }
            aria-invalid={props.context.invalid ? "true" : undefined}
          >
            {[1, 2, 3, 4, 5].map((index) => (
              <L.LoongArkRatingGroupItem
                {...(Number(props.context.answer) === 0 &&
                index === 1 &&
                !props.context.disabled
                  ? { tabIndex: 0 }
                  : {})}
                index={index}
              >
                <L.LoongArkIcon icon={controlIcons.star} size="lg" />
              </L.LoongArkRatingGroupItem>
            ))}
          </L.LoongArkRatingGroupControl>
          <Registration context={props.context} element={() => root} />
        </L.LoongArkRatingGroupRoot>
      </div>
      <L.LoongArkButton
        variant="outline"
        size="sm"
        disabled={props.context.disabled}
        onClick={() => props.suggest(props.context)}
      >
        Suggest five stars
      </L.LoongArkButton>
    </L.LoongArkStack>
  );
}

// examples/react/QuestionnaireRatingControl.tsx
import { useEffect, useRef } from "react";
import * as L from "@loongark/react";
import { controlIcons, type QuestionnaireCustomContext } from "@loongark/kit";
function Registration({
  context,
  element,
}: {
  context: QuestionnaireCustomContext;
  element: () => HTMLElement | null;
}) {
  useEffect(() => {
    const root = element();
    if (!root) return;
    return context.registerControl({
      element: root,
      focus: () =>
        root
          .querySelector<HTMLElement>('[role="radio"][tabindex="0"]')
          ?.focus(),
    });
  }, [context, element]);
  return null;
}
export function QuestionnaireRatingControl({
  context,
  suggest,
}: {
  context: QuestionnaireCustomContext;
  suggest: (context: QuestionnaireCustomContext) => void;
}) {
  const root = useRef<HTMLDivElement>(null);
  return (
    <L.LoongArkStack gap="sm">
      <div ref={root}>
        <L.LoongArkRatingGroupRoot
          value={Number(context.answer) || 0}
          disabled={context.disabled}
          count={5}
          required={context.question.required}
          size={context.question.customKind === "compact-rating" ? "sm" : "md"}
          ids={{ label: context.labelId, control: context.controlId }}
          onValueChange={({ value }) => context.onAnswerChange(String(value))}
        >
          <L.LoongArkRatingGroupControl
            aria-required={context.question.required ? "true" : undefined}
            aria-describedby={context.descriptionId + " " + context.errorId}
            aria-invalid={context.invalid ? "true" : undefined}
          >
            {[1, 2, 3, 4, 5].map((index) => (
              <L.LoongArkRatingGroupItem
                {...(Number(context.answer) === 0 &&
                index === 1 &&
                !context.disabled
                  ? { tabIndex: 0 }
                  : {})}
                index={index}
                key={index}
              >
                <L.LoongArkIcon icon={controlIcons.star} size="lg" />
              </L.LoongArkRatingGroupItem>
            ))}
          </L.LoongArkRatingGroupControl>
          <Registration context={context} element={() => root.current} />
        </L.LoongArkRatingGroupRoot>
      </div>
      <L.LoongArkButton
        variant="outline"
        size="sm"
        disabled={context.disabled}
        onClick={() => suggest(context)}
      >
        Suggest five stars
      </L.LoongArkButton>
    </L.LoongArkStack>
  );
}
